/* Isolated real browser checks. Never reads or seeds the player's browser profile. */
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'/Users/deanguedo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const base=process.env.WORLD_QA_URL||'http://localhost:8890/hub/',out=process.env.WORLD_QA_OUTPUT||'/tmp/unicorn-mall-qa';fs.mkdirSync(out,{recursive:true});
const results=[],errors=[],failed=[];const check=(name,details)=>{results.push({name,pass:true,details});console.log('PASS',name)};
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const c=await browser.newContext({viewport:{width:844,height:390},hasTouch:true});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.stack));p.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
 await p.goto(base+'?qa=1');await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);const state=()=>p.evaluate(()=>__WORLD_TEST__.snapshot()),profile=()=>p.evaluate(()=>__WORLD_TEST__.service.value);
 const close=async()=>{if(await p.locator('#panel').isVisible())await p.locator('#panel-close').click();await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().panel);};
 const nav=async id=>{await close();await p.evaluate(id=>__WORLD_TEST__.navigate(id),id);};
 const open=async id=>{await p.evaluate(id=>__WORLD_TEST__.mall.open(id),id);await p.waitForFunction(()=>__WORLD_TEST__.snapshot().panel);};
 const enter=async id=>{await nav('village');await p.evaluate(id=>{const d=__WORLD_TEST__.doors.find(d=>d.id===id);__WORLD_TEST__.place(d.x,d.y+45);},id);await p.locator('#enter').click();try{await p.waitForFunction(id=>__WORLD_TEST__.snapshot().frames.find(f=>f.id===id)?.ready,id);}catch(e){console.log('Startup diagnostics',await state(),errors,failed);await p.screenshot({path:out+'/startup-failure.png'});throw e;}return p.frames().find(f=>f.url().includes(id==='cafe'?'game/build':'adventure'));};
 const leave=async()=>{await close();await p.locator('#return').click();await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);};
 // Create native fixture in a standalone frame, before its first world connection.
 const native=await c.newPage();await native.goto('http://localhost:8890/game/build/?qa=1');await native.waitForFunction(()=>!!window.__RR_TEST__);await native.evaluate(()=>{const s=RR.fresh();s.coins=8;__RR_TEST__.loadFixture(s);});await native.close();
 let cafe=await enter('cafe');await p.waitForFunction(()=>__WORLD_TEST__.service.value.coins===8);check('Existing café earnings credit exactly once through actual bridge');await leave();cafe=await enter('cafe');await p.waitForTimeout(200);assert.equal((await profile()).coins,8);await leave();check('Game reentry does not repeat the old-coin credit');
 await nav('mall');await p.screenshot({path:out+'/mall-844x390.png'});await nav('boutique');await p.evaluate(()=>__WORLD_TEST__.place(240,560));await p.locator('#enter').click();await p.locator('[data-action="try"][data-item="flower-crown"]').click();assert.equal((await profile()).outfit.head,'bow');await p.screenshot({path:out+'/boutique-844x390.png'});await p.locator('[data-action="buy"][data-item="flower-crown"]').click();await p.waitForFunction(()=>__WORLD_TEST__.service.value.owned.includes('flower-crown'));assert.equal((await profile()).coins,5);assert.equal((await profile()).outfit.head,'flower-crown');
 await p.locator('[data-action="shop-tab"][data-slot="body"]').click();await p.locator('[data-action="try"][data-item="rainbow-dress"]').click();assert.equal(await p.locator('[data-action="buy"]').isDisabled(),true);await close();await nav('mall');assert.equal((await profile()).outfit.body,'tee');assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.previewOutfit),null);check('Buy and equip; unaffordable clothes can be tried on and do not escape fitting room');
 cafe=await enter('cafe');await cafe.evaluate(()=>__RR_TEST__.openRestaurant());await p.waitForTimeout(80);await p.screenshot({path:out+'/outfit-cafe.png'});assert.equal(await cafe.evaluate(()=>typeof UWArt.clothes),'function');
 await cafe.evaluate(()=>{const s=__RR_TEST__.snapshot();s.customers=[{id:123,table:0,dish:'pizza',variant:'tomato',type:'pink',phase:'paying',x:RR.CASHIER.x,y:RR.CASHIER.y,eat:1.2}];s.issued=1;s.nextId=124;__RR_TEST__.loadFixture(s);__RR_TEST__.tickRestaurant(.05);});await p.waitForFunction(()=>__WORLD_TEST__.service.value.coins===6);check('Real café payment hook adds one shared coin');
 await p.locator('#backpack').click();await p.locator('[data-action="bag-slot"][data-slot="head"]').click();await p.locator('[data-action="wear"][data-item="bow"]').click();await close();await p.waitForTimeout(80);await p.screenshot({path:out+'/cafe-backpack-change.png'});assert.equal((await profile()).outfit.head,'bow');await leave();
 let adventure=await enter('adventure');await adventure.evaluate(()=>{__qa.start(0);__qa.setup({game:{goalReady:true,catches:0}});__qa.finish();});await p.waitForFunction(()=>__WORLD_TEST__.service.value.coins===9);await adventure.evaluate(()=>__qa.finish());await p.waitForTimeout(120);assert.equal((await profile()).coins,9);await p.screenshot({path:out+'/outfit-adventure-win.png'});check('Adventure win pays three; duplicate completion does not pay twice');
 await adventure.evaluate(()=>{__qa.start(0);__qa.setup({game:{goalReady:true,catches:1}});__qa.finish();});await p.waitForFunction(()=>__WORLD_TEST__.service.value.coins===12);check('Legitimate replay completion pays again');await leave();
 // Durable receipt protection and simultaneous purchases use actual IndexedDB transactions.
 const atomic=await p.evaluate(async()=>{const s=__WORLD_TEST__.service;const e={id:'qa-duplicate-payment',kind:'payment'};const before=s.value.coins;await Promise.all([s.run('earn',{game:'cafe',event:e},e.id),s.run('earn',{game:'cafe',event:e},e.id)]);const earned=s.value.coins-before;await Promise.all([s.run('buy',{item:'sunhat'},'qa-buy-1'),s.run('buy',{item:'sunhat'},'qa-buy-2')]);return{earned,coins:s.value.coins};});assert.equal(atomic.earned,1);assert.equal(atomic.coins,10);check('Duplicate earned messages and concurrent purchases are charged/credited once');
 await nav('fitting');await open('closet');await p.locator('[data-action="shop-tab"][data-slot="outfits"]').click();await p.locator('[data-action="save-preset"][data-slot="1"]').click();await p.waitForFunction(()=>!!__WORLD_TEST__.service.value.outfits[1]);await close();await nav('photo');await open('take-photo');await p.locator('[data-action="save-photo"]').click();await p.waitForFunction(()=>__WORLD_TEST__.service.value.photos.length===1);await p.locator('[data-action="album"]').click();assert.equal(await p.locator('.photo-grid img').count(),1);await p.screenshot({path:out+'/photo-album.png'});check('Three-slot wardrobe and outfit photo album save actual rendered clothes');await close();
 await nav('arcade');await open('jigsaws');await p.waitForSelector('.puzzle-tile');let count=0,hashes=[];for(const theme of ['unicorns','animals','food','outfits','vehicles','places']){await p.locator('[data-action="theme"][data-theme="'+theme+'"]').click();count+=await p.locator('.puzzle-tile').count();const values=await p.locator('.puzzle-tile img').evaluateAll(ns=>ns.map(n=>n.src));hashes.push(...values.map(v=>crypto.createHash('sha256').update(v).digest('hex')));}assert.equal(count,48);assert.equal(new Set(hashes).size,48);check('All six themed shelves contain 48 distinct illustrated puzzles');await p.locator('[data-action="theme"][data-theme="animals"]').click();await p.locator('[data-action="picture"][data-puzzle="animals-3"]').click();await p.locator('[data-action="start"]').click();await p.waitForSelector('#round-canvas');let coins=(await profile()).coins;
 async function dragPiece(index){const info=await p.evaluate(i=>{const m=__WORLD_TEST__.mall,r=m.puzzleRects(),cv=m.cv.getBoundingClientRect(),fit=Math.min(cv.width/m.cv.width,cv.height/m.cv.height),left=cv.x+(cv.width-m.cv.width*fit)/2,top=cv.y+(cv.height-m.cv.height*fit)/2;const pt=(x,y)=>({x:left+x*fit,y:top+y*fit});m.selection=i;return{from:pt(r.tray.x,r.tray.y),to:pt(r.x+(i%r.n+.5)*r.cw,r.y+(Math.floor(i/r.n)+.5)*r.ch)};},index);await p.mouse.move(info.from.x,info.from.y);await p.mouse.down();await p.mouse.move(info.to.x,info.to.y,{steps:10});await p.mouse.up();}
 await dragPiece(0);await p.waitForFunction(()=>__WORLD_TEST__.service.value.sessions['animals-3:4'].state.placed.includes(0));await p.screenshot({path:out+'/jigsaw-partial.png'});await close();await p.reload();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);assert.equal((await profile()).coins,coins);assert.equal((await profile()).photos.length,1);assert.ok((await profile()).owned.includes('flower-crown'));await open('jigsaws');await p.waitForSelector('.puzzle-tile');await p.locator('[data-action="theme"][data-theme="animals"]').click();await p.locator('[data-action="picture"][data-puzzle="animals-3"]').click();await p.locator('[data-action="start"]').click();await p.waitForSelector('#round-canvas');assert.equal((await profile()).coins,coins);for(const i of [1,2,3])await dragPiece(i);await p.waitForFunction(()=>__WORLD_TEST__.service.value.sessions['animals-3:4'].status==='done');assert.equal((await profile()).coins,coins+1);assert.equal((await profile()).stamps,1);check('Real puzzle drag/snapping, reload resume without charge, one refund and stamp on completion');await close();
 // All three piece counts and paused sessions retain independent progress.
 const sizes=await p.evaluate(async()=>{const s=__WORLD_TEST__.service;for(const pieces of [9,16]){const r=await s.run('start',{game:'jigsaw',puzzle:'animals-3',pieces});await s.run('progress',{session:r.value.session.id,state:{placed:[0],guide:false}});}return Object.keys(s.value.sessions).filter(k=>k.startsWith('animals-3:'));});assert.deepEqual(sizes.sort(),['animals-3:16','animals-3:4','animals-3:9']);check('4-, 9-, and 16-piece puzzle saves are independent');
 await open('bowling');await p.locator('[data-action="start"]').click();await p.waitForSelector('#round-canvas');for(let i=0;i<3;i++){await p.evaluate(i=>{__WORLD_TEST__.mall.round.state.aim=[-.5,0,.45][i];},i);await p.locator('[data-action="roll"]').click();await p.waitForFunction(i=>__WORLD_TEST__.service.value.sessions.bowling.state.throws>i,i);}await p.waitForFunction(()=>__WORLD_TEST__.service.value.sessions.bowling.status==='done');assert.equal((await profile()).sessions.bowling.result.coins,2);await p.screenshot({path:out+'/bowling-result.png'});check('Playable three-throw bowling round awards score-based coins');await close();
 await open('catcher');await p.locator('[data-action="start"]').click();await p.waitForSelector('#round-canvas');const prior=(await profile()).coins;await p.setViewportSize({width:390,height:844});let elapsed=await p.evaluate(()=>__WORLD_TEST__.mall.round.state.elapsed);await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.round.state.elapsed),elapsed);await p.setViewportSize({width:844,height:390});await p.evaluate(()=>{__WORLD_TEST__.mall.round.state.elapsed=29.95;__WORLD_TEST__.mall.round.state.caught=Array.from({length:15},(_,i)=>i);});await p.waitForFunction(()=>__WORLD_TEST__.service.value.sessions.catcher.status==='done');assert.equal((await profile()).coins,prior+2);check('Star Catcher freezes in portrait and applies fifteen-star reward');await close();
 // Buying equipment, outdoor speed, automatic indoor parking, and free trial.
 await p.evaluate(async()=>{const s=__WORLD_TEST__.service;for(let i=0;i<15;i++)await s.run('earn',{game:'adventure',event:{id:'qa-funds-'+i,kind:'win'}},'qa-funds-'+i);});await nav('wheels');await open('wheel-shop');await p.locator('[data-action="buy-ride"][data-item="bike"]').click();await p.waitForFunction(()=>__WORLD_TEST__.service.value.owned.includes('bike'));await p.locator('[data-action="trial"][data-item="skateboard"]').click();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().scene==='track');assert.ok(!(await profile()).owned.includes('skateboard'));await p.screenshot({path:out+'/free-skateboard-trial.png'});await nav('street');const speed=await p.evaluate(async()=>{const w=__WORLD_TEST__;w.place(600,750);return w.snapshot().player.x;});await p.locator('#scene').focus();await p.keyboard.down('ArrowRight');await p.waitForTimeout(250);await p.keyboard.up('ArrowRight');assert.ok((await state()).player.x-speed>80);await nav('mall');assert.equal((await profile()).vehicle,'bike');check('Free equipment trial, permanent bike purchase, outdoor movement boost, indoor ownership retained');
 // Reset one native game preserves wallet/purchases and cannot reimport coins.
 cafe=await enter('cafe');const beforeReset=(await profile()).coins;await cafe.evaluate(()=>__RR_TEST__.route('reset-confirm'));await p.waitForTimeout(150);assert.equal((await profile()).coins,beforeReset);assert.ok((await profile()).owned.includes('bike'));await leave();cafe=await enter('cafe');await p.waitForTimeout(150);assert.equal((await profile()).coins,beforeReset);await leave();check('Café reset retains world possessions and does not repeat import');
 for(const[w,h]of[[568,320],[667,375],[844,390],[1280,720]]){await p.setViewportSize({width:w,height:h});await nav('boutique');await open('shop');const overflow=await p.evaluate(()=>{const r=document.getElementById('panel').getBoundingClientRect();return r.x<0||r.y<0||r.right>innerWidth||r.bottom>innerHeight;});assert.equal(overflow,false);assert.equal(await p.locator('[data-action="try"]').count()>0,true);await p.screenshot({path:out+`/shop-${w}x${h}.png`});await close();await nav('fitting');await open('closet');await p.locator('[data-action="shop-tab"][data-slot="outfits"]').click();assert.equal(await p.locator('[data-action="save-preset"]').count(),3);await p.screenshot({path:out+`/outfits-${w}x${h}.png`});await close();}check('Four landscape layouts keep boutique, outfit cards and 44px controls accessible');
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);check('No runtime exceptions or failed asset requests');
 // Simulated persistence failure must never pretend a purchase worked.
 const failure=await p.evaluate(async()=>{const s=__WORLD_TEST__.service,before=JSON.stringify(s.value);const old=s.db;s.db=null;let code;try{await s.run('buy',{item:'skateboard'});}catch(e){code=e.code;}s.db=old;return{code,same:before===JSON.stringify(s.value)};});assert.deepEqual(failure,{code:'storage',same:true});check('Unavailable saving does not deduct money or grant an item');
 fs.writeFileSync(out+'/QA-RESULTS.json',JSON.stringify({results,errors,failed,physicalDevice:false,childReview:false},null,2));await browser.close();console.log('Evidence:',out);
})().catch(e=>{console.error(e);fs.writeFileSync(out+'/QA-FAILURE.txt',e.stack);process.exit(1)});
