const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'/Users/deanguedo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');const out=process.env.WORLD_QA_OUTPUT||'/tmp/unicorn-mall-compatibility';fs.mkdirSync(out,{recursive:true});const results=[];
(async()=>{for(const [name,type,root]of[['Chromium legacy origins',chromium,'http://localhost:8790/hub/?legacy=1&qa=1'],['WebKit same origin',webkit,'http://localhost:8890/hub/?qa=1']]){
 const b=await type.launch({headless:true,...(type===chromium?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});try{const c=await b.newContext({viewport:{width:844,height:390},hasTouch:true});if(root.includes('legacy'))await c.route('http://localhost:8790/**',async route=>{if(!['image','script'].includes(route.request().resourceType()))return route.continue();const response=await route.fetch(),headers=response.headers();delete headers['access-control-allow-origin'];await route.fulfill({response,headers});});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(root);await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);
 for(const game of['cafe','adventure']){await p.evaluate(game=>{const w=__WORLD_TEST__,d=w.doors.find(d=>d.id===game);w.place(d.x,d.y+45);w.enter();},game);await p.waitForFunction(game=>__WORLD_TEST__.snapshot().frames.find(f=>f.id===game)?.ready,game);const f=p.frames().find(f=>f.url().includes(game==='cafe'?root.includes('legacy')?':8787':'game/build':root.includes('legacy')?':8788':'adventure'));
 if(game==='cafe'){await f.evaluate(()=>__RR_TEST__.openRestaurant());}else{await f.evaluate(()=>{__qa.start(0);__qa.setup({game:{entryGrace:10,hitStop:0}});});await f.evaluate(()=>{const nodes=__qa.nodes(false),keys=new Set(nodes.map(p=>p.x+':'+p.y));const p=nodes.find(p=>p.x>1000&&p.y>500&&p.y<900&&keys.has((p.x-96)+':'+p.y))||nodes.find(p=>p.x>300&&p.y>300);__qa.place(p.x,p.y);__qa.manual(false);});const beforeState=await f.evaluate(()=>SneakyUnicorn.snapshot());const before=beforeState.player.x;await f.waitForFunction(()=>!SneakyUnicorn.snapshot().hubPaused);await f.locator('#game').focus();await p.keyboard.down('ArrowLeft');await p.waitForTimeout(350);await p.keyboard.up('ArrowLeft');const after=await f.evaluate(()=>SneakyUnicorn.snapshot().player.x);if(Math.abs(after-before)<=5)console.log('Movement diagnostics',name,beforeState,await f.evaluate(()=>SneakyUnicorn.snapshot()));assert.ok(Math.abs(after-before)>5,'Open-floor keyboard movement');}
 await p.locator('#backpack').click();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().panel);await p.locator('[data-action="bag-slot"][data-slot="head"]').click();await p.locator('[data-action="wear"][data-item="bow"]').click();await p.locator('#panel-close').click();await p.locator('#return').click();await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);
 }
 assert.deepEqual(errors,[]);const prof=await p.evaluate(()=>__WORLD_TEST__.service.public());assert.ok(prof.owned.includes('legacy-princess'));await p.evaluate(()=>__WORLD_TEST__.navigate('arcade'));await p.evaluate(()=>__WORLD_TEST__.mall.open('jigsaws'));await p.waitForSelector('.puzzle-tile');assert.equal(await p.locator('.puzzle-tile').count(),8);await p.screenshot({path:out+'/'+name.replaceAll(' ','-')+'.png'});results.push({name,pass:true});console.log('PASS',name,'games, backpack, movement, puzzle library');await c.unrouteAll({behavior:'wait'});}finally{await b.close();}}
 fs.writeFileSync(out+'/QA-RESULTS.json',JSON.stringify({results,physicalSafari:false,physicalDevice:false},null,2));})().catch(e=>{console.error(e);fs.writeFileSync(out+'/QA-FAILURE.txt',e.stack);process.exit(1)});
