/* Isolated navigation, appearance pixels and actual save/return checks. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/deanguedo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const out=process.env.WORLD_QA_OUTPUT||'/tmp/unicorn-navigation-qa',results=[],errors=[],failed=[];fs.mkdirSync(out,{recursive:true});
const check=(name,details)=>{results.push({name,pass:true,details});console.log('PASS',name);};
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const context=await b.newContext({viewport:{width:852,height:393},hasTouch:true}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push({url:r.url(),status:r.status()});});
 await p.goto('http://localhost:8890/hub/?qa=1');await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);await p.waitForTimeout(40);
 const state=()=>p.evaluate(()=>__WORLD_TEST__.snapshot());const shot=name=>p.screenshot({path:out+'/'+name+'.png'});
 const point=(x,y)=>p.evaluate(({x,y})=>__WORLD_TEST__.screenPoint(x,y),{x,y});
 const tap=async(x,y)=>{const q=await point(x,y);await p.mouse.click(q.x,q.y);};
 const scenes=['village','street','mall','boutique','fitting','wheels','track','arcade','photo'];let entranceCount=0;
 for(const scene of scenes){await p.evaluate(scene=>__WORLD_TEST__.navigate(scene),scene);await p.waitForTimeout(420);assert.equal((await state()).scene,scene,'Arrival does not auto-exit');const ds=await p.evaluate(()=>__WORLD_TEST__.doors.map(d=>({id:d.id,zone:UWPortals.approach(d)})));
  for(const d of ds){await p.evaluate(({scene,z})=>{__WORLD_TEST__.navigate(scene);__WORLD_TEST__.place(z.x,z.y+100);},{scene,z:d.zone});await tap(d.zone.x,d.zone.y);await p.waitForFunction(id=>__WORLD_TEST__.snapshot().focused===id,d.id);await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().target);assert.equal((await state()).scene,scene);assert.equal((await state()).active,null);assert.equal((await state()).panel,false);assert.equal(await p.locator('#enter').isEnabled(),true);assert.ok(d.zone.rx*2>250&&d.zone.ry*2>140);entranceCount++;if(!['cafe','adventure'].includes(d.id)){await p.locator('#enter').click();if(scenes.includes(d.id))assert.equal((await state()).scene,d.id);else{assert.equal((await state()).panel,true);await p.locator('#panel-close').click();}}}
  await p.evaluate(scene=>__WORLD_TEST__.navigate(scene),scene);await p.evaluate(()=>document.getElementById('guide').classList.remove('show'));await shot(scene+'-852x393');check('Reachable picture-guided approaches and explicit actions: '+scene,{entrances:ds.length});
 }
 check('Large entrance areas keep scenes unchanged until the action button is pressed',{entranceCount});
 const parents={street:'village',mall:'street',boutique:'mall',fitting:'boutique',wheels:'mall',track:'wheels',arcade:'mall',photo:'mall'};
 for(const scene of Object.keys(parents)){await p.evaluate(scene=>{__WORLD_TEST__.navigate(scene);const z=__WORLD_TEST__.snapshot().exit;__WORLD_TEST__.place(z.x+200,z.y)},scene);const z=(await state()).exit;await tap(z.x,z.y);await p.waitForFunction(parent=>__WORLD_TEST__.snapshot().scene===parent,parents[scene]);assert.equal((await state()).panel,false);}
 check('Actual taps walk to all eight exit areas and return to the correct parent');
 await p.evaluate(()=>{__WORLD_TEST__.navigate('arcade');const z=__WORLD_TEST__.snapshot().exit;__WORLD_TEST__.place(z.x,z.y)});await p.waitForTimeout(650);assert.equal((await state()).scene,'arcade');await p.reload();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);await p.waitForTimeout(650);assert.equal((await state()).scene,'arcade');await p.locator('#enter').click();assert.equal((await state()).scene,'mall');check('Reloading or arriving on an exit does not create a return loop; its action button still works');
 await p.evaluate(()=>{__WORLD_TEST__.navigate('photo');const z=__WORLD_TEST__.snapshot().exit;__WORLD_TEST__.place(z.x+200,z.y)});let z=(await state()).exit;await tap(z.x,z.y);await p.setViewportSize({width:393,height:852});await p.waitForTimeout(650);assert.equal((await state()).scene,'photo');assert.equal((await state()).target,null);await p.setViewportSize({width:852,height:393});await p.waitForTimeout(500);assert.equal((await state()).scene,'photo');await p.locator('#backpack').click();await p.waitForTimeout(500);assert.equal((await state()).scene,'photo');await p.locator('#panel-close').click();check('Portrait and backpack pause navigation without an accidental exit');
 for(const scene of scenes){await p.setViewportSize({width:568,height:320});await p.evaluate(scene=>__WORLD_TEST__.navigate(scene),scene);const bs=await p.evaluate(()=>[...document.querySelectorAll('#world-tools button,#enter')].filter(el=>el.getClientRects().length).map(el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom}}));assert.ok(bs.every(r=>r.w>=44&&r.h>=44&&r.x>=0&&r.y>=0&&r.right<=568&&r.bottom<=320));await shot(scene+'-568x320');}check('All nine world scenes keep 44px controls and clean floor cues at 568x320');await p.setViewportSize({width:852,height:393});
 // Each completed body/neck accessory must preserve eyes and muzzle pixels.
 const face=await p.evaluate(()=>{const A=UWArt,poses=[...UWArtSprites.frames,...Array.from({length:4},(_,i)=>'bike'+i),...Array.from({length:4},(_,i)=>'skateboard'+i)],body=['tee','star-jacket','rainbow-dress','raincoat','prize-rainbow-cape','legacy-hero'],neck=['beads','scarf','prize-gold-scarf','satchel','prize-moon-bag'],heads=['bow','flower-crown','sunhat','helmet','prize-star-bow','prize-comet-helmet','legacy-princess','legacy-chef'];let checked=0,fail=[];function render(key,outfit,flip){const cv=document.createElement('canvas');cv.width=cv.height=192;const c=cv.getContext('2d'),p=A.poses[key];const [l,t,r,b]=p.bounds;c.save();if(flip){c.translate(192,0);c.scale(-1,1);}if(p.source){const e=p.source;c.drawImage(A.images[e.source],...e.rect,l,t,r-l,b-t);}else c.drawImage(A.images[key],l,t,r-l,b-t);c.restore();c.save();c.translate(96,184.5);A.clothes(c,outfit,192,flip,key,true);c.restore();return c.getImageData(0,0,192,192).data;}
  for(const key of poses)for(const flip of[false,true]){const pose=A.poses[key],base=render(key,{},flip),samples=[];const regions=[[pose.eyes[0],pose.eyes[1],7],[pose.neck[0]+6,pose.neck[1]-11,5]];for(const[x,y,r]of regions)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){const px=Math.round(flip?191-(x+dx):x+dx),py=Math.round(y+dy),i=(py*192+px)*4;if(base[i+3]>245)samples.push(i);}
   for(const id of[...body,...neck,...heads]){const outfit=body.includes(id)?{body:id}:heads.includes(id)?{head:id}:{accessory:id},actual=render(key,outfit,flip);const mismatched=samples.filter(i=>[0,1,2].some(n=>Math.abs(base[i+n]-actual[i+n])>4));if(mismatched.length>samples.length*.025)fail.push({key,flip,id,mismatched:mismatched.length,pixels:samples.length});checked++;}}
  return{checked,fail};});if(face.fail.length)throw Error('Face obstruction: '+JSON.stringify(face.fail.slice(0,12))); check('Clothing, necklaces, scarves, bags and hats keep original eyes/muzzle clear in every walking, riding and celebration pose, both directions',{renderComparisons:face.checked});
 // Both native games use the authoritative pause/save acknowledgement to leave.
 async function enter(id){await p.evaluate(id=>{const w=__WORLD_TEST__;w.navigate('village');const d=w.doors.find(d=>d.id===id);w.place(d.x,d.y+55);w.enter()},id);await p.waitForFunction(id=>__WORLD_TEST__.snapshot().frames.find(f=>f.id===id)?.ready,id);return p.frames().find(f=>f.url().includes(id==='cafe'?'game/build/':'adventure/'));}
 await p.evaluate(async()=>{const s=__WORLD_TEST__.service;for(let i=0;i<2;i++)await s.run('earn',{game:'adventure',event:{id:'nav-funds-'+i,kind:'win'}},'nav-funds-'+i);await s.run('buy',{item:'star-jacket',equip:true});await s.run('equip',{item:'beads'});});
 let cafe=await enter('cafe');await cafe.evaluate(()=>{__RR_TEST__.openRestaurant();const s=RR.fresh();s.customers=[{id:911,table:0,dish:'pizza',variant:'tomato',type:'pink',phase:'ordered',x:RR.TABLES[0].seat.x,y:RR.TABLES[0].seat.y,eat:0}];s.issued=1;s.nextId=912;s.active=911;s.tray={orderId:911,dish:'pizza',variant:'tomato',deco:null};__RR_TEST__.loadFixture(s);const z=__RR_TEST__.worldExit;__RR_TEST__.setPlayer(z.x-170,z.y);});
 const cz=await cafe.evaluate(()=>{const z=__RR_TEST__.worldExit;return __RR_TEST__.worldToScreen(z.x,z.y)});await cafe.locator('#world').click({position:cz});await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);const savedCafe=await cafe.evaluate(()=>__RR_TEST__.snapshot());assert.equal(savedCafe.tray.dish,'pizza');assert.equal(savedCafe.total,0);await p.waitForTimeout(550);assert.deepEqual(await cafe.evaluate(()=>__RR_TEST__.snapshot()),savedCafe);cafe=await enter('cafe');await p.waitForTimeout(650);assert.equal((await state()).active,'cafe');assert.deepEqual(await cafe.evaluate(()=>__RR_TEST__.snapshot().tray),savedCafe.tray);await shot('cafe-exit-and-necklace');await cafe.locator('#primary').click();await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);check('Café exit walks, saves its carried meal, pauses and resumes without a loop; lower-right return also works');
 cafe=await enter('cafe');
 for(let table=0;table<5;table++){
  await cafe.evaluate(table=>{const s=RR.fresh(),t=RR.TABLES[table];s.customers=[{id:920+table,table,dish:'pizza',variant:'tomato',type:'pink',phase:'ordered',x:t.seat.x,y:t.seat.y,eat:0}];s.issued=1;s.nextId=930;s.active=920+table;s.tray={orderId:920+table,dish:'pizza',variant:'tomato',deco:null};__RR_TEST__.loadFixture(s);__RR_TEST__.setPlayer(t.meet.x,t.meet.y);__RR_TEST__.updateHUD(true);__RR_TEST__.drawWorld();},table);
  assert.equal(await cafe.locator('#primary').getAttribute('aria-label'),'Serve the meal');await p.waitForTimeout(430);assert.equal((await state()).active,'cafe');await cafe.locator('#primary').click();assert.equal(await cafe.evaluate(()=>__RR_TEST__.snapshot().tray),null);assert.ok(['eating','finished'].includes(await cafe.evaluate(()=>__RR_TEST__.snapshot().customers[0].phase)));
 }
 // Tap the original door illustration as well as the floor cue.
 await cafe.evaluate(()=>{const z=__RR_TEST__.worldExit;__RR_TEST__.setPlayer(z.x-200,z.y);__RR_TEST__.drawWorld();});const doorPoint=await cafe.evaluate(()=>__RR_TEST__.worldToScreen(1490,950));await cafe.locator('#world').click({position:doorPoint});await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);
 check('The café exit preserves all five table actions, including the diamond table; tapping the original doorway also returns');
 const adventure=await enter('adventure');const levels=await adventure.evaluate(()=>__qa.levels().map((l,i)=>{__qa.start(i);const z=__qa.worldExit;if(!z)return{id:l.id,ok:false};return{id:l.id,ok:__qa.valid(z.x,z.y)&&__qa.path(z.x,z.y).length>0,exit:z,home:__qa.level().home}}));assert.ok(levels.every(l=>l.ok),JSON.stringify(levels));for(const l of levels)assert.ok(Math.hypot(l.exit.x-l.home.x,l.exit.y-l.home.y)>l.home.safe);check('All nine adventure maps have a reachable return area separate from their native treasure goal',{maps:levels});
 await adventure.evaluate(()=>{__qa.start(0);__qa.manual(false);__qa.setup({game:{entryGrace:100,hitStop:0}});const it=SneakyUnicorn.snapshot().items[0];__qa.place(it.x,it.y);__qa.collect();const z=__qa.worldExit;__qa.place(z.x+z.rx+38,z.y);});
 const az=await adventure.evaluate(()=>__qa.worldExit);await adventure.locator('#game').focus();await p.keyboard.down('ArrowLeft');await adventure.waitForFunction(()=>UWPortals.contains(__qa.worldExit,SneakyUnicorn.snapshot().player));await p.keyboard.up('ArrowLeft');await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);const as=await adventure.evaluate(()=>SneakyUnicorn.snapshot());assert.equal(as.carry.count,1);await p.waitForTimeout(500);assert.deepEqual(await adventure.evaluate(()=>SneakyUnicorn.snapshot().player),as.player);await enter('adventure');await p.waitForTimeout(650);assert.equal((await state()).active,'adventure');assert.deepEqual(await adventure.evaluate(()=>SneakyUnicorn.snapshot().player),as.player);assert.equal(await adventure.evaluate(()=>SneakyUnicorn.snapshot().carry.count),1);await shot('adventure-exit-and-necklace');check('Actual adventure walking reaches its exit and retains carried treasure and in-flight position on reentry');
 await p.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'UNICORN_WORLD',command:'return'},origin:location.origin,source:window})));assert.equal((await state()).active,'adventure');await p.locator('#return').click();await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);const profile=await p.evaluate(()=>__WORLD_TEST__.service.public());await p.reload();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);const reloaded=await p.evaluate(()=>__WORLD_TEST__.service.public());assert.equal(reloaded.coins,profile.coins);assert.deepEqual(reloaded.owned,profile.owned);assert.deepEqual(reloaded.outfit,profile.outfit);check('Forged return messages are ignored; navigation/reload retain the wallet, purchases and equipped outfit');
 for(const path of['game/build/','adventure/']){const solo=await context.newPage();await solo.goto('http://localhost:8890/'+path+'?qa=1');await solo.waitForFunction(()=>!!(window.__RR_TEST__||window.__qa));assert.equal(await solo.evaluate(()=>window.UWPortals===undefined),true);await solo.close();}check('Standalone games retain native navigation and do not load world exit cues');
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);check('No page exceptions or missing artwork');fs.writeFileSync(out+'/QA-RESULTS.json',JSON.stringify({results,errors,failed,physicalDevice:false,childReview:false},null,2));
 }finally{await b.close();}})().catch(e=>{console.error(e);fs.writeFileSync(out+'/QA-FAILURE.txt',e.stack);process.exit(1)});
