/* Generated sprite menus and real pointer bowling. Fresh storage; never uses her profile. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/deanguedo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const out=process.env.WORLD_QA_OUTPUT||'/tmp/unicorn-picture-menus',base=process.env.WORLD_QA_URL||'http://localhost:8890/hub/';
fs.mkdirSync(out,{recursive:true});const results=[],errors=[],failed=[];
const check=(name,details)=>{results.push({name,pass:true,details});console.log('PASS',name);};
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try{
 const context=await browser.newContext({viewport:{width:852,height:393},hasTouch:true}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
 await p.goto(base+'?qa=1');await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);
 const profile=()=>p.evaluate(()=>__WORLD_TEST__.service.value),close=async()=>{if(await p.locator('#panel').isVisible())await p.locator('#panel-close').click();await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().panel);};
 async function open(kind,scene){await close();if(scene)await p.evaluate(scene=>__WORLD_TEST__.navigate(scene),scene);await p.evaluate(kind=>__WORLD_TEST__.mall.open(kind),kind);await p.waitForFunction(()=>__WORLD_TEST__.snapshot().panel);if(kind==='library')await p.waitForSelector('.puzzle-tile');await p.locator('#panel-body img').evaluateAll(ns=>Promise.all(ns.map(im=>im.complete?Promise.resolve():new Promise(r=>im.onload=r))));}
 async function bottomRight(selector){const r=await p.locator(selector).boundingBox(),v=p.viewportSize();assert.ok(r&&r.width>=44&&r.height>=44,selector+' touch target');assert.ok(r.x+r.width/2>v.width*.78&&r.y+r.height/2>v.height*.75,selector+' lower right');}
 const art=await p.evaluate(()=>({items:Object.keys(UWArtSprites.items).length,icons:Object.keys(UWArtSprites.icons).length,bodyFrames:UWArt.fitted.manifest.fit_record_count,rides:Object.values(UWArtSprites.rides).reduce((n,poses)=>n+Object.keys(poses).length,0),allLoaded:Object.values(UWArt.images).every(im=>im.complete&&im.naturalWidth>0)}));
 assert.deepEqual(art,{items:25,icons:36,bodyFrames:437,rides:8,allLoaded:true});check('25 illustrated items, 36 controls, 437 fitted item/pose records and eight riding poses load successfully',art);
 await p.evaluate(async()=>{const s=__WORLD_TEST__.service;for(let i=0;i<30;i++)await s.run('earn',{game:'adventure',event:{id:'picture-qa-funds-'+i,kind:'win'}},'picture-qa-funds-'+i);});
 for(const [width,height]of[[852,393],[568,320]]){
  await p.setViewportSize({width,height});
  const spacing=await p.evaluate(()=>{const r=el=>{const b=el.getBoundingClientRect();return{x:b.x,y:b.y,right:b.right,bottom:b.bottom};};const buttons=[...document.querySelectorAll('#world-tools button')].filter(b=>b.getClientRects().length);return buttons.map(b=>{const box=r(b),im=r(b.querySelector('img'));return{left:box.x,top:box.y,right:innerWidth-box.right,height:b.offsetHeight,pad:Math.min(im.x-box.x,box.right-im.right,im.y-box.y,box.bottom-im.bottom)};});});
  assert.ok(spacing.every(q=>q.left>=8&&q.top>=6&&q.right>=8&&q.height>=44&&q.pad>=5),JSON.stringify(spacing));
  await open('shop','boutique');await bottomRight('.shop-actions .primary-action');assert.equal(await p.locator('#panel svg').count(),0);await p.locator('[data-action="try"][data-item="bow"]').click();await bottomRight('.shop-actions .primary-action');await p.locator('[data-action="try"][data-item="flower-crown"]').click();await p.screenshot({path:out+`/boutique-${width}x${height}.png`});
  await open('wheel-shop','wheels');await p.locator('[data-action="preview-ride"][data-item="bike"]').click();await p.waitForTimeout(250);await p.screenshot({path:out+`/bike-${width}x${height}.png`});await p.locator('[data-action="preview-ride"][data-item="skateboard"]').click();await p.waitForTimeout(250);await p.screenshot({path:out+`/skateboard-${width}x${height}.png`});
  await open('photo','photo');await bottomRight('[data-action="save-photo"]');const photo=await p.evaluate(()=>{const cv=document.querySelector('.photo-preview'),r=cv.getBoundingClientRect();return{ratio:cv.width/cv.height,boxRatio:(r.width-10)/(r.height-10)};});assert.ok(Math.abs(photo.ratio-photo.boxRatio)<.004);await p.screenshot({path:out+`/photo-${width}x${height}.png`});
  await open('library','arcade');const fits=await p.locator('.puzzle-tile').evaluateAll(bs=>bs.every(b=>{const r=b.getBoundingClientRect(),im=b.querySelector('img').getBoundingClientRect();return im.x>=r.x+6&&im.y>=r.y+6&&im.right<=r.right-6&&im.bottom<=r.bottom-6;}));assert.equal(fits,true,'Puzzle illustrations stay inside their tiles');await bottomRight('.puzzle-footer .primary-action');await p.screenshot({path:out+`/library-${width}x${height}.png`});
  await open('bowling','arcade');await bottomRight('[data-action="start"]');await p.screenshot({path:out+`/bowling-preview-${width}x${height}.png`});await open('catcher','arcade');await bottomRight('[data-action="start"]');await p.screenshot({path:out+`/catcher-preview-${width}x${height}.png`});
  check('Illustrated menus fit '+width+'x'+height+' landscape: padded toolbar, contained pictures and lower-right actions');
 }
 await p.setViewportSize({width:852,height:393});await open('bowling','arcade');const before=await profile();await p.locator('[data-action="demo"]').click();await p.waitForSelector('#round-canvas');await bottomRight('[data-action="roll"]');
 const touch=await context.newCDPSession(p);
 async function aim(value,useTouch=false){const q=await p.evaluate(value=>{const cv=__WORLD_TEST__.mall.cv,r=cv.getBoundingClientRect(),fit=Math.min(r.width/cv.width,r.height/cv.height),left=r.x+(r.width-cv.width*fit)/2,top=r.y+(r.height-cv.height*fit)/2;return{from:{x:left+450*fit,y:top+cv.height*.75*fit},to:{x:left+(450+280*value)*fit,y:top+cv.height*.65*fit}};},value);if(useTouch){await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[q.from]});for(let i=1;i<=8;i++)await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:q.from.x+(q.to.x-q.from.x)*i/8,y:q.from.y+(q.to.y-q.from.y)*i/8}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{await p.mouse.move(q.from.x,q.from.y);await p.mouse.down();await p.mouse.move(q.to.x,q.to.y,{steps:8});await p.mouse.up();}await p.waitForFunction(value=>Math.abs(__WORLD_TEST__.mall.round.state.aim-value)<.005,value);}
 await aim(-.5);await p.screenshot({path:out+'/bowling-aim-left.png'});await p.locator('[data-action="roll"]').click();assert.equal(await p.locator('[data-action="roll"]').isDisabled(),true);await p.waitForFunction(()=>__WORLD_TEST__.mall.ball?.t>1.12);await p.screenshot({path:out+'/bowling-visible-impact.png'});await p.waitForFunction(()=>__WORLD_TEST__.mall.round.state.throws===1);assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.round.state.score),6);
 await aim(0,true);await p.locator('[data-action="roll"]').click();await p.waitForFunction(()=>__WORLD_TEST__.mall.ball?.t>.25);const t=await p.evaluate(()=>__WORLD_TEST__.mall.ball.t);await p.setViewportSize({width:393,height:852});await p.waitForTimeout(350);const paused=await p.evaluate(()=>__WORLD_TEST__.mall.ball.t);assert.ok(paused>=t&&paused-t<.065);assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.drag),null);assert.equal(await p.locator('#rotate').isVisible(),true);await p.setViewportSize({width:852,height:393});await p.waitForFunction(()=>__WORLD_TEST__.mall.round.state.throws===2);assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.round.state.score),16);
 await aim(0);await p.locator('[data-action="roll"]').click();await p.waitForFunction(()=>__WORLD_TEST__.mall.round.status==='done');const after=await profile();assert.equal(after.coins,before.coins);assert.equal(after.stamps,before.stamps);assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.round.state.score),26);check('Real mouse/touch aiming, six-pin hit, fresh ten-pin throws, visible impact and portrait pause; free demonstration changes no money or stamps');
 await open('bowling','arcade');await p.locator('[data-action="start"]').click();await p.waitForSelector('#round-canvas');assert.equal((await profile()).coins,before.coins-1);await aim(0);await p.locator('[data-action="roll"]').click();await p.waitForFunction(()=>__WORLD_TEST__.service.value.sessions.bowling.state.throws===1);await close();await p.reload();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);await open('bowling','arcade');await p.locator('[data-action="start"]').click();await p.waitForSelector('#round-canvas');assert.equal((await profile()).coins,before.coins-1);assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.round.state.throws),1);
 for(const n of[2,3]){await aim(0);await p.locator('[data-action="roll"]').click();await p.waitForFunction(n=>__WORLD_TEST__.service.value.sessions.bowling.state.throws===n,n);}await p.waitForFunction(()=>__WORLD_TEST__.service.value.sessions.bowling.status==='done');const done=await profile();assert.equal(done.coins,before.coins+1);assert.equal(done.stamps,before.stamps+1);assert.equal(done.sessions.bowling.result.score,30);const repeat=await p.evaluate(()=>{const s=__WORLD_TEST__.service,r=s.value.sessions.bowling;return s.run('finish',{session:r.id,state:r.state});});assert.equal((await profile()).coins,done.coins);assert.equal((await profile()).stamps,done.stamps);check('Paid bowling resumes after reload for free and returns two coins plus one stamp exactly once after three actual rolls');await p.screenshot({path:out+'/bowling-result.png'});
 await open('photo','photo');await p.locator('[data-action="save-photo"]').click();await p.waitForFunction(()=>__WORLD_TEST__.service.value.photos.length===1);await p.locator('[data-action="album"]').click();assert.equal(await p.locator('.photo-grid img').count(),1);check('Free fitted photo preview saves to the existing local album');await close();
 // The user marked these two rows and the ticket diamond in the actual restaurant iframe.
 for(const [width,height]of[[852,393],[568,320]]){
  await p.setViewportSize({width,height});await p.evaluate(()=>{const w=__WORLD_TEST__;w.navigate('village');const d=w.doors.find(d=>d.id==='cafe');w.place(d.x,d.y+45);w.enter();});await p.waitForFunction(()=>__WORLD_TEST__.snapshot().frames.find(f=>f.id==='cafe')?.ready);const f=p.frames().find(f=>f.url().includes('/game/build/'));
  await f.evaluate(()=>{__RR_TEST__.openRestaurant();const s=__RR_TEST__.snapshot();s.customers=[{id:177,table:0,dish:'pizza',variant:'tomato',type:'pink',phase:'ordered',x:RR.TABLES[0].seat.x,y:RR.TABLES[0].seat.y,eat:0}];s.issued=1;s.nextId=178;s.active=177;__RR_TEST__.loadFixture(s);__RR_TEST__.openRecipeMenu();});
  const toolbar=await f.evaluate(()=>{const el=document.querySelector('.kitchen-header'),header=el.getBoundingClientRect(),b=el.querySelector('button').getBoundingClientRect(),im=el.querySelector('button svg').getBoundingClientRect(),ticket=document.querySelector('.kitchen-screen>.ticket'),r=ticket.getBoundingClientRect(),s=getComputedStyle(ticket,'::after'),children=[...ticket.children].map(n=>n.getBoundingClientRect().bottom);return{top:b.y-header.y,bottom:header.bottom-b.bottom,left:b.x-header.x,pad:Math.min(im.x-b.x,im.y-b.y,b.right-im.right,b.bottom-im.bottom),diamondTop:r.bottom-parseFloat(s.bottom)-parseFloat(s.height)-(parseFloat(s.height)*(Math.SQRT2-1)/2),lastPictureBottom:Math.max(...children)};});
  assert.ok(toolbar.top>=5&&toolbar.bottom>=5&&toolbar.left>=10&&toolbar.pad>=5,JSON.stringify(toolbar));assert.ok(toolbar.diamondTop>toolbar.lastPictureBottom+6,JSON.stringify(toolbar));await p.screenshot({path:out+`/restaurant-toolbar-ticket-${width}x${height}.png`});
  await p.locator('#return').click();await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);check('Restaurant second toolbar has padding and its diamond stays below all order pictures at '+width+'x'+height);
 }
 const gallery=await p.evaluate(()=>{const cv=document.createElement('canvas');cv.width=1500;cv.height=1050;const c=cv.getContext('2d');c.fillStyle='#8b73a0';c.fillRect(0,0,cv.width,cv.height);const outfits=[{head:'bow',body:'tee',accessory:'beads'},{head:'sunhat',body:'star-jacket',accessory:'satchel'},{head:'flower-crown',body:'rainbow-dress',accessory:'glasses'},{head:'helmet',body:'raincoat',accessory:'scarf'},{head:'prize-star-bow',body:'prize-rainbow-cape',accessory:'prize-moon-bag'},{head:'legacy-princess',body:'legacy-hero',accessory:'legacy-mask'}];outfits.forEach((outfit,row)=>UWArtSprites.frames.forEach((key,col)=>UWArt.unicorn(c,65+col*135,165+row*147,120,outfit,key,col%2===1)));for(const [n,id]of['bike','skateboard'].entries())for(let frame=0;frame<4;frame++)UWArt.unicorn(c,130+(frame+n*4)*170,1030,100,outfits[n],id+frame,false,id);return cv.toDataURL();});fs.writeFileSync(out+'/all-clothing-and-riding-poses.png',Buffer.from(gallery.split(',')[1],'base64'));check('Appearance review sheet captures all six body pieces in every original pose and both four-frame rides');
 const controls=await p.evaluate(()=>{const cv=document.createElement('canvas');cv.width=720;cv.height=720;const c=cv.getContext('2d');c.fillStyle='#f7ebd2';c.fillRect(0,0,720,720);Object.keys(UWArtSprites.icons).forEach((id,n)=>UWArt.picture(c,id,60+n%6*120,114+Math.floor(n/6)*120,94,94));return cv.toDataURL();});fs.writeFileSync(out+'/generated-controls.png',Buffer.from(controls.split(',')[1],'base64'));
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);check('No page exceptions or missing sprite requests');fs.writeFileSync(out+'/QA-RESULTS.json',JSON.stringify({results,errors,failed,physicalDevice:false,childReview:false},null,2));console.log('Evidence:',out);
}finally{await browser.close();}})().catch(e=>{console.error(e);fs.writeFileSync(out+'/QA-FAILURE.txt',e.stack);process.exit(1);});
