/* Behaviour checks: prices, ownership, skill rewards and resumable paid sessions. */
const assert=require('node:assert/strict'),C=require('../../shared/catalogue.js'),{fresh,apply}=require('../../shared/profile.js');
let count=0;function check(name,fn){fn();count++;console.log('PASS',name);}
check('Catalogue: 48 unique puzzles, three free pieces, nine shop wearables, six prizes',()=>{assert.equal(C.puzzles.length,48);assert.equal(new Set(C.puzzles.map(p=>p.id)).size,48);assert.equal(C.starters.length,3);assert.equal(C.items.filter(i=>C.slots.includes(i.slot)&&i.price>0).length,9);assert.equal(C.prizes.length,6);});
check('Purchase is permanent, re-buy costs nothing, unaffordable purchase cannot alter state',()=>{const p=fresh();p.coins=3;apply(p,'buy',{item:'flower-crown'});assert.equal(p.coins,0);assert.ok(p.owned.includes('flower-crown'));apply(p,'buy',{item:'flower-crown'});assert.equal(p.coins,0);const before=JSON.stringify(p);assert.throws(()=>apply(p,'buy',{item:'bike'}),/coins/);assert.equal(JSON.stringify(p),before);});
check('Only owned outfit pieces can be equipped or saved',()=>{const p=fresh();assert.throws(()=>apply(p,'equip',{item:'sunhat'}),/owned/);assert.throws(()=>apply(p,'outfit',{outfit:{head:'sunhat'}}),/owned/);apply(p,'save-outfit',{slot:2});apply(p,'equip',{item:null,slot:'head'});apply(p,'wear-outfit',{slot:2});assert.equal(p.outfit.head,'bow');});
check('Legacy costumes respect secret counts and stay owned',()=>{const p=fresh();apply(p,'earn',{game:'adventure',event:{id:'a',kind:'costumes',secrets:1}});assert.ok(p.owned.includes('legacy-princess'));assert.ok(p.owned.includes('legacy-hero'));assert.ok(!p.owned.includes('legacy-chef'));apply(p,'earn',{game:'adventure',event:{id:'b',kind:'costumes',secrets:3}});apply(p,'earn',{game:'adventure',event:{id:'c',kind:'costumes',secrets:0}});assert.ok(p.owned.includes('legacy-chef')&&p.owned.includes('legacy-space'));});
check('Paid jigsaw resumes for free, saves each difficulty, and refunds once on completion',()=>{const p=fresh();p.coins=10;const a=apply(p,'start',{game:'jigsaw',puzzle:'animals-2',pieces:4}).session;apply(p,'progress',{session:a.id,state:{placed:[0,1],guide:true}});const b=apply(p,'start',{game:'jigsaw',puzzle:'animals-2',pieces:4});assert.equal(b.resumed,true);assert.equal(b.session.id,a.id);assert.equal(p.coins,9);assert.throws(()=>apply(p,'finish',{session:a.id}),/unfinished/);apply(p,'finish',{session:a.id,state:{placed:[0,1,2,3]}});assert.equal(p.coins,10);assert.equal(p.stamps,1);apply(p,'finish',{session:a.id});assert.equal(p.coins,10);assert.equal(p.stamps,1);const replay=apply(p,'start',{game:'jigsaw',puzzle:'animals-2',pieces:4});assert.notEqual(replay.session.id,a.id);apply(p,'start',{game:'jigsaw',puzzle:'animals-2',pieces:9});assert.equal(p.coins,8);});
check('All skill reward thresholds and five-stamp prize',()=>{for(const[game,score,reward]of[['catcher',7,0],['catcher',8,1],['catcher',15,2],['bowling',9,0],['bowling',10,1],['bowling',20,2]]){const p=fresh();p.coins=1;const s=apply(p,'start',{game}).session;const state=game==='catcher'?{elapsed:30,basket:.5,caught:Array.from({length:score},(_,i)=>i)}:{throws:3,score,aim:0};const v=apply(p,'finish',{session:s.id,state});assert.equal(v.amount,reward);}const p=fresh();p.coins=5;for(let i=0;i<5;i++){const s=apply(p,'start',{game:'bowling'}).session;apply(p,'finish',{session:s.id,state:{throws:3,score:0,aim:0}});}assert.ok(p.owned.includes(C.prizes[0]));assert.equal(p.stamps,0);assert.equal(p.prize,C.prizes[1]);});
console.log(count+' profile behaviour checks passed');
