const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const out=process.env.WORLD_QA_OUTPUT||'/tmp/unicorn-world-qa',results=[],errors=[],failed=[];
fs.mkdirSync(out,{recursive:true});
const check=(name,details)=>{results.push({name,pass:true,details});console.log('PASS',name)};
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});const c=await b.newContext({viewport:{width:844,height:390},hasTouch:true});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push({url:r.url(),status:r.status()})});
const state=()=>p.evaluate(()=>__WORLD_TEST__.snapshot());
const returnHub=async()=>{await p.locator('#return').click();await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().active)};
const enter=async(id)=>{await p.evaluate(id=>{const d=__WORLD_TEST__.doors.find(d=>d.id===id);__WORLD_TEST__.place(d.x,d.y+45)},id);await p.locator('#enter').click();await p.waitForFunction(id=>__WORLD_TEST__.snapshot().frames.find(f=>f.id===id)?.ready,id);return p.frames().find(f=>f.url().includes(id==='cafe'?'/game/build/':'/adventure/'))};
await p.goto('http://localhost:8890/hub/?qa=1');await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);assert.equal((await state()).frames.length,0);check('Fresh start loads world and only needed games');
await p.locator('#scene').focus();await p.keyboard.down('ArrowLeft');await p.waitForTimeout(460);await p.keyboard.up('ArrowLeft');await p.keyboard.down('ArrowUp');await p.waitForTimeout(470);await p.keyboard.up('ArrowUp');await p.keyboard.down('ArrowLeft');await p.waitForTimeout(475);await p.keyboard.up('ArrowLeft');assert.equal((await state()).focused,'cafe');check('Actual keyboard walk reaches café, without accidental entry');await p.screenshot({path:out+'/hub-cafe-door.png'});
await p.locator('#enter').click();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().frames[0]?.ready);let cafe=p.frames().find(f=>f.url().includes('/game/build/'));await cafe.getByRole('button',{name:'Choose flooring mint',exact:true}).click();await cafe.getByRole('button',{name:'Open the restaurant',exact:true}).click();await cafe.waitForFunction(()=>__RR_TEST__.mode==='world');check('Fresh hub → actual café designer → open restaurant');
await cafe.evaluate(()=>{const s=RR.fresh();s.decor.flooring='mint';s.customers=[{id:1,table:0,dish:'pizza',variant:'tomato',type:'pink',phase:'ordered',x:RR.TABLES[0].seat.x,y:RR.TABLES[0].seat.y,eat:0}];s.issued=1;s.nextId=2;s.active=1;s.prep={orderId:1,dish:'pizza',step:0,p:1,variant:'tomato',done:false,placements:[]};__RR_TEST__.loadFixture(s);__RR_TEST__.openCooking();});
let before=await cafe.evaluate(()=>({snapshot:__RR_TEST__.snapshot(),mode:__RR_TEST__.mode}));await p.screenshot({path:out+'/cafe-playing.png'});await returnHub();let paused=await cafe.evaluate(()=>__RR_TEST__.snapshot());await p.waitForTimeout(500);assert.deepEqual(await cafe.evaluate(()=>__RR_TEST__.snapshot()),paused);check('Café saves before return; hidden game simulation pauses');cafe=await enter('cafe');assert.equal(await cafe.evaluate(()=>__RR_TEST__.mode),before.mode);assert.deepEqual(await cafe.evaluate(()=>__RR_TEST__.snapshot().prep),before.snapshot.prep);check('Café reentry resumes same unfinished cooking session');await returnHub();
let adventure=await enter('adventure');await adventure.getByRole('button',{name:'Play Big Cozy House',exact:true}).click();await adventure.waitForFunction(()=>SneakyUnicorn.snapshot().mode==='play');await adventure.evaluate(()=>{const ns=__qa.nodes(false),set=new Set(ns.map(p=>p.x+':'+p.y));const p=ns.find(p=>p.x>1000&&p.y>500&&p.y<900&&set.has((p.x-96)+':'+p.y));__qa.place(p.x,p.y);__qa.manual(false);});let a0=await adventure.evaluate(()=>SneakyUnicorn.snapshot());await adventure.locator('#game').click({position:{x:100,y:100}});await adventure.page().keyboard.down('ArrowLeft');await p.waitForTimeout(320);await p.keyboard.up('ArrowLeft');let a1=await adventure.evaluate(()=>SneakyUnicorn.snapshot());console.log('Adventure move evidence',a0.mode,a0.player,a1.mode,a1.player);assert.ok(Math.abs(a1.player.x-a0.player.x)>5);await adventure.getByRole('button',{name:/Mute sound/}).count().then(()=>{});await p.screenshot({path:out+'/adventure-playing.png'});check('Home enters actual adventure; actual keyboard moves unicorn');
await returnHub();let ap=await adventure.evaluate(()=>SneakyUnicorn.snapshot());await p.waitForTimeout(500);assert.deepEqual((await adventure.evaluate(()=>SneakyUnicorn.snapshot())).player,ap.player);adventure=await enter('adventure');let ar=await adventure.evaluate(()=>SneakyUnicorn.snapshot());assert.deepEqual(ar.player,ap.player);assert.equal(ar.mode,ap.mode);check('Adventure return/reentry preserves in-flight player, mode and progress');
// Completion fixture uses the game's real earned-progress/save path in isolated storage.
await adventure.evaluate(()=>{__qa.setup({game:{goalReady:true,catches:1}});__qa.finish();});await returnHub();const savedCafe=await cafe.evaluate(()=>localStorage.getItem(RR.SAVE_KEY));const savedAdventure=await adventure.evaluate(()=>localStorage.getItem('sneaky-unicorn-midnight-v15'));await p.reload();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);cafe=await enter('cafe');assert.equal(await cafe.evaluate(()=>localStorage.getItem(RR.SAVE_KEY)),savedCafe);assert.deepEqual(await cafe.evaluate(()=>__RR_TEST__.snapshot().prep),before.snapshot.prep);await returnHub();adventure=await enter('adventure');assert.equal(await adventure.evaluate(()=>localStorage.getItem('sneaky-unicorn-midnight-v15')),savedAdventure);assert.equal(await adventure.evaluate(()=>SneakyUnicorn.snapshot().best.easy_house),2);await returnHub();check('Reload retains native café partial recipe and adventure earned progress');
// Touch pointer drag at the same invisible joystick ratio as café, including cancellation.
await p.evaluate(()=>__WORLD_TEST__.place(1050,620));let beforeDrag=(await state()).player;const touch=await c.newCDPSession(p);await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:520,y:250}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:560,y:250}]});await p.waitForTimeout(250);await touch.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});let cancelled=await state();assert.ok(cancelled.player.x>beforeDrag.x+10);assert.equal(cancelled.drag,false);assert.equal(cancelled.target,null);await p.waitForTimeout(180);assert.deepEqual((await state()).player,cancelled.player);check('Touch joystick movement and pointer-cancel stop without stray target');
await p.evaluate(()=>__WORLD_TEST__.place(900,500));await p.locator('#scene').focus();await p.keyboard.down('ArrowUp');await p.waitForTimeout(650);await p.keyboard.up('ArrowUp');assert.ok((await state()).player.y>=395);check('Expansion path requires explicit doorway action');
await p.evaluate(()=>__WORLD_TEST__.place(550,530));await p.evaluate(()=>{document.getElementById('enter').click();document.getElementById('enter').click();document.getElementById('enter').click()});await p.waitForTimeout(150);assert.equal((await state()).active,'cafe');assert.equal((await state()).frames.length,2);await returnHub();assert.equal((await state()).active,null);assert.equal((await state()).focused,undefined);check('Rapid enter taps create no duplicate games; return spawn avoids entry loop');
// Portrait gate clears input and prevents entry, then landscape recovers.
await p.setViewportSize({width:390,height:844});await p.waitForFunction(()=>__WORLD_TEST__.snapshot().portrait);assert.equal((await state()).portrait,true);assert.equal(await p.locator('#rotate').isVisible(),true);await p.setViewportSize({width:568,height:320});await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().portrait);assert.equal((await state()).portrait,false);check('Portrait picture gate and narrow landscape recovery');
for(const [w,h]of[[568,320],[667,375],[740,300],[844,390],[932,430],[1280,720]]){await p.setViewportSize({width:w,height:h});await p.evaluate(()=>__WORLD_TEST__.place(1050,600));await p.waitForTimeout(60);let r=await p.locator('#enter').boundingBox();assert.ok(r.width>=44&&r.x>=0&&r.y>=0&&r.x+r.width<=w&&r.y+r.height<=h);await p.screenshot({path:out+`/hub-${w}x${h}.png`});}check('Six landscape layouts retain visible 44px+ context button');
await p.setViewportSize({width:844,height:390});await p.locator('#scene').focus();await p.keyboard.down('ArrowRight');const second=await c.newPage();await second.goto('about:blank');await second.bringToFront();await p.waitForTimeout(120);await p.bringToFront();await p.keyboard.up('ArrowRight');assert.equal((await state()).keys,0);check('Background/foreground clears held controls');await second.close();
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);check('All requested assets load; no browser errors or HTTP failures');
// Standalone entry remains launchable and bridge dormant.
for(const path of ['/game/build/?qa=1','/adventure/?qa=1']){const q=await c.newPage();await q.goto('http://localhost:8890'+path);await q.waitForFunction(()=>!!(window.__RR_TEST__||window.__qa));check('Independent launch '+path);await q.close();}
fs.writeFileSync(out+'/QA-RESULTS.json',JSON.stringify({results,errors,failed,physicalPhoneTest:false,childTest:false},null,2));await c.close();await b.close();})().catch(e=>{console.error(e);fs.writeFileSync(out+'/QA-FAILURE.txt',e.stack);process.exit(1)});
