const {chromium}=require('/Users/deanguedo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{const p=await b.newPage({viewport:{width:852,height:393}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.WORLD_QA_URL||'http://localhost:8890/hub/')+'?qa=1');await p.waitForFunction(()=>window.__WORLD_TEST__?.snapshot().loaded);
await p.evaluate(()=>{const w=__WORLD_TEST__;const d=w.doors.find(d=>d.id==='mall');w.place(d.x,d.y+45);w.enter()});assert.equal(await p.evaluate(()=>__WORLD_TEST__.snapshot().scene),'mall');
await p.evaluate(()=>{const w=__WORLD_TEST__;w.navigate('boutique');const d=w.doors.find(d=>d.id==='closet');w.place(d.x,d.y+45);w.enter()});await p.waitForSelector('#outfit-preview');assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.kind),'closet');
await p.locator('[data-action="try"][data-item="bow"]').click();await p.waitForFunction(()=>__WORLD_TEST__.service.value.outfit.head==='bow');assert.equal(await p.locator('[data-action="wish"]').count(),0);await p.locator('[data-action="try"][data-item="flower-crown"]').click();assert.equal(await p.evaluate(()=>__WORLD_TEST__.service.value.outfit.head),'bow');await p.locator('#panel-close').click();assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.previewOutfit),null);
await p.locator('#backpack').click();assert.equal(await p.locator('.panel-tabs').count(),1);await p.locator('[data-action="remove"]').click();await p.waitForFunction(()=>__WORLD_TEST__.service.value.outfit.head===null);await p.locator('[data-action="wear"][data-item="bow"]').click();await p.waitForFunction(()=>__WORLD_TEST__.service.value.outfit.head==='bow');await p.locator('[data-action="bag-tab"][data-slot="accessory"]').click();await p.locator('[data-action="wear"][data-item="beads"]').click();await p.waitForFunction(()=>__WORLD_TEST__.service.value.outfit.accessory==='beads');
for(const size of [{width:852,height:393},{width:568,height:320}]){await p.setViewportSize(size);assert.equal(await p.locator('.panel-tabs').count(),1);assert.ok(await p.locator('.panel-tabs button').evaluateAll(bs=>bs.every(b=>{const r=b.getBoundingClientRect();return r.width>=44&&r.height>=44&&r.right<=innerWidth&&r.bottom<=innerHeight})));await p.screenshot({path:'/tmp/quick-switch-'+size.width+'.png'});}
await p.locator('#panel-close').click();await p.evaluate(()=>{const w=__WORLD_TEST__;w.navigate('mall');const d=w.doors.find(d=>d.id==='take-photo');w.place(d.x,d.y+45);w.enter()});await p.waitForSelector('.photo-preview');assert.equal(await p.evaluate(()=>__WORLD_TEST__.snapshot().scene),'mall');await p.locator('[data-action="save-photo"]').click();await p.waitForFunction(()=>__WORLD_TEST__.service.value.photos.length===1);await p.locator('#panel-close').click();await p.reload();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);assert.equal(await p.evaluate(()=>__WORLD_TEST__.service.value.outfit.head),'bow');assert.equal(await p.evaluate(()=>__WORLD_TEST__.service.value.photos.length),1);assert.deepEqual(errors,[]);console.log('PASS direct mall, mirror and photo entry; one-tap owned clothes, free previews, removal, single-row mobile backpack, reload and photo retention');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
