/* Real isolated browser proof for project-subpath hosting and old café replacement. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/deanguedo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const repo=path.resolve(__dirname,'../..'),out=process.env.WORLD_RELEASE_OUTPUT||path.join(__dirname,'release-evidence');fs.mkdirSync(out,{recursive:true});
const results=[],errors=[],missing=[];const check=(name,details)=>{results.push({name,pass:true,details});console.log('PASS',name);};
(async()=>{
 let server,folder=path.join(repo,'game/pages'),base=process.env.WORLD_RELEASE_URL;
 if(!base){
  const mime={'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png','.webp':'image/webp'};
  server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),prefix='/unicorn-cafe/';if(!u.pathname.startsWith(prefix)){res.writeHead(404);return res.end();}let relative=decodeURIComponent(u.pathname.slice(prefix.length));if(!relative||relative.endsWith('/'))relative+='index.html';const file=path.resolve(folder,relative);if(!file.startsWith(folder+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res);});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port+'/unicorn-cafe/';
 }
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 async function context(){const c=await browser.newContext({viewport:{width:852,height:393},hasTouch:true});c.on('page',p=>{p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)missing.push({url:r.url(),status:r.status()});});});return c;}
 async function world(p){await p.waitForFunction(()=>window.__WORLD_TEST__?.snapshot().loaded,null,{timeout:90000});assert.ok(p.url().includes('/unicorn-cafe/hub/'));}
 async function enter(p,id){await p.evaluate(id=>{const w=__WORLD_TEST__;w.navigate('village');const d=w.doors.find(d=>d.id===id);w.place(d.x,d.y+55);w.enter();},id);await p.waitForFunction(id=>__WORLD_TEST__.snapshot().frames.find(f=>f.id===id)?.ready,id,{timeout:90000});return p.frames().find(f=>f.url().includes(id==='cafe'?'/game/build/':'/adventure/'));}
 async function leave(p){await p.locator('#return').click();await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);}
 try{
  const c=await context(),p=await c.newPage();await p.goto(base+'?qa=1');await world(p);assert.equal(await p.title(),'Unicorn World');await p.screenshot({path:out+'/world-entry.png'});check('The existing project root opens the connected Unicorn World in landscape');
  let cafe=await enter(p,'cafe');assert.ok(await cafe.evaluate(()=>!!__RR_TEST__.bridge?.profile));assert.equal(new URL(cafe.url()).searchParams.get('worldBase'),base);
  await cafe.evaluate(()=>{__RR_TEST__.openRestaurant();const s=__RR_TEST__.snapshot();s.customers=[{id:777,table:0,dish:'pizza',variant:'tomato',type:'pink',phase:'paying',x:RR.CASHIER.x,y:RR.CASHIER.y,eat:1.2}];s.issued=1;s.nextId=778;__RR_TEST__.loadFixture(s);__RR_TEST__.tickRestaurant(.05);});await p.waitForFunction(()=>__WORLD_TEST__.service.value.coins===1);await leave(p);
  const adventure=await enter(p,'adventure');assert.ok(await adventure.evaluate(()=>worldReady&&worldLink?.profile));assert.equal(new URL(adventure.url()).searchParams.get('worldBase'),base);
  await adventure.evaluate(()=>{__qa.start(0);__qa.manual(false);__qa.setup({game:{entryGrace:100}});const nodes=__qa.nodes(false),keys=new Set(nodes.map(p=>p.x+':'+p.y));const floor=nodes.find(p=>p.x>1000&&p.y>500&&p.y<900&&keys.has((p.x-96)+':'+p.y));if(floor)__qa.place(floor.x,floor.y);});await adventure.waitForFunction(()=>!SneakyUnicorn.snapshot().hubPaused);const before=await adventure.evaluate(()=>SneakyUnicorn.snapshot().player);await adventure.locator('#game').focus();await p.keyboard.down('ArrowLeft');try{await adventure.waitForFunction(before=>{const p=SneakyUnicorn.snapshot().player;return Math.hypot(p.x-before.x,p.y-before.y)>5;},before,{timeout:5000});}finally{await p.keyboard.up('ArrowLeft');}const moved=await adventure.evaluate(()=>SneakyUnicorn.snapshot().player);assert.ok(Math.hypot(moved.x-before.x,moved.y-before.y)>5);
  await adventure.evaluate(()=>{__qa.manual(true);__qa.setup({game:{goalReady:true}});__qa.finish();});await p.waitForFunction(()=>__WORLD_TEST__.service.value.coins===4);await leave(p);
  await p.evaluate(async()=>{await __WORLD_TEST__.service.run('buy',{item:'flower-crown',equip:true});await __WORLD_TEST__.service.run('equip',{item:'beads'});__WORLD_TEST__.navigate('boutique');const d=__WORLD_TEST__.doors.find(d=>d.id==='shop');__WORLD_TEST__.place(d.x,d.y+55);__WORLD_TEST__.enter();});await p.waitForFunction(()=>__WORLD_TEST__.snapshot().panel);await p.screenshot({path:out+'/wardrobe-project-path.png'});await p.locator('#panel-close').click();
  cafe=await enter(p,'cafe');await cafe.waitForFunction(()=>__RR_TEST__.bridge.profile.outfit.head==='flower-crown');await cafe.evaluate(()=>__RR_TEST__.openRestaurant());await p.screenshot({path:out+'/cafe-project-path.png'});await leave(p);
  await enter(p,'adventure');await adventure.waitForFunction(()=>worldOutfit.head==='flower-crown');await p.screenshot({path:out+'/adventure-project-path.png'});await leave(p);await p.reload();await world(p);const profile=await p.evaluate(()=>__WORLD_TEST__.service.public());assert.equal(profile.coins,1);assert.ok(profile.owned.includes('flower-crown'));assert.equal(profile.outfit.head,'flower-crown');assert.equal(profile.outfit.accessory,'beads');
  check('Both games connect beneath the GitHub project path: real café earning, adventure movement/win hook, purchase/equip and reload retain coins and clothing');
  await p.setViewportSize({width:393,height:852});await p.locator('#rotate').waitFor({state:'visible'});await p.setViewportSize({width:568,height:320});await p.locator('#rotate').waitFor({state:'hidden'});await p.screenshot({path:out+'/world-small-landscape.png'});check('Published-layout portrait suspension returns to the same world on a small landscape screen');await c.close();
  if(server){
   folder=path.join(repo,'game/cafe-pages');const old=await context(),q=await old.newPage();await q.goto(base+'?qa=1');await q.waitForFunction(()=>window.__RR_TEST__?.mode==='customize');await q.waitForFunction(()=>__RR_TEST__.offlineReady);
   await q.evaluate(async()=>{const s=RR.fresh();s.coins=11;s.total=11;__RR_TEST__.loadFixture(s);__RR_TEST__.save();localStorage.setItem('world-release-survivor','keep');await caches.open('world-release-unrelated');});await q.reload();await q.waitForFunction(()=>window.__RR_TEST__?.offlineReady&&!!navigator.serviceWorker.controller);
   assert.equal(await q.evaluate(()=>__RR_TEST__.snapshot().coins),11);folder=path.join(repo,'game/pages');await q.evaluate(async()=>{const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.filter(r=>new URL(r.scope).pathname==='/unicorn-cafe/').map(r=>r.update()));});await q.waitForURL('**/hub/**',{timeout:90000});await world(q);
   assert.equal(await q.evaluate(()=>localStorage.getItem('world-release-survivor')),'keep');assert.ok(await q.evaluate(async()=>(await caches.keys()).includes('world-release-unrelated')));
   const cf=await enter(q,'cafe');await q.waitForFunction(()=>__WORLD_TEST__.service.value.coins===11);assert.equal(await cf.evaluate(()=>__RR_TEST__.snapshot().coins),11);await leave(q);await q.reload();await world(q);await enter(q,'cafe');await q.waitForTimeout(500);assert.equal(await q.evaluate(()=>__WORLD_TEST__.service.value.coins),11);await q.screenshot({path:out+'/old-cafe-save-retained.png'});
   check('A real cached café installation upgrades to the world, preserves its native coins and unrelated storage/cache, and imports the old balance once');await old.close();
  }
  assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);check('No browser exceptions or missing release resources',{errors,missing});
  fs.writeFileSync(out+'/QA-RESULTS.json',JSON.stringify({results,errors,missing,url:base,oldCafeUpgradeTested:!!server,physicalDevice:false,childReview:false},null,2)+'\n');
 }finally{await browser.close();if(server)await new Promise(resolve=>server.close(resolve));}
})().catch(e=>{console.error(e);fs.writeFileSync(out+'/QA-FAILURE.txt',e.stack);process.exitCode=1;});
