/* Isolated browser regression checks; never use the player's profile/storage. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.UNICORN_QA_URL||'http://127.0.0.1:8790';
const out=process.env.UNICORN_QA_OUTPUT||'/tmp/unicorn-picture-first-qa';
fs.mkdirSync(out,{recursive:true});const results=[],errors=[];
const check=(name,details)=>{results.push({name,pass:true,details});console.log('PASS',name)};
const watch=p=>p.on('pageerror',e=>errors.push(e.message));
const state=p=>p.evaluate(()=>SneakyUnicorn.snapshot());
const visibleText=(p,selector)=>p.locator(selector).evaluate(el=>{const copy=el.cloneNode(true);copy.querySelectorAll('.sr-only,#brand,#subline,#kicker,[hidden]').forEach(n=>n.remove());return copy.textContent.trim()});
async function targets(p,selector,w,h){
 const boxes=await p.locator(selector).evaluateAll(nodes=>nodes.filter(e=>e.getClientRects().length&&!e.closest('[hidden]')).map(e=>({label:e.getAttribute('aria-label'),...e.getBoundingClientRect().toJSON()})));
 for(const r of boxes){assert.ok(r.width>=44&&r.height>=44,JSON.stringify(r));assert.ok(r.x>=0&&r.y>=0&&r.right<=w+.1&&r.bottom<=h+.1,JSON.stringify(r));}
 return boxes;
}
(async()=>{
 const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--disable-gpu']});
 try{
 const c=await b.newContext({viewport:{width:844,height:390},hasTouch:true});const p=await c.newPage();watch(p);p.setDefaultTimeout(20000);
 await p.goto(base+'/adventure/?qa=1');await p.waitForFunction(()=>window.__qa);
 const ids=await p.locator('#levelCards button').evaluateAll(bs=>bs.map(b=>({id:+b.dataset.level,label:b.getAttribute('aria-label')})));assert.equal(ids.length,5);assert.equal(await p.locator('.theme-figure').evaluateAll(es=>es.every(e=>e.children.length===1&&getComputedStyle(e).backgroundColor==='rgba(0, 0, 0, 0)')),true);assert.deepEqual(await p.locator('.theme-figure').evaluateAll(es=>es.map(e=>e.dataset.theme)),['house','groceries','restaurant','toys','police']);assert.equal(await p.locator('.theme-figure img').evaluateAll(es=>es.every(e=>e.complete&&e.naturalWidth>0)),true);
 assert.equal(await visibleText(p,'#overlay'),'');assert.equal(await p.locator('#gameMenu').isVisible(),true);
 await p.screenshot({path:out+'/opening-844x390.png'});check('Five picture places with distinct theme pictures, no visible reading, persistent settings');
 // Seed a realistic native profile plus untouched legacy data, then reload.
 const seed=await p.evaluate(()=>{saved.best.easy_house=2;saved.stickers=['apple'];saved.babies=['easy_market:baby:0'];saved.costume='chef';save();localStorage.setItem('sneaky-unicorn-midnight-v13','{"legacy":"keep"}');return localStorage.getItem(PREF_KEY)});
 await p.reload();await p.waitForFunction(()=>window.__qa);assert.equal(await p.evaluate(()=>localStorage.getItem(PREF_KEY)),seed);assert.equal((await state(p)).best.easy_house,2);check('Existing native and legacy saves survive unchanged on launch');
 await p.locator('#gameMenu').focus();await p.keyboard.press('Enter');assert.equal((await state(p)).uiPaused,true);
 await p.waitForFunction(()=>[...document.querySelectorAll('.menu-art img,#gameMenu img')].every(e=>e.complete&&e.naturalWidth>0));await p.locator('#ui-help').click();await p.screenshot({path:out+'/picture-help.png'});await p.locator('#help-back').click();
 await p.locator('#sound').click();await p.locator('#motion').click();
 const prefs=await p.evaluate(()=>JSON.parse(localStorage.getItem(PREF_KEY)));assert.deepEqual(Object.keys(prefs).sort(),Object.keys(JSON.parse(seed)).sort());assert.equal(prefs.muted,true);assert.equal(prefs.reduced,true);
 assert.equal(await p.locator('.drag-demo svg').first().evaluate(e=>getComputedStyle(e).animationName),'none');assert.equal(await p.evaluate(()=>localStorage.getItem('sneaky-unicorn-midnight-v13')),'{"legacy":"keep"}');
 await p.screenshot({path:out+'/settings-844x390.png'});await p.keyboard.press('Escape');assert.equal((await state(p)).mode,'menu');check('Keyboard settings, picture help, saved sound/motion, static gentle guidance');
 // Every map is selected via its actual picture button.
 for(const item of ids){await p.getByRole('button',{name:item.label,exact:true}).click();assert.equal((await state(p)).mode,'play');assert.equal(await p.locator('#mission').innerText(),'');assert.equal(await p.locator('#blast').innerText(),'');await p.locator('#gameMenu').focus();await p.keyboard.press('Space');assert.equal((await state(p)).uiPaused,true);await p.locator('#ui-places').click();}
 check('All five actual place buttons, picture HUD/blast, keyboard gear while playing');
 await p.locator('[data-level="0"]').click();assert.equal(await p.locator('#movement-picture').isVisible(),true);
 await p.evaluate(()=>{__qa.input(-1,0);__qa.step(.25);__qa.release();});assert.equal(await p.locator('#movement-picture').isVisible(),false);assert.equal(await p.locator('#blast-picture').isVisible(),true);
 await p.locator('#blast').focus();await p.keyboard.press('Space');await p.evaluate(()=>__qa.step(.01));assert.equal((await state(p)).mastery.blast,true);assert.equal(await p.locator('#blast-picture').isVisible(),false);
 await p.screenshot({path:out+'/playing-844x390.png'});check('Movement and blast guidance disappear after real actions');
 // Exact native mode/timers survive the new settings suspension.
 for(const mode of ['play','reset','win','pause','menu']){
 await p.evaluate(mode=>{__qa.start(0);if(mode==='reset'){__qa.setup({game:{entryGrace:0}});__qa.catch(0);}else if(mode==='win'){__qa.setup({game:{goalReady:true}});__qa.finish();}else if(mode==='pause')__qa.pause();else if(mode==='menu')__qa.showMenu();},mode);
 const before=await state(p);await p.locator('#gameMenu').click();await p.evaluate(()=>__qa.step(.5));let frozen=await state(p);assert.equal(frozen.clock,before.clock);assert.equal(frozen.mode,before.mode);assert.equal(frozen.winTime,before.winTime);assert.equal(frozen.resetTime,before.resetTime);assert.deepEqual(frozen.player,before.player);
 await p.locator('#ui-resume').click();assert.equal((await state(p)).mode,before.mode);
 // Portrait blocks both real keyboard input and deterministic simulation.
 await p.setViewportSize({width:390,height:844});await p.waitForFunction(()=>SneakyUnicorn.snapshot().portraitBlocked);assert.equal(await p.locator('#rotate-screen').isVisible(),true);await p.waitForFunction(()=>['suspended','not-started'].includes(SneakyUnicorn.snapshot().audio),null,{timeout:2000}).catch(async e=>{console.log('Portrait audio evidence',mode,await state(p));throw e});
 const rotated=await state(p);await p.keyboard.press('ArrowLeft');await p.keyboard.press('Space');await p.evaluate(()=>__qa.step(.5));frozen=await state(p);assert.deepEqual(frozen.player,rotated.player);assert.equal(frozen.clock,rotated.clock);assert.equal(frozen.mode,mode);assert.equal(frozen.audio==='suspended'||frozen.audio==='not-started',true);
 await p.setViewportSize({width:844,height:390});await p.waitForFunction(()=>!SneakyUnicorn.snapshot().portraitBlocked);assert.equal((await state(p)).mode,mode);
 }
 check('Settings and portrait freeze/restore play, reset, win, pause, and selection');
 await p.evaluate(()=>__qa.start(0));await p.locator('#gameMenu').click();await p.locator('#ui-help').click();await p.setViewportSize({width:390,height:844});await p.waitForFunction(()=>SneakyUnicorn.snapshot().portraitBlocked);await p.setViewportSize({width:844,height:390});await p.waitForFunction(()=>!SneakyUnicorn.snapshot().portraitBlocked);assert.equal(await p.locator('#help-pictures').isVisible(),true);assert.equal((await state(p)).uiPaused,true);await p.keyboard.press('Escape');assert.equal(await p.locator('#settings-pictures').isVisible(),true);await p.keyboard.press('Escape');check('Rotation preserves open help/settings and their paused state');
 // Actual contact reset keeps carried treasure, then resumes normally.
 await p.evaluate(()=>{__qa.start(0);const it=SneakyUnicorn.snapshot().items[0];__qa.place(it.x,it.y);__qa.collect();__qa.setup({game:{entryGrace:0,hitStop:0}});__qa.catch(0);});const carried=(await state(p)).carry.entries;assert.equal(carried.length,1);await p.evaluate(()=>__qa.step(1.2));assert.equal((await state(p)).mode,'play');assert.deepEqual((await state(p)).carry.entries,carried);check('Contact reset retains native carried treasure');
 // Rescue both babies through the real portal/rescue flow; 1→2→3 capacity.
 const family=await p.evaluate(()=>{
 __qa.start(0);const caps=[__qa.carry().capacity];
 for(let i=0;i<2;i++){
  const level=__qa.level();__qa.setup({game:{roomCooldown:0,hitStop:0}});__qa.place(level.secretDoors[i].x,level.secretDoors[i].y);__qa.step(.025);
  if(!SneakyUnicorn.snapshot().inSecretRoom)throw Error('Door did not enter');
  const room=__qa.level().secretRooms[i];__qa.place(room.baby.x,room.baby.y);__qa.step(.025);caps.push(__qa.carry().capacity);
  __qa.setup({game:{roomCooldown:0,hitStop:0}});__qa.place(room.exit.x,room.exit.y);__qa.step(.025);
 }
 for(const it of SneakyUnicorn.snapshot().items.slice(0,3)){__qa.place(it.x,it.y);__qa.collect();}
 const carrying=__qa.carry();__qa.setup({game:{entryGrace:0,hitStop:0}});__qa.catch(0);__qa.step(1.2);
 const preserved=__qa.carry();const home=__qa.level().home;__qa.place(home.x,home.y);__qa.deposit();return {caps,carrying,preserved,after:__qa.carry(),delivered:SneakyUnicorn.snapshot().items.filter(it=>it.status==='delivered').length};
 });assert.deepEqual(family.caps,[1,2,3]);assert.equal(family.carrying.count,3);assert.deepEqual(family.preserved.entries.map(({id,kind,index})=>({id,kind,index})),family.carrying.entries.map(({id,kind,index})=>({id,kind,index})));assert.equal(family.after.count,0);assert.equal(family.delivered,3);assert.equal(await p.locator('.carry-picture').count(),3);check('Both real baby rescues, three carrying slots, contact preservation, bulk deposit',family.caps);
 const group=await p.evaluate(()=>{__qa.start(0);__qa.jail(0);const one=SneakyUnicorn.snapshot().enemies[0].state;for(let i=1;i<SneakyUnicorn.snapshot().enemies.length;i++)__qa.jail(i);const all=SneakyUnicorn.snapshot().enemies.every(e=>e.state==='JAILED');__qa.step(1.5);return{one,all,released:SneakyUnicorn.snapshot().enemies.every(e=>e.state!=='JAILED')}});assert.equal(group.one,'JAILED');assert.equal(group.all,true);assert.equal(group.released,true);
 const police=await p.evaluate(id=>{__qa.start(id);__qa.jail(0);__qa.step(3);return SneakyUnicorn.snapshot().enemies[0].state},ids[4].id);assert.equal(police,'JAILED');check('Regular opponents release together; police captures stay jailed');
 const aim=await p.evaluate(()=>{__qa.start(0);__qa.blast();const idle=SneakyUnicorn.snapshot().blasts;__qa.input(-1,0);__qa.step(.25);__qa.release();__qa.blast();return{idle,aim:SneakyUnicorn.snapshot().player.aim,vx:G.blasts[0]?.vx,vy:G.blasts[0]?.vy}});assert.equal(aim.idle,0);assert.ok(aim.vx<0);assert.equal(aim.vy,0);check('Rainbow blast preserves last real movement direction; idle has no fallback');
 // Real completion through pickups/deposits yields saved stars and picture choices.
 await p.evaluate(()=>{__qa.start(0);for(const it of [...SneakyUnicorn.snapshot().items]){__qa.place(it.x,it.y);__qa.collect();const home=__qa.level().home;__qa.place(home.x,home.y);__qa.deposit();}__qa.step(2)});
 assert.equal((await state(p)).mode,'win');assert.equal((await state(p)).resultShown,true);assert.equal(await visibleText(p,'#overlay'),'');await p.screenshot({path:out+'/celebration.png'});
 await p.getByRole('button',{name:'Again',exact:true}).click();assert.equal((await state(p)).mode,'play');await p.evaluate(()=>{__qa.setup({game:{goalReady:true}});__qa.finish();__qa.step(2)});await p.getByRole('button',{name:'Next place',exact:true}).click();assert.equal((await state(p)).level,'easy_market');
 await p.evaluate(()=>__qa.pause());await p.getByRole('button',{name:'Keep playing',exact:true}).click();assert.equal((await state(p)).mode,'play');check('Real collected completion, celebration, replay, next location, pause/resume');
 const layouts=[[1443,1338],[568,320],[667,375],[740,300],[844,390],[932,430],[1280,720],[568,271],[740,251]];
 for(const [w,h]of layouts){await p.setViewportSize({width:w,height:h});await p.evaluate(()=>__qa.showMenu());const boxes=await targets(p,'#levelCards button,#gameMenu',w,h);assert.equal(boxes.length,6);const tiles=await p.locator('#levelCards').boundingBox();assert.ok(tiles.width>=w-30&&tiles.y+tiles.height>=h-20,JSON.stringify(tiles));const cues=await p.locator('.theme-figure').evaluateAll(es=>es.map(e=>({cue:e.getBoundingClientRect().toJSON(),card:e.closest('.levelCard').getBoundingClientRect().toJSON(),footer:e.closest('.levelCard').querySelector('.cardFoot').getBoundingClientRect().toJSON()})));for(const {cue,card,footer}of cues){assert.ok(cue.width>=60&&cue.x>=card.x&&cue.right<=card.right+.1&&cue.y>=card.y&&cue.bottom<=footer.y+.1,JSON.stringify({cue,card,footer}));}assert.equal(new Set(boxes.filter(r=>r.label?.startsWith('Play ')).map(r=>r.y)).size,h<=540?1:2);await p.screenshot({path:out+`/opening-${w}x${h}.png`});await p.locator('#gameMenu').click();await targets(p,'.settings-grid button',w,h);await p.locator('#ui-help').click();await targets(p,'#help-back',w,h);const panel=await p.locator('.picture-panel').boundingBox();assert.ok(panel.y>=0&&panel.y+panel.height<=h+.1);await p.locator('#help-back').click();await p.locator('#ui-resume').click();await p.locator('[data-level="0"]').click();await targets(p,'#gameMenu,#blast',w,h);await p.evaluate(()=>{__qa.setup({game:{goalReady:true}});__qa.finish();__qa.step(2)});await targets(p,'#resultButtons button,#gameMenu',w,h);}
 check('Nine full-area layouts, including desktop and 251px iframe height; theme pictures clear and buttons at least 44px');
 await p.setViewportSize({width:740,height:300});await p.addStyleTag({content:':root{--qa-left:44px}#hud{left:44px;right:108px}#gameMenu{right:52px}#dock{right:54px;bottom:32px}#overlay{padding-left:44px;padding-right:44px;padding-bottom:20px}'});await p.evaluate(()=>__qa.showMenu());await targets(p,'#levelCards button,#gameMenu',740,300);check('Landscape notch and bottom inset spacing');
 // Actual live RAF continues after closing settings; freezes while open.
 await p.setViewportSize({width:844,height:390});await p.locator('[data-level="0"]').click();await p.evaluate(()=>__qa.manual(false));await p.waitForTimeout(120);const running=await state(p);await p.locator('#gameMenu').click();const paused=await state(p);await p.waitForTimeout(180);assert.equal((await state(p)).clock,paused.clock);await p.locator('#ui-resume').click();await p.waitForTimeout(120);assert.ok((await state(p)).clock>paused.clock);assert.ok(paused.clock>=running.clock);await p.evaluate(()=>__qa.manual(true));check('Real animation loop freezes and resumes with settings');
 // Real phone pointers retain invisible drag steering and cancel cleanly.
 await p.evaluate(()=>{__qa.start(0);__qa.manual(false)});const touch=await c.newCDPSession(p),touchBefore=await state(p);
 await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:250,y:180}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:210,y:180}]});await p.waitForTimeout(200);await touch.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await p.evaluate(()=>__qa.manual(true));
 const touchAfter=await state(p);assert.ok(touchAfter.player.x<touchBefore.player.x-10);assert.equal(await p.evaluate(()=>input.drag),null);
 const blastBox=await p.locator('#blast').boundingBox();await p.touchscreen.tap(blastBox.x+blastBox.width/2,blastBox.y+blastBox.height/2);assert.equal((await state(p)).mastery.blast,true);check('Real phone drag/cancel and rainbow-button touch');
 // Hub uses its genuine source/origin-checked pause/save bridge.
 const h=await c.newPage();watch(h);await h.goto(base+'/hub/?qa=1');await h.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);
 async function enter(){await h.evaluate(()=>{const d=__WORLD_TEST__.doors.find(d=>d.id==='adventure');__WORLD_TEST__.place(d.x,d.y+45)});await h.locator('#enter').click();await h.waitForFunction(()=>__WORLD_TEST__.snapshot().frames.find(f=>f.id==='adventure')?.ready);return h.frames().find(f=>f.url().includes('/adventure/'));}
 let a=await enter();await a.locator('[data-level="0"]').click();await a.evaluate(()=>{__qa.input(-1,0);__qa.step(.2);__qa.release()});const ah=await state(a);await h.screenshot({path:out+'/hub-playing-844x390.png'});await h.locator('#return').click();await h.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);assert.equal((await state(a)).hubPaused,true);await a.evaluate(()=>__qa.step(.5));assert.deepEqual((await state(a)).player,ah.player);a=await enter();assert.deepEqual((await state(a)).player,ah.player);assert.equal((await state(a)).mode,ah.mode);await targets(h,'#return',844,390);await a.locator('#gameMenu').click();await a.locator('#ui-help').click();await h.locator('#return').click();await h.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);a=await enter();assert.equal(await a.locator('#help-pictures').isVisible(),true);assert.equal((await state(a)).uiPaused,true);await a.locator('#help-back').click();await a.locator('#ui-resume').click();
 await h.setViewportSize({width:390,height:844});await h.waitForFunction(()=>__WORLD_TEST__.snapshot().portrait);assert.equal((await state(a)).hubPaused,true);await h.setViewportSize({width:568,height:320});await h.waitForFunction(()=>!__WORLD_TEST__.snapshot().portrait);await h.waitForTimeout(80);await targets(h,'#return',568,320);await targets(a,'#gameMenu,#blast',568,271);await h.screenshot({path:out+'/hub-playing-568x320.png'});check('Hub return/reentry, retained help, portrait suspension, 44px home button');
 await h.locator('#return').click();await h.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);await h.evaluate(()=>{const d=__WORLD_TEST__.doors.find(d=>d.id==='cafe');__WORLD_TEST__.place(d.x,d.y+45)});await h.locator('#enter').click();await h.waitForFunction(()=>__WORLD_TEST__.snapshot().frames.find(f=>f.id==='cafe')?.ready);const cafe=h.frames().find(f=>f.url().includes('/game/build/'));await cafe.getByRole('button',{name:'Open the restaurant',exact:true}).click();await cafe.waitForFunction(()=>__RR_TEST__.mode==='world');await targets(cafe,'#menu,#primary',568,271);await h.screenshot({path:out+'/hub-cafe-568x320.png'});await h.locator('#return').click();await h.waitForFunction(()=>!__WORLD_TEST__.snapshot().active);check('Existing cafe still fits 568x320 hub layout and returns normally');

 // Unsupported orientation lock must never prevent use.
 const lock=await c.newPage();watch(lock);await lock.addInitScript(()=>{try{Object.defineProperty(screen.orientation,'lock',{value:()=>Promise.reject(new Error('Unsupported'))})}catch(_){}});await lock.goto(base+'/adventure/?qa=1');await lock.waitForFunction(()=>window.__qa);await lock.locator('[data-level="0"]').click();assert.equal((await state(lock)).mode,'play');await lock.close();check('Rejected orientation lock leaves landscape play usable');
 // Artwork failure uses wordless retry (isolate and block workers).
 const failContext=await b.newContext({viewport:{width:844,height:390},serviceWorkers:'block'});await failContext.addInitScript(()=>{const desc=Object.getOwnPropertyDescriptor(HTMLImageElement.prototype,'src');Object.defineProperty(HTMLImageElement.prototype,'src',{get:desc.get,set(value){if(value.startsWith('data:image'))queueMicrotask(()=>this.onerror?.(new Event('error')));else desc.set.call(this,value)}})});
 const f=await failContext.newPage();watch(f);await f.goto(base+'/adventure/');await f.getByRole('button',{name:'Try loading the artwork again'}).waitFor();assert.equal(await visibleText(f,'#status'),'');await f.screenshot({path:out+'/artwork-retry.png'});await failContext.close();check('Artwork failure presents a picture retry control');
 // Same scoped worker serves updated picture UI on standalone offline reload.
 const oc=await b.newContext({viewport:{width:844,height:390}}),op=await oc.newPage();watch(op);await op.goto(base+'/adventure/?qa=1');await op.waitForFunction(()=>window.__qa);await op.evaluate(async()=>{const reg=await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(r=>navigator.serviceWorker.addEventListener('controllerchange',r,{once:true}));await new Promise((resolve,reject)=>{const channel=new MessageChannel();channel.port1.onmessage=e=>e.data.cached&&e.data.version==='15.0.0-pictures-3'?resolve():reject(Error('Wrong worker'));reg.active.postMessage({type:'APP_STATUS'},[channel.port2]);})});await oc.setOffline(true);await op.reload();await op.waitForFunction(()=>window.__qa);assert.equal(await op.locator('#levelCards button').count(),5);await op.locator('[data-level="0"]').click();assert.equal((await state(op)).mode,'play');check('Standalone offline reload serves all picture assets from updated scoped cache');
 await op.evaluate(async()=>{for(const key of await caches.keys()){const cache=await caches.open(key);for(const request of await cache.keys())await cache.delete(request)}});await op.goto(base+'/adventure/offline-check');await op.getByRole('button',{name:'Reconnect to load the game, then try again'}).waitFor();assert.equal(await op.locator('body').innerText(),'');await oc.close();check('Missing offline copy also shows a wordless retry');
 assert.deepEqual(errors,[]);check('No browser JavaScript errors across tested flows');
 fs.rmSync(path.join(out,'QA-FAILURE.txt'),{force:true});
 fs.writeFileSync(path.join(out,'QA-RESULTS.json'),JSON.stringify({results,errors,physicalPhoneTest:false,childTest:false},null,2));await c.close();
 }finally{await b.close()}
})().catch(e=>{console.error(e);fs.writeFileSync(path.join(out,'QA-FAILURE.txt'),e.stack);process.exit(1)});
