/* Frozen v1 cut contract: FNV-1a seed, xorshift32 signs, shared cubic edges. */
(function(root){'use strict';const cache=new Map();
function hash(text){let n=2166136261;for(let i=0;i<text.length;i++){n^=text.charCodeAt(i);n=Math.imul(n,16777619);}return n>>>0;}
function make(id,count,width,height,version=1){const key=[id,count,width,height,version].join('|');if(cache.has(key))return cache.get(key);const n=Math.sqrt(count);if(![2,3,4].includes(n)||version!==1)throw Error('Unsupported cut');let seed=hash(`uw-jigsaw-v1|${id}|${count}`)||1;const random=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296;},cw=width/n,ch=height/n,depth=Math.min(cw,ch)*.15,edges=[],h=[],v=[];
function edge(x,y,dx,dy,flat){const sign=random()<.5?-1:1,length=Math.hypot(dx,dy),nx=-dy/length*depth*sign,ny=dx/length*depth*sign,p=(t,l=0)=>[x+dx*t+nx*l,y+dy*t+ny*l];const e={start:p(0),segments:flat?[{type:'L',end:p(1)}]:[{type:'L',end:p(.32)},{type:'C',c1:p(.42),c2:p(.40,.15),end:p(.40,.45)},{type:'C',c1:p(.40,1.18),c2:p(.60,1.18),end:p(.60,.45)},{type:'C',c1:p(.60,.15),c2:p(.58),end:p(.68)},{type:'L',end:p(1)}],flat};edges.push(e);return e;}
for(let row=0;row<=n;row++){h[row]=[];for(let col=0;col<n;col++)h[row][col]=edge(col*cw,row*ch,cw,0,row===0||row===n);}
for(let row=0;row<n;row++){v[row]=[];for(let col=0;col<=n;col++)v[row][col]=edge(col*cw,row*ch,0,ch,col===0||col===n);}
function commands(e,reverse){let start=e.start,segments=e.segments;if(!reverse)return{start,segments};const ends=[e.start,...segments.map(s=>s.end)];return{start:ends.at(-1),segments:segments.map((s,i)=>s.type==='C'?{type:'C',c1:s.c2,c2:s.c1,end:ends[i]}:{type:'L',end:ends[i]}).reverse()};}
function trace(path,cmd,ox=0,oy=0,move=true){if(move)path.moveTo(cmd.start[0]-ox,cmd.start[1]-oy);for(const s of cmd.segments)if(s.type==='C')path.bezierCurveTo(s.c1[0]-ox,s.c1[1]-oy,s.c2[0]-ox,s.c2[1]-oy,s.end[0]-ox,s.end[1]-oy);else path.lineTo(s.end[0]-ox,s.end[1]-oy);}
const pieces=Array.from({length:count},(_,i)=>{const row=Math.floor(i/n),col=i%n,origin={x:col*cw,y:row*ch},refs=[[h[row][col],false],[v[row][col+1],false],[h[row+1][col],true],[v[row][col],true]],cmds=refs.map(([e,r])=>commands(e,r)),points=cmds.flatMap(c=>[c.start,...c.segments.flatMap(s=>s.type==='C'?[s.c1,s.c2,s.end]:[s.end])]);const path=typeof Path2D==='undefined'?null:new Path2D();if(path){cmds.forEach((c,k)=>trace(path,c,origin.x,origin.y,k===0));path.closePath();}return{id:i,origin,refs,commands:cmds,path,bounds:{left:Math.min(...points.map(p=>p[0]))-origin.x,right:Math.max(...points.map(p=>p[0]))-origin.x,top:Math.min(...points.map(p=>p[1]))-origin.y,bottom:Math.max(...points.map(p=>p[1]))-origin.y}};});
const seams=typeof Path2D==='undefined'?null:new Path2D();if(seams)edges.forEach(e=>trace(seams,commands(e,false)));const result={n,cw,ch,width,height,pieces,edges,seams,seed:hash(`uw-jigsaw-v1|${id}|${count}`)};cache.clear();cache.set(key,result);return result;}
const api={make,hash};root.UWJigsaw=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
