/* Sports Park V3: supplied art, isolated progression, continuous three-region terrain. */
(()=>{'use strict';const D=UWSportsData,A=UWArt,root=new URL('../assets/sports/v3/',document.currentScript.src),clamp=A.clamp,STORE='unicorn-world-sports-v3',S=.28;
const stations=[{id:'bike',x:600,y:650,picture:'wheel'},{id:'skate',x:1040,y:740,picture:'wheel'},{id:'basketball',x:359,y:1616,picture:'ball'},{id:'tennis',x:1180,y:1665,picture:'ball'},{id:'volleyball',x:488,y:2580,picture:'ball'}];
const gates=[{x:280,y:220},{x:140,y:500},{x:570,y:665}],ramps=[{id:'shallow-bank',x:1190,y:370},{id:'rounded-roller',x:1180,y:610}];
const poly=(x,y,pts)=>{let hit=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const [a,b]=pts[i],[c,d]=pts[j];if((b>y)!==(d>y)&&x<(c-a)*(y-b)/(d-b)+a)hit=!hit;}return hit;};
const ellipse=(x,y,cx,cy,rx,ry)=>((x-cx)/rx)**2+((y-cy)/ry)**2<1;
const rect=(x,y,a,b,w,h)=>x>a&&x<a+w&&y>b&&y<b+h;
class Park{
 constructor(w){this.w=w;this.im={};this.ready=false;this.loading=null;this.mode=null;this.pose=null;this.age=0;this.ball=null;this.pointer=null;this.queued=false;this.aim=0;this.progress={bike:[],skate:[],basketball:0,tennis:0,volleyball:0,completed:[]};this.camera={x:0,y:0};this.volleyStage=0;
 try{const p=JSON.parse(localStorage.getItem(STORE));if(p?.version===1){for(const k of ['bike','skate'])this.progress[k]=Array.isArray(p.progress?.[k])?[...new Set(p.progress[k].filter(n=>Number.isInteger(n)&&n>=0&&n<(k==='bike'?3:2)))]:[];for(const k of ['basketball','tennis','volleyball'])this.progress[k]=clamp(Number(p.progress?.[k])||0,0,k==='tennis'?5:3);this.progress.completed=(p.progress?.completed||[]).filter(k=>stations.some(s=>s.id===k));this.mode=stations.some(s=>s.id===p.mode)?p.mode:null;}}catch(_){}
 this.installUI();if(this.mode)this.resetRally();
 }
 save(){try{localStorage.setItem(STORE,JSON.stringify({version:1,mode:this.mode,progress:this.progress}));}catch(_){this.w.announce('Sports progress could not save. Your world purchases are unchanged.');}}
 installUI(){this.hud=document.createElement('div');this.hud.id='sports-tools';this.hud.hidden=true;this.hud.innerHTML='<div id="sports-progress" role="status"></div><button id="sports-retry" aria-label="Play this activity again">'+A.icon('play')+'</button>';document.body.append(this.hud);document.getElementById('sports-retry').onclick=()=>{if(this.mode)this.begin(this.mode,true);};}
 async load(){if(this.ready)return;if(this.loading)return this.loading;this.loading=(async()=>{const paths=[...D.world.world.regions.map(r=>r.file),...D.seams.placements.map(s=>'seams/'+s.png),...new Set(D.actions.frames.map(f=>'actions/'+f.source)),...D.props.assets.map(p=>'props/'+p.file),'props/volleyball.png','props/volleyball-net-receding.png','props/basketball-front-coverage-mask.png'];await Promise.all(paths.map(async file=>{const im=new Image();im.src=new URL(file,root);await im.decode();this.im[file]=im;}));this.seams=D.seams.placements.map(s=>{const im=this.im['seams/'+s.png],cv=document.createElement('canvas');cv.width=im.width;cv.height=im.height;const c=cv.getContext('2d');c.drawImage(im,0,0);c.globalCompositeOperation='destination-in';const g=c.createLinearGradient(0,0,0,cv.height);for(const [y,a]of D.seams.blend_contract.local_y_opacity_knots)g.addColorStop(y/cv.height,`rgba(0,0,0,${a})`);c.fillStyle=g;c.fillRect(0,0,cv.width,cv.height);return{canvas:cv,x:s.world_origin[0],y:s.world_origin[1]};});const source=this.im['props/basketball-hoop.png'],mask=this.im['props/basketball-front-coverage-mask.png'],cv=document.createElement('canvas');cv.width=source.width;cv.height=source.height;const c=cv.getContext('2d');c.drawImage(source,0,0);const src=c.getImageData(0,0,cv.width,cv.height);c.clearRect(0,0,cv.width,cv.height);c.drawImage(mask,0,0);const m=c.getImageData(0,0,cv.width,cv.height);for(let i=3;i<src.data.length;i+=4)src.data[i]=Math.round(src.data[i]*m.data[i-3]/255);c.putImageData(src,0,0);this.hoopFront=cv;this.makeIcons();this.ready=true;})().finally(()=>this.loading=null);return this.loading;}
 makeIcons(){this.icons={};for(const id of ['basketball','tennis','volleyball']){const key=id==='tennis'?'tennis-ball':id,p=D.actions.props[key],cv=document.createElement('canvas');cv.width=100;cv.height=100;const b=p.bounds;const ctx=cv.getContext('2d');ctx.drawImage(this.im['props/'+key+'.png'],b[0],b[1],b[2]-b[0],b[3]-b[1],4,4,92,92);this.icons[id]=cv.toDataURL();}for(const f of D.actions.frames){const cv=document.createElement('canvas');cv.width=100;cv.height=100;const [l,t,r,b]=f.source_rect_xyxy,s=Math.min(94/(r-l),94/(b-t)),ctx=cv.getContext('2d');ctx.drawImage(this.im['actions/'+f.source],l,t,r-l,b-t,50-(r-l)*s/2,50-(b-t)*s/2,(r-l)*s,(b-t)*s);this.icons[f.id]=cv.toDataURL();}}
 walkable(x,y){if(x<65||x>1470||y<20||y>3030)return false;
 let ok=false;if(y<1024){ok=poly(x,y,[[900,0],[1030,0],[990,65],[890,118],[805,160],[810,260],[845,430],[842,570],[875,700],[860,880],[890,1024],[705,1024],[720,880],[732,760],[717,625],[730,530],[732,410],[725,300],[705,180],[685,135],[825,100],[900,55]])|| (ellipse(x,y,385,430,330,320)&&!ellipse(x,y,455,400,250,180))||poly(x,y,[[960,210],[1250,190],[1430,315],[1480,590],[1370,685],[980,660],[900,430]])||rect(x,y,180,620,640,100)||rect(x,y,770,670,660,75);if(ellipse(x,y,455,400,250,180))ok=false;}
 else if(y<2048){const q=y-1024;ok=rect(x,q,705,0,130,1024)||(ellipse(x,q,768,225,155,145)&&!ellipse(x,q,768,225,102,100))||poly(x,q,D.world.geometry.courts.basketball.play_surface_polygon)||poly(x,q,D.world.geometry.courts.tennis.play_surface_polygon)||rect(x,q,120,800,1290,65)||rect(x,q,305,680,95,140)||rect(x,q,1170,675,100,155);if(ellipse(x,q,768,225,102,100)||rect(x,q,320,222,80,40)||rect(x,q,983,430,347,30))ok=false;}
 else{const q=y-2048;ok=rect(x,q,700,0,145,300)||rect(x,q,110,180,1295,100)||rect(x,q,140,250,160,495)||rect(x,q,1240,250,150,495)||poly(x,q,D.world.geometry.courts.volleyball.play_surface_polygon)||rect(x,q,100,735,1320,95)||rect(x,q,705,710,130,315)||rect(x,q,380,680,130,100)||rect(x,q,1070,680,130,100);if(rect(x,q,730,320,80,380))ok=false;}
 return ok;}
 stations(){return stations.map(s=>({...s,r:90}));}
 iconFor(id){return this.icons[id]||(['bike','skate'].includes(id)?A.imagePiece(UWCatalog.byId[id==='skate'?'skateboard':'bike']):A.iconURL('door'));}
 actionURL(){if(this.mode==='tennis')return this.icons.tennis_contact;return this.mode==='volleyball'?this.icons[this.volleyStage===0?'volleyball_bump':this.volleyStage===1?'volleyball_set':'volleyball_hit']:this.iconFor(this.mode);}
 focus(player){if(this.mode)return{id:this.mode,x:player.x,y:player.y,action:true};if(player.y<140&&Math.abs(player.x-990)<110)return{id:'park-exit',exit:true,to:'village',x:990,y:45,picture:'home'};return stations.find(s=>Math.hypot(player.x-s.x,player.y-s.y)<130)||null;}
 begin(id,replay=false){if(!stations.some(s=>s.id===id))return;this.mode=id;document.getElementById('guide').classList.remove('show');this.pointer=null;this.queued=false;this.age=0;this.aim=0;if(replay){this.progress[id]=['bike','skate'].includes(id)?[]:0;this.progress.completed=this.progress.completed.filter(k=>k!==id);}const s=stations.find(s=>s.id===id);if(['bike','skate'].includes(id))Object.assign(this.w.player,{x:id==='bike'?580:1030,y:id==='bike'?650:740});else Object.assign(this.w.player,{x:s.x,y:s.y,facing:1});this.resetRally();this.save();this.w.announce({bike:'Ride through three arches, then return to the north entrance.',skate:'Glide over the bank and roller, or use their flat bypasses.',basketball:'Drag toward the hoop and release, or press the ball button. Three baskets.',tennis:'Move along the baseline and press the ball button to swing. Five returns.',volleyball:'Press the picture button to bump, set, then hit. Three returns.'}[id]);}
 stop(){const old=this.mode;this.mode=null;this.pose=null;this.ball=null;this.pointer=null;this.queued=false;this.hud.hidden=true;this.save();if(old==='tennis')this.w.player.y=1720;}
 resetRally(){this.age=0;this.pose=this.mode==='basketball'?'basketball_ready':this.mode==='tennis'?'tennis_ready':this.mode==='volleyball'?'volleyball_ready':null;this.volleyStage=0;this.queued=false;this.flight=null;if(this.mode==='tennis'||this.mode==='volleyball')this.serve();else this.ball=null;}
 cancel(){const id=this.pointer?.id;this.pointer=null;if(id!==undefined)try{this.w.canvas.releasePointerCapture(id);}catch(_){}}
 leaveWorld(){this.hud.hidden=true;this.cancel();this.save();}
 frame(id=this.pose){return D.actions.frames.find(f=>f.id===id);}
 anchor(id=this.pose,x=this.w.player.x,y=this.w.player.y,facing=this.w.player.facing,exit=false){const f=this.frame(id),a=exit?f.ball_handoff_on_exit:f.ball;if(!a)return null;const [px,py]=f.ground_pivot_source,[bx,by]=a.center_source;return{x:x+(bx-px)*f.scale_to_logical*S*facing,y:y+(by-py)*f.scale_to_logical*S,diameter:a.visible_diameter_source*f.scale_to_logical*S,logicalDiameter:a.visible_diameter_source*f.scale_to_logical,kind:a.kind};}
 actor(c,id,x,y,facing=1,scale=S){const f=this.frame(id),[l,t,r,b]=f.source_rect_xyxy,[px,py]=f.ground_pivot_source;c.save();c.translate(x,y);c.scale(facing*scale,scale);c.drawImage(this.im['actions/'+f.source],l,t,r-l,b-t,(l-px)*f.scale_to_logical,(t-py)*f.scale_to_logical,(r-l)*f.scale_to_logical,(b-t)*f.scale_to_logical);c.restore();}
 ballDraw(c,b){if(!b||b.hidden)return;const p=D.actions.props[b.kind],a=p.bounds,im=this.im['props/'+b.kind+'.png'];c.drawImage(im,a[0],a[1],a[2]-a[0],a[3]-a[1],b.x-(a[2]-a[0])*b.diameter/Math.max(a[2]-a[0],a[3]-a[1])/2,b.y-(b.z||0)-(a[3]-a[1])*b.diameter/Math.max(a[2]-a[0],a[3]-a[1])/2,(a[2]-a[0])*b.diameter/Math.max(a[2]-a[0],a[3]-a[1]),(a[3]-a[1])*b.diameter/Math.max(a[2]-a[0],a[3]-a[1]));}
 prop(c,id,x,y,width){const p=D.props.assets.find(p=>p.file===id+'.png'),im=this.im['props/'+id+'.png'],a=p.visible_bounds_alpha_at_least_10_xyxy,s=width/(a[2]-a[0]),pivot=p.suggested_pivot_px;c.drawImage(im,x-pivot[0]*s,y-pivot[1]*s,im.width*s,im.height*s);}
 hoop(){return{x:359-611.5*.1,y:1269-1222*.1,scale:.1,mouth:{x:359.05,y:1269+(570-1222)*.1},bottom:1269+(849-1222)*.1};}
 drawHoop(c){const h=this.hoop(),im=this.im['props/basketball-hoop.png'];c.drawImage(im,h.x,h.y,im.width*h.scale,im.height*h.scale);}
 occludeHoop(c,b){if(!b)return;const h=this.hoop(),cy=b.y-(b.z||0),r=b.diameter/2,zone=D.hoop.clip_bounds_xyxy;if(b.x+r<h.x+zone[0]*h.scale||b.x-r>h.x+zone[2]*h.scale||cy+r<h.y+zone[1]*h.scale||cy-r>h.y+zone[3]*h.scale)return;c.save();c.beginPath();c.rect(b.x-r,cy-r,b.diameter,b.diameter);c.clip();c.drawImage(this.hoopFront,h.x,h.y,this.hoopFront.width*h.scale,this.hoopFront.height*h.scale);c.restore();}
 serve(){this.age=0;this.queued=false;if(this.mode==='tennis'){const u=.35+(this.progress.tennis%3)*.15;this.incomingTarget=this.projectCourt('tennis',u,.85);const start=this.projectCourt('tennis',.5,.18);this.ball={kind:'tennis-ball',diameter:D.actions.ball_size_contract.tennis_logical_diameter*S,x:start.x,y:start.y,z:10,phase:'in',age:0,start};}else if(this.mode==='volleyball'){this.volleyStage=0;const a=this.anchor('volleyball_bump');this.ball={kind:'volleyball',diameter:D.actions.ball_size_contract.volleyball_logical_diameter*S,x:1085,y:2550,z:80,phase:'in',age:0,start:{x:1085,y:2550},target:a};this.pose='volleyball_ready';}}
 projectCourt(id,u,v){const q=D.world.geometry.courts[id],p=q.play_surface_polygon,top={x:p[0][0]+(p[1][0]-p[0][0])*u,y:p[0][1]+(p[1][1]-p[0][1])*u},bottom={x:p[3][0]+(p[2][0]-p[3][0])*u,y:p[3][1]+(p[2][1]-p[3][1])*u};return{x:top.x+(bottom.x-top.x)*v,y:1024+top.y+(bottom.y-top.y)*v};}
 action(){if(!this.mode)return;if(this.progress.completed.includes(this.mode)){this.begin(this.mode,true);return;}if(this.mode==='basketball'){if(this.flight)return;this.pose='basketball_aim';this.age=0;this.queued=true;}else if(this.mode==='tennis')this.queued=true;else if(this.mode==='volleyball'){if(this.ball?.phase==='in'){this.queued=true;}else if(this.volleyStage===1&&this.ball?.phase==='hold'){this.pose='volleyball_set';this.age=0;this.ball.hidden=true;}else if(this.volleyStage===2&&this.ball?.phase==='hold'){this.pose='volleyball_hit';this.age=0;this.ball.phase='hit';this.ball.start={x:this.ball.x,y:this.ball.y};}}else if(this.mode==='bike'||this.mode==='skate'){this.stop();}}
 move(dx,dy,dt){if(this.mode==='basketball')return false;if(this.mode==='tennis'){const p=this.w.player,before=p.x;p.x=clamp(p.x+dx*220*dt,1020,1245);p.facing=1;return Math.abs(p.x-before)>.1;}if(this.mode==='volleyball'){const p=this.w.player,before=p.y;p.y=clamp(p.y+dy*170*dt,2490,2690);p.facing=1;return Math.abs(p.y-before)>.1;}return null;}
 down(e,p){if(!['basketball','tennis','volleyball'].includes(this.mode))return false;if(this.pointer||e.button>0)return true;this.pointer={id:e.pointerId};this.w.canvas.setPointerCapture(e.pointerId);if(this.mode==='basketball'&&!this.flight){this.pose='basketball_aim';this.age=0;this.aim=clamp((p.x-this.hoop().mouth.x)/180,-1,1);}else if(this.mode==='tennis'){this.w.player.x=clamp(p.x-this.anchor('tennis_contact',0,0,1).x,1020,1245);}else if(this.mode==='volleyball'){this.w.player.y=clamp(p.y-this.anchor('volleyball_bump',0,0,1).y,2490,2690);}return true;}
 pointerMove(e,p){if(this.pointer?.id!==e.pointerId)return false;if(this.mode==='basketball'&&!this.flight)this.aim=clamp((p.x-this.hoop().mouth.x)/180,-1,1);else if(this.mode==='tennis')this.w.player.x=clamp(p.x-this.anchor('tennis_contact',0,0,1).x,1020,1245);else if(this.mode==='volleyball')this.w.player.y=clamp(p.y-this.anchor('volleyball_bump',0,0,1).y,2490,2690);return true;}
 up(e,p,cancel=false){if(this.pointer?.id!==e.pointerId)return false;this.pointerMove(e,p);this.pointer=null;if(!cancel&&this.mode==='basketball'&&!this.flight)this.queued=true;try{this.w.canvas.releasePointerCapture(e.pointerId);}catch(_){}return true;}
 credit(id){this.progress[id]=Math.min(id==='tennis'?5:3,this.progress[id]+1);if(this.progress[id]===(id==='tennis'?5:3)){if(!this.progress.completed.includes(id))this.progress.completed.push(id);this.w.announce('Practice complete. Press replay to play again or the back picture to leave.');}else this.w.announce(this.progress[id]+' successful returns.');this.save();}
 tick(dt,moving){if(!this.ready)return;this.age+=dt;const p=this.w.player;if(this.mode==='bike'){gates.forEach((g,i)=>{if(Math.abs(p.x-g.x)<70&&Math.abs(p.y-g.y)<45&&!this.progress.bike.includes(i)){this.progress.bike.push(i);this.save();this.w.announce('Checkpoint '+this.progress.bike.length+' of 3.');}});if(this.progress.bike.length===3&&Math.hypot(p.x-990,p.y-50)<95&&!this.progress.completed.includes('bike')){this.progress.completed.push('bike');this.save();this.w.announce('Bicycle route complete.');}}
 if(this.mode==='skate'){ramps.forEach((g,i)=>{if(p.x>960&&p.x<1450&&Math.abs(p.y-g.y)<55&&!this.progress.skate.includes(i)){this.progress.skate.push(i);this.save();this.w.announce('Skate route '+this.progress.skate.length+' of 2.');}});if(this.progress.skate.length===2&&!this.progress.completed.includes('skate')){this.progress.completed.push('skate');this.save();this.w.announce('Skate route complete. Flat bypasses count too.');}}
 if(this.mode==='basketball'){if(this.pose==='basketball_aim'&&this.queued&&this.age>=.18){this.pose='basketball_release';this.age=0;this.queued=false;const a=this.anchor(),h=this.hoop();this.flight={start:a,target:{x:h.mouth.x+this.aim*180,y:h.mouth.y},t:0,hit:Math.abs(this.aim)<.22};}if(this.flight){const f=this.flight;f.t+=dt;const t=clamp(f.t/1.3,0,1);this.ball={kind:'basketball',diameter:85*S,x:f.start.x+(f.target.x-f.start.x)*t,y:f.start.y+(f.target.y-f.start.y)*t-180*Math.sin(Math.PI*t)};if(f.t>1.3)this.ball.y=f.target.y+(f.t-1.3)*95;if(f.t>1.75){if(f.hit)this.credit('basketball');this.flight=null;this.ball=null;this.pose='basketball_ready';this.age=0;}}}
 if(this.mode==='tennis'){const b=this.ball;if(b){b.age+=dt;if(b.phase==='in'){const target={x:this.incomingTarget.x,y:this.anchor('tennis_contact').y};const t=clamp(b.age/1.2,0,1);b.x=b.start.x+(target.x-b.start.x)*t;b.y=b.start.y+(target.y-b.start.y)*t;b.z=25*Math.sin(Math.PI*t);if(this.queued&&b.age>=1.0&&this.pose==='tennis_ready'){this.pose='tennis_backswing';this.age=0;}if(this.pose==='tennis_backswing'&&this.age>=.12){this.pose='tennis_contact';this.age=0;this.queued=false;const a=this.anchor();if(Math.hypot(b.x-a.x,b.y-(b.z||0)-a.y)<30){Object.assign(b,a,{phase:'out',age:0,start:a});this.credit('tennis');}else{this.pose='tennis_ready';this.serve();}}else if(b.age>1.7){this.pose='tennis_ready';this.serve();this.w.announce('Try the next ball. Your returns are kept.');}}else{const end=this.projectCourt('tennis',.5,.18),t=clamp(b.age/.9,0,1);b.x=b.start.x+(end.x-b.start.x)*t;b.y=b.start.y+(end.y-b.start.y)*t;b.z=30*Math.sin(Math.PI*t);if(this.pose==='tennis_contact'&&this.age>=.09)this.pose='tennis_ready';if(b.age>.95){if(this.progress.completed.includes('tennis'))this.ball=null;else this.serve();}}}}
 if(this.mode==='volleyball'&&!this.progress.completed.includes('volleyball')){const b=this.ball;if(b){b.age+=dt;if(b.phase==='in'){const target=this.anchor('volleyball_bump'),t=clamp(b.age/1.25,0,1);b.x=b.start.x+(target.x-b.start.x)*t;b.y=b.start.y+(target.y-b.start.y)*t;b.z=80*(1-t);if(this.queued&&b.age>=1){this.queued=false;this.pose='volleyball_bump';this.age=0;Object.assign(b,target,{phase:'bump',age:0,z:0});}else if(b.age>1.8)this.serve();}else if(b.phase==='bump'){if(this.age>=.14){this.volleyStage=1;b.phase='hold';this.pose='volleyball_ready';Object.assign(b,this.anchor('volleyball_set',p.x,p.y,p.facing,true));}}else if(this.pose==='volleyball_set'&&this.age>=.14){Object.assign(b,this.anchor('volleyball_set',p.x,p.y,p.facing,true),{hidden:false,phase:'hold',age:0});this.volleyStage=2;this.pose='volleyball_ready';}else if(b.phase==='hit'){const a=this.anchor('volleyball_hit'),t=clamp(this.age/.1,0,1);b.x=b.start.x+(a.x-b.start.x)*t;b.y=b.start.y+(a.y-b.start.y)*t;if(this.age>=.1){Object.assign(b,a,{phase:'out',age:0,start:a});this.pose='volleyball_ready';}}else if(b.phase==='out'){const t=clamp(b.age/1.25,0,1);b.x=b.start.x+(1085-b.start.x)*t;b.y=b.start.y+(2550-b.start.y)*t;b.z=145*Math.sin(Math.PI*t);if(t>=1){this.credit('volleyball');if(!this.progress.completed.includes('volleyball'))this.serve();}}}}
 this.updateUI();}
 updateUI(){this.hud.hidden=!this.mode;if(!this.mode)return;const n=['bike','skate'].includes(this.mode)?this.progress[this.mode].length:this.progress[this.mode]||0,total=this.mode==='tennis'?5:this.mode==='skate'?2:3;const signature=[this.mode,n,this.progress.completed.includes(this.mode)].join(':');if(this.uiSignature===signature)return;this.uiSignature=signature;const node=document.getElementById('sports-progress');node.innerHTML=(this.progress.completed.includes(this.mode)?A.icon('check'):this.mode==='bike'||this.mode==='skate'?'<img class="picture-sprite" src="'+this.iconFor(this.mode)+'" alt="">':'<img class="picture-sprite" src="'+this.icons[this.mode]+'" alt="">')+'<span>'+n+' / '+total+'</span>';document.getElementById('sports-retry').hidden=!this.progress.completed.includes(this.mode);}
 view(){const p=this.w.player;let x=p.x-384,y=p.y-270;if(this.mode==='basketball'){x=0;y=1125;}if(this.mode==='tennis'){x=768;y=1200;}if(this.mode==='volleyball'){x=380;y=2275;}this.camera={x:clamp(x,0,768),y:clamp(y,0,2560)};return this.camera;}
 draw(c,time,moving,outfit){if(!this.ready)return;const camera=this.view();c.save();c.translate(-camera.x,-camera.y);for(const r of D.world.world.regions)if(r.origin[1]<camera.y+512&&r.origin[1]+1024>camera.y)c.drawImage(this.im[r.file],...r.origin);for(const s of this.seams)if(s.y<camera.y+512&&s.y+1024>camera.y)c.drawImage(s.canvas,s.x,s.y);
 const freeActor=!['basketball','tennis','volleyball'].includes(this.mode),p=this.w.player;let freeDrawn=false;const drawFree=()=>{if(!freeActor||freeDrawn)return;freeDrawn=true;const ride=this.mode==='bike'?'bike':this.mode==='skate'?'skateboard':this.w.service.value.vehicle,frame=ride?ride+(moving?Math.floor(time*10)%4:0):moving?'u_run'+Math.floor(time*10)%6:'u_idle'+Math.floor(time*2)%2;const lift=this.mode==='skate'?Math.max(0,...ramps.map(r=>Math.abs(this.w.player.x-r.x)<80?14*Math.max(0,1-Math.abs(this.w.player.y-(r.y-25))/45):0)):0;A.unicorn(c,this.w.player.x,this.w.player.y-lift,80,outfit,frame,this.w.player.facing<0,ride);};
 for(const r of ramps)this.prop(c,r.id,r.x,r.y,190);for(const g of gates)this.prop(c,'checkpoint-arch',g.x,g.y,115);if(freeActor&&p.x<650&&p.y>1220&&p.y<1269)drawFree();this.drawHoop(c);
 if(freeActor&&p.x>965&&p.y>1220&&p.y<1469)drawFree();if(this.mode!=='tennis')this.prop(c,'tennis-net',1156.5,1469,347);
 const fit=D.net.court_fit,drawVolleyNet=()=>{const im=this.im['props/volleyball-net-receding.png'];c.drawImage(im,fit.recommended_translation_for_centered_baseline[0],2048+fit.recommended_translation_for_centered_baseline[1],im.width*fit.uniform_scale_to_y_span,im.height*fit.uniform_scale_to_y_span);};
 if(this.mode==='volleyball'){this.actor(c,'volleyball_ready',1085,2580,-1);if(this.ball&&this.ball.x>=768&&(this.ball.z||0)<120)this.ballDraw(c,this.ball);drawVolleyNet();this.actor(c,this.pose,this.w.player.x,this.w.player.y,1);if(this.ball&&(this.ball.x<768||(this.ball.z||0)>=120))this.ballDraw(c,this.ball);}else{if(freeActor&&p.x>=768&&p.y>2320&&p.y<2780)drawFree();drawVolleyNet();}
 if(this.mode==='basketball'){const held=!this.flight?this.anchor():null;if(held&&this.frame().ball.layer==='back')this.ballDraw(c,held);this.actor(c,this.pose,this.w.player.x,this.w.player.y,this.w.player.facing);if(held&&this.frame().ball.layer==='front')this.ballDraw(c,held);if(this.ball){this.ballDraw(c,this.ball);this.occludeHoop(c,this.ball);}if(!this.flight){const h=this.hoop();A.ellipse(c,h.mouth.x+this.aim*180,h.mouth.y,18,10,null,'#fff1b8',3);}}
 else if(this.mode==='tennis'){if(this.ball?.phase==='in')A.ellipse(c,this.incomingTarget.x,this.w.player.y,30,12,null,'#fff1b8',3);this.actor(c,'tennis_ready',1143,1315,-1,.21);if(this.ball&&this.ball.y<1469&&(this.ball.z||0)<30)this.ballDraw(c,this.ball);this.prop(c,'tennis-net',1156.5,1469,347);this.actor(c,this.pose,this.w.player.x,this.w.player.y,1);if(this.ball&&(this.ball.y>=1469||(this.ball.z||0)>=30))this.ballDraw(c,this.ball);}
 else if(this.mode!=='volleyball'){drawFree();}
 if(!this.mode){for(const s of stations){c.save();c.globalAlpha=.9;A.ellipse(c,s.x,s.y,30,13,'#fff1d088','#b789a0',2);if(this.icons[s.id]){const im=this.im['props/'+(s.id==='tennis'?'tennis-ball':s.id)+'.png'];this.ballDraw(c,{kind:s.id==='tennis'?'tennis-ball':s.id,x:s.x,y:s.y-18,diameter:25});}else{const im=A.images['item:'+(s.id==='skate'?'skateboard':'bike')];if(im)A.sprite(c,im,s.x,s.y-10,35,30);}c.restore();}}
 if(['bike','skate'].includes(this.mode)&&!this.progress.completed.includes(this.mode)){const goals=this.mode==='bike'?gates:ramps,next=goals.find((_,i)=>!this.progress[this.mode].includes(i))||{x:990,y:50};A.ellipse(c,next.x,next.y,65,32,null,'#fff2bd',4);const dx=next.x-this.w.player.x,dy=next.y-this.w.player.y,px=clamp(next.x-camera.x,72,696),py=clamp(next.y-camera.y,130,422);if(next.x-camera.x!==px||next.y-camera.y!==py){c.save();c.translate(camera.x+px,camera.y+py);c.rotate(Math.atan2(dy,dx));A.picture(c,'arrow',0,0,48,38);c.restore();}}
 c.restore();}
}
window.UWSportsPark=Park;
})();
