/* Sneaky Unicorn v15. Only this app's cache is managed here. */
const VERSION='15.0.0-pictures-4-touch';
const ROOT=new URL(self.registration.scope);
const PREFIX='sneaky-unicorn-scope-'+encodeURIComponent(ROOT.pathname)+'-';
const CACHE=PREFIX+VERSION;
const INDEX=new URL('index.html',ROOT).href;
const APP=['index.html','manifest.webmanifest','icons/apple-touch-icon.png','icons/icon-192.png','icons/icon-512.png','icons/ui-sound-v1.png','icons/ui-settings-v1.png'].map(p=>new URL(p,ROOT).href);
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(APP)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE&&(k.startsWith(PREFIX)||/^sneaky-unicorn-v[1-9]$/.test(k))).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',event=>{const req=event.request,url=new URL(req.url);if(req.method!=='GET'||url.origin!==ROOT.origin||!url.pathname.startsWith(ROOT.pathname))return;event.respondWith((async()=>{const cache=await caches.open(CACHE);if(req.mode==='navigate'){try{const response=await fetch(req);if(response.ok){await cache.put(INDEX,response.clone());return response;}}catch(_){}return await cache.match(INDEX)||new Response(`<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sneaky Unicorn</title><style>body{margin:0;height:100dvh;display:grid;place-items:center;background:#fff8e7}button{width:88px;height:88px;border:3px solid #fff7d7;border-radius:50%;background:#e1c8ee;box-shadow:0 4px 0 #704c76;color:#68477c}svg{width:60px;height:60px}</style><button onclick="location.reload()" aria-label="Reconnect to load the game, then try again"><svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M13 27a21 21 0 1 1 2 18M13 12v16h17"/></svg></button></html>`,{status:503,headers:{'Content-Type':'text/html; charset=utf-8'}});}const cached=await cache.match(req);if(cached)return cached;try{const response=await fetch(req);if(response.ok&&APP.includes(url.href))await cache.put(req,response.clone());return response;}catch(_){return new Response('',{status:503});}})());});
self.addEventListener('message',event=>{if(event.data?.type!=='APP_STATUS')return;event.waitUntil(caches.open(CACHE).then(cache=>cache.match(INDEX)).then(cached=>event.ports[0]?.postMessage({version:VERSION,cached:!!cached})));});
