const {chromium}=require('/Users/deanguedo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict'),fs=require('node:fs');const out=process.env.WORLD_QA_OUTPUT||'/tmp/unicorn-puzzle-worlds';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const results=[],errors=[];const pass=n=>{results.push(n);console.log('PASS',n)};try{const ctx=await b.newContext({viewport:{width:932,height:430},hasTouch:true,deviceScaleFactor:2});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.WORLD_QA_URL||'http://localhost:8890/hub/')+'?qa=1');await p.waitForFunction(()=>window.__WORLD_TEST__?.snapshot().loaded);
const open=async()=>{await p.evaluate(()=>__WORLD_TEST__.mall.open('library'));await p.waitForSelector('.puzzle-tile')},close=async()=>{await p.locator('#panel-close').click();await p.waitForFunction(()=>!__WORLD_TEST__.snapshot().panel)},profile=()=>p.evaluate(()=>__WORLD_TEST__.service.value);
await p.evaluate(async()=>{const s=__WORLD_TEST__.service;for(let i=0;i<4;i++)await s.run('earn',{game:'adventure',event:{id:'puzzles-funds-'+i,kind:'win'}});});await open();assert.equal(await p.locator('.puzzle-grid .puzzle-tile').count(),8);assert.equal(await p.evaluate(()=>UWCatalog.puzzles.length),56);assert.equal(await p.evaluate(()=>UWPuzzles.masters.size),0);await p.locator('.puzzle-grid img').evaluateAll(ims=>Promise.all(ims.map(im=>im.decode())));await p.screenshot({path:out+'/gallery.png'});pass('Eight exact scenic previews replace the visible gallery; all 48 legacy IDs remain and masters load on demand');
// Selected full image must fail before payment, then recover from the same Play button.
const wallet=(await profile()).coins;const pattern='**/uw-puzzle-enchanted-garden-v1.webp';await p.route(pattern,r=>r.abort());await p.locator('[data-action="start"]').click();await p.waitForFunction(()=>!__WORLD_TEST__.mall.loadingPicture);assert.equal((await profile()).coins,wallet);assert.equal(await p.locator('#round-canvas').count(),0);await p.unroute(pattern);await p.locator('[data-action="start"]').click();await p.waitForSelector('#round-canvas');assert.equal((await profile()).coins,wallet-1);pass('Failed master decode spends no coin; the same Play button retries successfully');
await p.screenshot({path:out+'/loose-tabbed-piece.png'});
const geometry=await p.evaluate(()=>{const stats=[];for(const q of UWCatalog.visiblePuzzles)for(const count of [4,9,16]){const scale=Math.min(540/q.width,371.43/q.height),cut=UWJigsaw.make(q.id,count,q.width*scale,q.height*scale),n=Math.sqrt(count),canvas=document.createElement('canvas'),c=canvas.getContext('2d');const refs=new Map();for(const piece of cut.pieces){for(const [edge,reverse]of piece.refs){if(!refs.has(edge))refs.set(edge,[]);refs.get(edge).push(reverse);}const a=piece.commands[0].start,z=piece.commands.at(-1).segments.at(-1).end;if(a[0]!==z[0]||a[1]!==z[1])throw Error('Open shape');}let internal=0;for(const [edge,uses]of refs){if(edge.flat){if(uses.length!==1||edge.segments.length!==1||edge.segments[0].type!=='L')throw Error('Outer edge');}else{internal++;if(uses.length!==2||uses[0]===uses[1])throw Error('Shared curve mismatch');}}
for(let y=.71;y<cut.height;y+=3.97)for(let x=.43;x<cut.width;x+=4.03){const owners=cut.pieces.filter(pc=>c.isPointInPath(pc.path,x-pc.origin.x,y-pc.origin.y)).length;if(owners!==1)throw Error('Gap or overlap '+q.id+' '+count+' '+x+','+y);}
if(internal!==2*n*(n-1))throw Error('Edge count');stats.push({id:q.id,count,internal});}return stats});assert.equal(geometry.length,24);pass('All 24 deterministic cuts are closed, share exact reversed curves, have flat borders and single-owner raster coverage');
async function pointerPoint(x,y){return p.evaluate(({x,y})=>{const m=__WORLD_TEST__.mall,r=m.cv.getBoundingClientRect(),fit=Math.min(r.width/m.cv.width,r.height/m.cv.height);return{x:r.x+(r.width-m.cv.width*fit)/2+x*fit,y:r.y+(r.height-m.cv.height*fit)/2+y*fit};},{x,y});}
async function placeOne(touch=false,offset={x:0,y:0}){const coords=await p.evaluate(()=>{const m=__WORLD_TEST__.mall,r=m.puzzleRects(),i=m.selection;return{tray:r.tray,target:{x:r.x+(i%r.n+.5)*r.cw,y:r.y+(Math.floor(i/r.n)+.5)*r.ch}}});const a=await pointerPoint(coords.tray.x+offset.x,coords.tray.y+offset.y),z=await pointerPoint(coords.target.x+offset.x,coords.target.y+offset.y);if(touch){const cd=await ctx.newCDPSession(p);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[z]});await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cd.detach();}else{await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(z.x,z.y,{steps:4});await p.mouse.up();}await p.waitForTimeout(35);}
// Find an actual lobe and socket from the path, rather than a rectangular bounding box.
const masks=await p.evaluate(()=>{const m=__WORLD_TEST__.mall,r=m.puzzleRects();let tab=null,hole=null;for(const pc of r.cut.pieces){for(let y=2;y<r.ch-2;y+=3)for(let x=2;x<r.cw-2;x+=3)if(!m.cc.isPointInPath(pc.path,x,y)&&!hole)hole={piece:pc.id,x,y};for(let y=pc.bounds.top+1;y<pc.bounds.bottom;y+=2)for(let x=pc.bounds.left+1;x<pc.bounds.right;x+=2)if((x<0||x>r.cw||y<0||y>r.ch)&&m.cc.isPointInPath(pc.path,x,y)&&!tab)tab={piece:pc.id,x,y};}return{tab,hole}});assert.ok(masks.tab&&masks.hole);
for(const [kind,v]of Object.entries(masks)){await p.evaluate(v=>{const m=__WORLD_TEST__.mall;m.selection=v.piece;m.drawRound()},v);const at=await p.evaluate(v=>{const r=__WORLD_TEST__.mall.puzzleRects();return{x:r.tray.x+(v.x-r.cw/2)*r.trayScale,y:r.tray.y+(v.y-r.ch/2)*r.trayScale}},v),pt=await pointerPoint(at.x,at.y);await p.mouse.move(pt.x,pt.y);await p.mouse.down();assert.equal(await p.evaluate(()=>!!__WORLD_TEST__.mall.drag),kind==='tab');if(kind==='tab'){const anchor=await p.evaluate(()=>({x:__WORLD_TEST__.mall.drag.x,y:__WORLD_TEST__.mall.drag.y,tray:__WORLD_TEST__.mall.puzzleRects().tray}));assert.equal(anchor.x,anchor.tray.x);assert.equal(anchor.y,anchor.tray.y);await p.evaluate(()=>__WORLD_TEST__.mall.cancelControls());}await p.mouse.up();}
pass('Visible tabs pick up, socket holes reject pickup, and off-center pickup preserves the resting anchor');
await p.evaluate(()=>{const m=__WORLD_TEST__.mall;m.selection=0;m.drawRound()});await placeOne(true,{x:8,y:7});await p.waitForFunction(()=>__WORLD_TEST__.mall.round.state.placed.length===1);await p.screenshot({path:out+'/partly-completed.png'});const key=await p.evaluate(()=>__WORLD_TEST__.mall.round.key);await close();await p.reload();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);await open();await p.locator('[data-action="start"]').click();await p.waitForSelector('#round-canvas');assert.equal((await profile()).coins,wallet-1);assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.round.state.placed.length),1);pass('Touch placement, close, refresh and free resume retain placed pieces and the paid balance');
for(const q of await p.evaluate(()=>UWCatalog.visiblePuzzles))for(const count of [4,9,16]){if(!(q.order===0&&count===4)){await close();await open();await p.locator('[data-action="picture"][data-puzzle="'+q.id+'"]').click();await p.locator('[data-action="pieces"][data-pieces="'+count+'"]').click();await p.locator('[data-action="start"]').click();await p.waitForSelector('#round-canvas');}
const before=await profile();for(let i=await p.evaluate(()=>__WORLD_TEST__.mall.round.state.placed.length);i<count;i++){await placeOne(i%2===1);}
await p.waitForSelector('.completed-picture');const after=await profile();assert.equal(after.coins,before.coins+1);assert.equal(after.sessions[q.id+':'+count].status,'done');assert.equal(after.sessions[q.id+':'+count].state.placed.length,count);assert.ok(await p.evaluate(()=>UWPuzzles.masters.size<=2));if(q.order===0&&count===4)await p.screenshot({path:out+'/seamless-completion.png'});await p.evaluate(async()=>{const m=__WORLD_TEST__.mall;await m.service.run('finish',{session:m.round.id,state:m.round.state})});assert.equal((await profile()).coins,after.coins);}
pass('All eight scenes finish at 4, 9 and 16 pieces using actual mouse/touch drops, returning one coin exactly once; cache stays bounded');
await close();await p.evaluate(async()=>{const s=__WORLD_TEST__.service;const r=await s.run('start',{game:'jigsaw',puzzle:'unicorns-1',pieces:4});await s.run('progress',{session:r.value.session.id,state:{placed:[0],guide:true}})});await open();await p.locator('.legacy-continue [data-action="picture"]').click();await p.locator('[data-action="start"]').click();await p.waitForSelector('#round-canvas');assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.puzzleRects().cut),null);assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.round.state.placed.length),1);await p.screenshot({path:out+'/legacy-resume.png'});pass('Continue retains old paid rounds, their original composite art and rectangular cut, without new-scene completion badges');
await close();await open();await p.locator('[data-action="picture"][data-puzzle="worlds-toy-train-v1"]').click();await p.locator('[data-action="pieces"][data-pieces="16"]').click();await p.locator('[data-action="start"]').click();await p.waitForSelector('#round-canvas');await p.locator('#round-canvas').focus();await p.keyboard.press('ArrowLeft');assert.ok(await p.evaluate(()=>__WORLD_TEST__.mall.drag?.id===-1));await p.setViewportSize({width:393,height:852});await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>__WORLD_TEST__.mall.drag),null);await p.setViewportSize({width:568,height:320});await p.waitForTimeout(100);assert.ok(await p.locator('.game-footer button').evaluateAll(bs=>bs.every(b=>{const r=b.getBoundingClientRect();return r.width>=44&&r.height>=44&&r.bottom<=innerHeight})));await p.screenshot({path:out+'/narrow-landscape.png'});pass('Keyboard controls, portrait cancellation and 44px controls survive high-DPI narrow landscape');assert.deepEqual(errors,[]);pass('No browser exceptions');fs.writeFileSync(out+'/QA-RESULTS.json',JSON.stringify({results,geometry},null,2));}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
