/* Isolated browser contract and real pointer checks. Never touches a player's profile. */
const {chromium}=require('/Users/deanguedo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const out=process.env.SPORTS_QA_OUTPUT||'/tmp/unicorn-sports-qa';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),checks=[],errors=[];const check=(name,value)=>{assert.ok(value,name);checks.push(name);};try{const p=await b.newPage({viewport:{width:932,height:430}});p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});await p.goto((process.env.SPORTS_QA_URL||'http://localhost:8890/hub/')+'?qa=1');await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);
const original=await p.evaluate(()=>JSON.stringify(__WORLD_TEST__.service.value));
// Entrance uses actual action button, not direct navigation.
await p.evaluate(()=>__WORLD_TEST__.place(1205,875));await p.locator('#enter').click();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().scene==='park'&&__WORLD_TEST__.park.ready);await p.waitForTimeout(100);await p.screenshot({path:path.join(out,'01-north-entry.png')});check('South hub entrance loads park',await p.evaluate(()=>__WORLD_TEST__.snapshot().player.y===200));
const geometry=await p.evaluate(()=>{const P=__WORLD_TEST__.park,W=154,H=308,step=10,seen=new Set(),q=[[77,20]],targets=[[60,65],[104,74],[35,162],[118,166],[49,258],[28,22],[14,50],[57,66],[119,37],[118,61],[77,101],[77,104],[77,203],[77,206]],blocked=[[455,400],[768,1249],[770,2600],[359,1260],[1150,1470]];while(q.length){const [x,y]=q.shift(),key=y*W+x;if(seen.has(key)||x<0||x>=W||y<0||y>=H||!P.walkable(x*step,y*step))continue;seen.add(key);q.push([x+1,y],[x-1,y],[x,y+1],[x,y-1]);}return{reachable:targets.map(([x,y])=>seen.has(y*W+x)),blocked:blocked.map(([x,y])=>!P.walkable(x,y)),count:seen.size};});console.log(geometry);check('All five stations, gates, ramps and both seam crossings reachable',geometry.reachable.every(Boolean));check('Gardens, hoop base and both nets collide',geometry.blocked.every(Boolean));
// The pointer-driven shoot path, plus deliberate miss without losing prior success.
await p.evaluate(()=>__WORLD_TEST__.park.begin('basketball',true));const aim=await p.evaluate(()=>__WORLD_TEST__.screenPoint(__WORLD_TEST__.park.hoop().mouth.x,__WORLD_TEST__.park.hoop().mouth.y));await p.mouse.move(aim.x,aim.y);await p.mouse.down();await p.mouse.up();await p.waitForFunction(()=>__WORLD_TEST__.park.pose==='basketball_ready'&&!!__WORLD_TEST__.park.flight);check('Basketball release returns to ready after its authored 150ms',true);await p.waitForFunction(()=>__WORLD_TEST__.park.progress.basketball===1);check('Real drag/release scores a basket',true);
await p.evaluate(()=>{const P=__WORLD_TEST__.park;P.aim=1;P.action();for(let i=0;i<120;i++)P.tick(1/60,false);});check('Basketball miss keeps completed baskets',await p.evaluate(()=>__WORLD_TEST__.park.progress.basketball===1));
await p.evaluate(()=>{const P=__WORLD_TEST__.park;P.aim=0;for(let n=0;n<2;n++){P.action();for(let i=0;i<120;i++)P.tick(1/60,false);}});check('Three baskets complete one bounded round',await p.evaluate(()=>__WORLD_TEST__.park.progress.completed.includes('basketball')));await p.screenshot({path:path.join(out,'02-basketball-complete.png')});
// Tennis still requires matching lane. A misplaced racket misses, early press queues safely.
await p.evaluate(()=>{const P=__WORLD_TEST__.park;P.begin('tennis',true);P.w.player.x=1245;P.action();for(let i=0;i<110;i++)P.tick(1/60,false);});check('Tennis misplaced racket re-serves without a return',await p.evaluate(()=>__WORLD_TEST__.park.progress.tennis===0));
for(let n=0;n<5;n++){await p.evaluate(()=>{const P=__WORLD_TEST__.park;P.w.player.x=P.incomingTarget.x-P.anchor('tennis_contact',0,0,1).x;});await p.locator('#enter').click();await p.evaluate(()=>{const P=__WORLD_TEST__.park;for(let i=0;i<130;i++)P.tick(1/60,false);});}check('Five aligned tennis returns complete',await p.evaluate(()=>__WORLD_TEST__.park.progress.completed.includes('tennis')));await p.screenshot({path:path.join(out,'03-tennis-complete.png')});
await p.evaluate(()=>__WORLD_TEST__.park.begin('volleyball',true));for(let n=0;n<3;n++){await p.locator('#enter').click();await p.evaluate(()=>{for(let i=0;i<85;i++)__WORLD_TEST__.park.tick(1/60,false);});check('Volleyball bump hands off to set '+n,await p.evaluate(()=>__WORLD_TEST__.park.volleyStage===1));await p.locator('#enter').click();check('Set hides external ball',await p.evaluate(()=>__WORLD_TEST__.park.ball.hidden));if(n===0)await p.screenshot({path:path.join(out,'04-volleyball-set.png')});await p.evaluate(()=>{for(let i=0;i<12;i++)__WORLD_TEST__.park.tick(1/60,false);});check('Set restores identical-sized ball',await p.evaluate(()=>{const P=__WORLD_TEST__.park;return P.volleyStage===2&&!P.ball.hidden&&Math.abs(P.ball.diameter-27.1082)<.001;}));await p.locator('#enter').click();await p.evaluate(()=>{for(let i=0;i<90;i++)__WORLD_TEST__.park.tick(1/60,false);});}check('Three bump-set-hit returns complete',await p.evaluate(()=>__WORLD_TEST__.park.progress.completed.includes('volleyball')));await p.screenshot({path:path.join(out,'05-volleyball-complete.png')});
// Registered anchors mirror as a single unit, never scale ball by pose artwork dimensions.
check('All ten state pivots and mirrored anchors match manifest',await p.evaluate(()=>UWSportsData.actions.frames.every(f=>{const P=__WORLD_TEST__.park,a=P.anchor(f.id,500,500,1,f.id==='volleyball_set'),m=P.anchor(f.id,500,500,-1,f.id==='volleyball_set');return !a||(Math.abs(a.x+m.x-1000)<.0001&&a.y===m.y&&Math.abs(a.logicalDiameter-(f.id.startsWith('basketball')?85:f.id.startsWith('tennis')?22.4:96.815))<.001);} )));
// Follow the collision graph using the same keyboard move routine (QA exposes no teleport through obstacles).
await p.evaluate(()=>__WORLD_TEST__.park.begin('bike',true));for(const [x,y] of [[280,220],[140,500],[570,665],[990,50]]){await p.evaluate(([x,y])=>{__WORLD_TEST__.place(x,y);__WORLD_TEST__.park.tick(.02,true);},[x,y]);}check('Bike gates and entrance finish route',await p.evaluate(()=>__WORLD_TEST__.park.progress.completed.includes('bike')));await p.screenshot({path:path.join(out,'06-bike.png')});
await p.evaluate(()=>__WORLD_TEST__.park.begin('skate',true));for(const [x,y] of [[1190,370],[1180,610]])await p.evaluate(([x,y])=>{__WORLD_TEST__.place(x,y);__WORLD_TEST__.park.tick(.02,true);},[x,y]);check('Both skate features finish, without airborne substitution',await p.evaluate(()=>__WORLD_TEST__.park.progress.completed.includes('skate')));await p.screenshot({path:path.join(out,'07-skate.png')});
check('Sports do not change wallet, ownership or wardrobe',await p.evaluate(original=>JSON.stringify(__WORLD_TEST__.service.value)===original,original));await p.reload();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);check('All five completed activities survive reload',await p.evaluate(()=>__WORLD_TEST__.park.progress.completed.length===5));
await p.evaluate(()=>__WORLD_TEST__.park.begin('volleyball',true));await p.setViewportSize({width:393,height:852});await p.waitForFunction(()=>__WORLD_TEST__.snapshot().portrait);const age=await p.evaluate(()=>__WORLD_TEST__.park.ball.age);await p.waitForTimeout(300);check('Portrait gate suspends sports simulation',await p.evaluate(a=>__WORLD_TEST__.snapshot().portrait&&Math.abs(__WORLD_TEST__.park.ball.age-a)<.05,age));await p.setViewportSize({width:568,height:320});await p.waitForTimeout(100);check('Small landscape controls have 44px targets and no overlap',await p.evaluate(()=>{const ids=['scene-back','wallet','backpack','world-sound','enter','sports-progress'],r=ids.map(id=>document.getElementById(id).getBoundingClientRect());return r.every(a=>a.width>=44&&a.height>=44&&a.left>=0&&a.right<=innerWidth&&a.top>=0&&a.bottom<=innerHeight)&&r.every((a,i)=>r.every((b,j)=>i===j||a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top));}));await p.screenshot({path:path.join(out,'08-small-landscape.png')});check('No browser errors',errors.length===0);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,geometry,errors},null,2));console.log(JSON.stringify({passed:checks.length,geometry,output:out},null,2));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
