/* Disposable browser profiles only. Real game renderer; deterministic clocks for rally boundaries. */
const {chromium}=require('/Users/deanguedo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('node:assert/strict'),fs=require('node:fs');const out=process.env.SPORTS_QA_OUTPUT||'/tmp/unicorn-pong-qa';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{const p=await b.newPage({viewport:{width:932,height:430}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.SPORTS_QA_URL||'http://localhost:8890/hub/')+'?qa=1');await p.waitForFunction(()=>__WORLD_TEST__?.snapshot().loaded);await p.evaluate(()=>__WORLD_TEST__.navigate('park'));await p.waitForFunction(()=>__WORLD_TEST__.park.ready);const original=await p.evaluate(()=>JSON.stringify(__WORLD_TEST__.service.value));await p.evaluate(()=>Object.defineProperty(document,'hidden',{get:()=>true,configurable:true}));const check=async(name,fn)=>{assert.ok(await p.evaluate(fn),name);checks.push(name)};
await check('Wider bush ring and direct court doorways stay walkable',()=>{const P=__WORLD_TEST__.park;return [[930,1249],[590,1610],[940,1610],[768,2340],[650,2350],[488,2390]].every(([x,y])=>P.walkable(x,y))&&!P.walkable(768,1249)&&!P.walkable(770,2600)});
await check('Volleyball entry avoids the outside lap',()=>{const Q=__WORLD_TEST__;Q.place(768,2280);const path=Q.planRoute({x:488,y:2580});let a=Q.snapshot().player,d=0;for(const q of path){d+=Math.hypot(q.x-a.x,q.y-a.y);a=q;}return path.length&&d<650});
await check('Court buttons work immediately on the entry aprons',()=>{const P=__WORLD_TEST__.park;P.stop();return P.focus({x:590,y:1610})?.id==='basketball'&&P.focus({x:940,y:1610})?.id==='tennis'&&P.focus({x:768,y:2340})?.id==='volleyball'});for(const id of ['tennis','volleyball']){await p.evaluate(id=>window.__sportsMode=id,id);await check('One opening serve, then automatic returns: '+id,()=>{const P=__WORLD_TEST__.park,id=__sportsMode;P.begin(id,true);if(P.ball.phase!=='waiting')return false;P.action();if(id==='tennis')P.w.player.x=P.ball.target.x-P.anchor('tennis_contact',0,0,1).x;else P.w.player.y=P.incomingTarget.y;for(let i=0;i<110;i++)P.tick(1/60,false);return P.ball.phase==='out'});
await check('Three points unlock next opponent: '+id,()=>{const P=__WORLD_TEST__.park,id=__sportsMode;P.begin(id,true);P.action();for(let i=0;i<18000&&!P.progress.completed.includes(id);i++){if(P.ball?.phase==='in'){if(id==='tennis')P.w.player.x=P.ball.target.x-P.anchor('tennis_contact',0,0,1).x;else P.w.player.y=P.incomingTarget.y;}P.tick(1/60,false);}return P.progress[id]===3&&P.ladder[id].unlocked===1&&P.ladder[id].wins.includes(0)});
await check('Every difficulty has faster ball and stronger opponent: '+id,()=>{const P=__WORLD_TEST__.park,id=__sportsMode,values=[];for(let level=0;level<3;level++){P.ladder[id].level=level;P.begin(id,true);values.push(P.ball.duration);}P.ladder[id].level=0;return values[0]>values[1]&&values[1]>values[2]});
for(let level=1;level<=2;level++){await p.evaluate(level=>window.__sportsLevel=level,level);await check('Challenger can be beaten with edge returns: '+id+' '+level,()=>{const P=__WORLD_TEST__.park,id=__sportsMode;P.ladder[id].level=__sportsLevel;P.begin(id,true);P.action();for(let i=0;i<30000&&!P.progress.completed.includes(id)&&!P.matchOver;i++){if(P.ball?.phase==='in'){if(id==='tennis'){const body=P.ball.target.x-P.anchor('tennis_contact',0,0,1).x;P.w.player.x=Math.max(985,Math.min(1305,body+(P.opponent.x<1143?-32:32)));}else P.w.player.y=Math.max(2430,Math.min(2700,P.incomingTarget.y+(P.opponent.y<2580?-32:32)));}P.tick(1/60,false);}return P.progress[id]===3&&P.ladder[id].wins.includes(__sportsLevel)});await p.evaluate(()=>{const Q=__WORLD_TEST__,P=Q.park;Q.place(P.w.player.x,P.w.player.y);P.w.draw();});await p.screenshot({path:out+'/'+id+'-level-'+level+'.png'});}
await check('Missing returns lose a bounded match: '+id,()=>{const P=__WORLD_TEST__.park,id=__sportsMode;P.begin(id,true);P.action();for(let i=0;i<900;i++)P.tick(1/60,false);return P.matchOver&&P.opponentScores[id]===3});}
await check('Basketball needs current spot and power, then changes spot',()=>{const P=__WORLD_TEST__.park;P.begin('basketball',true);P.w.player.y=1460;P.charge=.65;P.aimCursor=0;P.action();P.tick(.19,false);P.tick(.16,false);if(!P.flight||P.pose!==null)return false;for(let i=0;i<120;i++)P.tick(1/60,false);return P.progress.basketball===1});
await check('Wrong spot produces a collectable miss',()=>{const P=__WORLD_TEST__.park;P.aimCursor=0;P.charge=.65;P.action();for(let i=0;i<140;i++)P.tick(1/60,false);return P.progress.basketball===1&&P.ball.phase==='loose'});
await check('Walking to missed basketball retrieves it',()=>{const P=__WORLD_TEST__.park;Object.assign(P.w.player,{x:P.ball.x,y:P.ball.y});P.tick(.02,true);return !P.ball&&P.pose==='basketball_ready'});
assert.equal(await p.evaluate(()=>JSON.stringify(__WORLD_TEST__.service.value)),original);checks.push('Wallet, equipment and wardrobe remain unchanged');await p.reload();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded&&__WORLD_TEST__.park.ready);await check('Ladder unlocks and wins survive reload',()=>['tennis','volleyball'].every(id=>__WORLD_TEST__.park.ladder[id].unlocked===2&&__WORLD_TEST__.park.ladder[id].wins.includes(2)));
// Real touch-style hold/release; no artificial shot offset.
await p.evaluate(()=>{const Q=__WORLD_TEST__;Q.park.begin('basketball',true);Q.place(359,1460);});const button=await p.locator('#enter').boundingBox();await p.mouse.move(button.x+button.width/2,button.y+button.height/2);await p.mouse.down();await p.waitForTimeout(900);assert.ok(await p.evaluate(()=>__WORLD_TEST__.park.charging));await p.screenshot({path:out+'/basketball-power-meter.png'});await p.mouse.up();await p.waitForFunction(()=>!!__WORLD_TEST__.park.flight);assert.equal(await p.evaluate(()=>__WORLD_TEST__.park.pose),null);checks.push('Actual button hold/release launches an intact-avatar shot');await p.screenshot({path:out+'/basketball-power-flight.png'});
await p.evaluate(()=>__WORLD_TEST__.park.begin('tennis',true));await p.setViewportSize({width:568,height:320});await p.waitForTimeout(100);assert.ok(await p.evaluate(()=>{const ids=['scene-back','wallet','backpack','world-sound','enter','sports-progress'],r=ids.map(id=>document.getElementById(id).getBoundingClientRect()).concat([...document.querySelectorAll('#sports-levels button')].map(e=>e.getBoundingClientRect()));return r.every(a=>a.width>=44&&a.height>=44&&a.left>=0&&a.right<=innerWidth&&a.top>=0&&a.bottom<=innerHeight)&&r.every((a,i)=>r.every((b,j)=>i===j||a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top));}));checks.push('Opponent cards and controls fit small landscape without overlap');await p.screenshot({path:out+'/small-landscape-ladder.png'});assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));console.log({passed:checks.length,errors});}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
