const {chromium}=require('/Users/deanguedo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('node:assert/strict'),fs=require('node:fs');const out=process.env.SPORTS_QA_OUTPUT||'/tmp/unicorn-sports-upgrade';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{const p=await b.newPage({viewport:{width:932,height:430}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.SPORTS_QA_URL||'http://localhost:8890/hub/')+'?qa=1');await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded);
for(const scene of ['village','mall','boutique','wheels','arcade','park']){await p.evaluate(s=>__WORLD_TEST__.navigate(s),scene);await p.waitForFunction(s=>__WORLD_TEST__.snapshot().scene===s&&__WORLD_TEST__.snapshot().loaded&&(s!=='park'||__WORLD_TEST__.park.ready),scene);const paths=await p.evaluate(()=>{const Q=__WORLD_TEST__,start=Q.snapshot().player;return Q.doors.map(d=>{const goal=Q.snapshot().scene==='park'?{x:d.x,y:d.y}:UWPortals.approach(d),path=Q.planRoute(goal);let a=start;const valid=path.every(b=>{const n=Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/4);for(let i=0;i<=n;i++)if(!Q.walkable(a.x+(b.x-a.x)*i/Math.max(n,1),a.y+(b.y-a.y)*i/Math.max(n,1)))return false;a=b;return true});return {id:d.id,waypoints:path.length,valid};});});assert.ok(paths.every(q=>q.waypoints&&q.valid),scene+JSON.stringify(paths));checks.push('Collision-safe routes to every entrance: '+scene);}
const routes=await p.evaluate(()=>{const Q=__WORLD_TEST__,points=[[190,220],[155,350],[180,565],[550,655],[685,615],[860,780],[935,225],[1390,660],[125,1300],[600,1350],[645,1580],[665,1210],[768,1160],[768,1330],[488,2340],[735,2380],[805,2380],[488,2760],[100,2848]];return points.map(([x,y])=>{const walkable=Q.walkable(x,y),route=walkable?Q.planRoute({x,y}):[];let a=Q.snapshot().player,d=0,valid=route.length>0;for(const b of route){const n=Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/2);for(let i=0;i<=n;i++)if(!Q.walkable(a.x+(b.x-a.x)*i/Math.max(1,n),a.y+(b.y-a.y)*i/Math.max(1,n)))valid=false;d+=Math.hypot(b.x-a.x,b.y-a.y);a=b;}return{x,y,walkable,valid,d};});});assert.ok(routes.every(r=>r.walkable&&r.valid),JSON.stringify(routes));checks.push('19 painted track edges, garden approaches, court aprons and net-end routes remain accessible');
assert.ok(await p.evaluate(()=>[1024,2048].every(y=>[720,768,820,850].every(x=>__WORLD_TEST__.walkable(x,y-1)&&__WORLD_TEST__.walkable(x,y)&&__WORLD_TEST__.walkable(x,y+1)))));checks.push('Both terrain seams have no one-pixel invisible wall');
const obstacles=await p.evaluate(()=>[[455,400],[768,1249],[359,1269],[1150,1469],[768,2600]].every(([x,y])=>!__WORLD_TEST__.walkable(x,y)));assert.ok(obstacles);checks.push('Planted garden cores, hoop base and thin net footprints stay solid');
await p.evaluate(()=>__WORLD_TEST__.place(768,1100));const at=await p.evaluate(()=>__WORLD_TEST__.screenPoint(830,1330));await p.mouse.click(at.x,at.y);await p.waitForFunction(()=>{const q=__WORLD_TEST__.snapshot();return Math.hypot(q.player.x-830,q.player.y-1330)<12&&!q.target},null,{timeout:10000}).catch(async e=>{console.log('ROUTE FAILURE',await p.evaluate(()=>__WORLD_TEST__.snapshot()));await p.screenshot({path:out+'/route-failure.png'});throw e;});checks.push('Actual floor tap walks around middle garden');await p.evaluate(()=>__WORLD_TEST__.place(359,1616));await p.locator('#enter').click();await p.waitForFunction(()=>__WORLD_TEST__.park.mode==='basketball');checks.push('Arrived at court with working action button');
await p.setViewportSize({width:568,height:320});await p.waitForTimeout(100);assert.ok(await p.evaluate(()=>{const r=['scene-back','wallet','backpack','world-sound','enter','sports-progress'].map(id=>document.getElementById(id).getBoundingClientRect());return r.every(a=>a.width>=44&&a.height>=44&&a.left>=0&&a.right<=innerWidth&&a.top>=0&&a.bottom<=innerHeight)&&r.every((a,i)=>r.every((b,j)=>i===j||a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top));}));checks.push('Small landscape controls fit, have 44px targets and do not overlap');await p.screenshot({path:out+'/small-landscape.png'});
await p.evaluate(async()=>{const Q=__WORLD_TEST__;Q.park.stop();await Q.service.run('earn',{game:'cafe',event:{id:'qa-sports-fresh-credit',kind:'import',coins:30}},'qa-sports-owned-funding');await Q.service.run('buy',{item:'skateboard',equip:true},'qa-sports-owned-purchase');});const owned=await p.evaluate(()=>__WORLD_TEST__.service.value);assert.equal(owned.vehicle,'skateboard');assert.ok(owned.owned.includes('skateboard'));await p.evaluate(()=>{__WORLD_TEST__.place(1180,610);__WORLD_TEST__.park.w.draw();});await p.screenshot({path:out+'/owned-skateboard.png'});await p.reload();await p.waitForFunction(()=>__WORLD_TEST__.snapshot().loaded&&__WORLD_TEST__.park.ready);assert.deepEqual(await p.evaluate(()=>__WORLD_TEST__.service.value),owned);assert.equal(await p.evaluate(()=>__WORLD_TEST__.park.mode),null);checks.push('Owned equipped skateboard persists with no forced activity');
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/navigation-results.json',JSON.stringify({checks,errors},null,2));console.log({checks:checks.length,errors});}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
