/* Connected Unicorn World. Native game saves remain owned by their games. */
(()=>{'use strict';const $=id=>document.getElementById(id),canvas=$('scene'),ctx=canvas.getContext('2d'),A=UWArt,C=UWCatalog,N=UWPortals;
const params=new URLSearchParams(location.search),qa=params.get('qa')==='1',legacy=params.get('legacy')==='1',STORE='unicorn-world-hub-v1';
const service=new UWProfile.Profile(),frames=new Map(),images={},keys=new Set(),player={x:830,y:620,facing:1};
let scene='village',scale=1,ox=0,oy=0,dpr=1,last=0,time=0,drag=null,target=null,route=[],focused=null,active=null,loaded=false,moving=false,portrait=false,returning=false,panelOpen=false,lastPersist=0,panelPausePromise=null,panelPauseResolve=null,navGeneration=0;
const park=new UWSportsPark({player,service,canvas,announce,draw,clear,equipment:()=>{mall.bagTab="equipment";mall.open("backpack");}});
const villageDoors=[{id:'cafe',x:518,y:495,r:114,spawn:{x:590,y:620},picture:'pizza',hit:{x:430,y:305,w:170,h:225}},{id:'adventure',x:1290,y:512,r:114,spawn:{x:1190,y:655},picture:'room_door',hit:{x:1200,y:235,w:220,h:310}},{id:'mall',x:840,y:430,r:95,picture:'bag',hit:{x:750,y:355,w:180,h:140}},{id:'park',x:1205,y:880,r:75,approachOffset:-45,picture:'wheel'}];
const scenes={
 park:{w:768,h:512,outdoor:true,spawn:{x:768,y:200}},
 village:{w:1672,h:941,outdoor:true,spawn:{x:830,y:620}},
 mall:{w:1536,h:1024,image:'mall',spawn:{x:768,y:810},doors:[{id:'boutique',x:225,y:465,r:110,picture:'hanger'},{id:'wheels',x:588,y:465,r:110,picture:'wheel'},{id:'arcade',x:955,y:465,r:110,picture:'pins'},{id:'take-photo',x:1310,y:465,r:110,picture:'camera'}]},
 boutique:{w:1536,h:1024,image:'boutique',spawn:{x:765,y:810},doors:[{id:'shop',x:240,y:535,r:110,picture:'hanger'},{id:'closet',x:700,y:445,r:110,picture:'mirror'}]},
 wheels:{w:1536,h:1024,image:'wheels',spawn:{x:768,y:810},doors:[{id:'wheel-shop',x:760,y:490,r:120,picture:'wheel'},{id:'track',x:1150,y:715,r:110,picture:'play'}]},
 track:{w:1536,h:1024,image:'wheels',outdoor:true,spawn:{x:700,y:835},doors:[{id:'test-ride',x:520,y:625,r:110,picture:'wheel'}]},
 arcade:{w:1536,h:1024,image:'arcade',spawn:{x:768,y:810},doors:[{id:'catcher',x:260,y:530,r:115,picture:'basket'},{id:'bowling',x:740,y:530,r:115,picture:'pins'},{id:'jigsaws',x:1215,y:535,r:115,picture:'puzzle'},{id:'prizes',x:1310,y:745,r:100,picture:'star'}]},
};
const parents={park:'village',mall:'village',boutique:'mall',wheels:'mall',track:'wheels',arcade:'mall'};
const exitLatch=N.latch();
function exitArea(){if(scene==='park')return park.mode?null:{id:'exit',exit:true,x:990,y:50,rx:90,ry:60,to:'village',picture:'home'};if(!parents[scene])return null;return {id:'exit',exit:true,x:245,y:890,rx:150,ry:78,to:parents[scene],picture:parents[scene]==='village'?'home':parents[scene]==='boutique'?'hanger':parents[scene]==='wheels'?'wheel':'bag',builtInDoor:scene==='wheels'||scene==='track'};}
const obstacles=[{x:0,y:0,w:744,h:455},{x:1030,y:0,w:642,h:475},{x:720,y:0,w:350,h:380},{x:192,y:658,w:260,h:162},{ellipse:true,x:842,y:865,rx:260,ry:170},{x:0,y:0,w:68,h:941},{x:1602,y:0,w:70,h:941},{x:1380,y:635,w:292,h:310},{ellipse:true,x:220,y:590,rx:300,ry:65},{ellipse:true,x:1550,y:570,rx:175,ry:80},{x:0,y:730,w:185,h:211}];
const doors=()=>scene==='park'?park.stations():scene==='village'?villageDoors:scenes[scene].doors||[];
function walkable(x,y){if(scene==='park')return park.walkable(x,y);if(scene!=='village')return x>=90&&x<=1446&&y>=435&&y<=955;
 if(x<90||x>1580||y<415||y>905)return false;return !obstacles.some(o=>o.ellipse?((x-o.x)/(o.rx+18))**2+((y-o.y)/(o.ry+18))**2<1:x>o.x-19&&x<o.x+o.w+19&&y>o.y-15&&y<o.y+o.h+15);}
try{const s=JSON.parse(localStorage.getItem(STORE)||'null');if(s?.version===1){scene=({street:'mall',fitting:'boutique',photo:'mall'})[s.scene]||(scenes[s.scene]?s.scene:'village');if(walkable(s.x,s.y))Object.assign(player,{x:s.x,y:s.y,facing:s.facing===-1?-1:1});else Object.assign(player,scenes[scene].spawn);}}catch(_){}
function persist(){try{localStorage.setItem(STORE,JSON.stringify({version:1,scene,x:player.x,y:player.y,facing:player.facing,visited:[...frames.keys()]}));}catch(_){}}
function clear(){park.cancel();keys.clear();target=null;route=[];if(drag){try{canvas.releasePointerCapture(drag.id);}catch(_){}drag=null;}moving=false;exitLatch.reset(player,exitArea());}
function resize(){const r=canvas.getBoundingClientRect(),spec=scenes[scene];dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);scale=Math.min(r.width/spec.w,r.height/spec.h);ox=(r.width-spec.w*scale)/2;oy=(r.height-spec.h*scale)/2;const before=portrait;portrait=innerHeight>innerWidth;if(active&&portrait!==before)send(frames.get(active),portrait?'suspend':panelOpen?'suspend':'resume');$('rotate').hidden=!portrait;if(portrait!==before)mall.cancelControls();clear();last=0;}
function point(e){const r=canvas.getBoundingClientRect(),camera=scene==='park'?park.view():{x:0,y:0};return{x:(e.clientX-r.left-ox)/scale+camera.x,y:(e.clientY-r.top-oy)/scale+camera.y};}
function ride(){if(!scenes[scene].outdoor)return null;if(scene==='track'&&mall.trialVehicle)return mall.trialVehicle;return service.value.owned.includes(service.value.vehicle)?service.value.vehicle:null;}
function clearLine(a,b){const n=Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/8);for(let i=0;i<=n;i++)if(!walkable(a.x+(b.x-a.x)*i/Math.max(n,1),a.y+(b.y-a.y)*i/Math.max(n,1)))return false;return true;}
// Route floor taps around scenery; every segment still obeys the same collision map.
function planRoute(goal){
 const start={x:player.x,y:player.y},step=24,w=scene==='park'?1536:scenes[scene].w,h=scene==='park'?3072:scenes[scene].h;
 if(clearLine(start,goal))return [goal];
 const nearest=p=>{let best=null,d=Infinity;const cx=Math.round(p.x/step),cy=Math.round(p.y/step);for(let y=cy-4;y<=cy+4;y++)for(let x=cx-4;x<=cx+4;x++){const q={x:x*step,y:y*step},v=Math.hypot(q.x-p.x,q.y-p.y);if(v<d&&walkable(q.x,q.y)&&clearLine(p,q)){best={...q,key:x+','+y,gx:x,gy:y};d=v;}}return best;};
 const first=nearest(start),last=nearest(goal);if(!first||!last)return [];
 const open=[{...first,g:0,f:Math.hypot(first.x-last.x,first.y-last.y)}],cost=new Map([[first.key,0]]),parents=new Map(),closed=new Set();let end=null;
 while(open.length){let i=0;for(let j=1;j<open.length;j++)if(open[j].f<open[i].f)i=j;const n=open.splice(i,1)[0];if(closed.has(n.key))continue;if(n.key===last.key){end=n;break;}closed.add(n.key);
  for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const gx=n.gx+dx,gy=n.gy+dy,q={x:gx*step,y:gy*step,gx,gy,key:gx+','+gy};if(q.x<0||q.y<0||q.x>w||q.y>h||closed.has(q.key)||!clearLine(n,q))continue;const g=n.g+Math.hypot(dx,dy)*step;if(g>=(cost.get(q.key)??Infinity))continue;cost.set(q.key,g);parents.set(q.key,n);open.push({...q,g,f:g+Math.hypot(q.x-last.x,q.y-last.y)});}
 }
 if(!end)return [];const points=[goal];for(let n=end;n;n=parents.get(n.key))points.unshift({x:n.x,y:n.y});const smooth=[];let a=start,index=0;while(index<points.length){let next=index;while(next+1<points.length&&clearLine(a,points[next+1]))next++;smooth.push(points[next]);a=points[next];index=next+1;}return smooth;
}
function setDestination(p){route=scene==='park'&&park.mode?[p]:planRoute(p);target=route.length?p:null;}
function move(dx,dy,dt){if(scene==='park'){const result=park.move(dx,dy,dt);if(result!==null)return result;}const len=Math.hypot(dx,dy);if(len<.08)return false;const before={...player},step=(scene==='park'?180:292)*dt*Math.min(1,len)*(C.speed[ride()]||1);dx=dx/len*step;dy=dy/len*step;if(walkable(player.x+dx,player.y+dy)){player.x+=dx;player.y+=dy;}else{if(walkable(player.x+dx,player.y))player.x+=dx;if(walkable(player.x,player.y+dy))player.y+=dy;}if(Math.abs(dx)>.3)player.facing=dx<0?-1:1;return Math.hypot(player.x-before.x,player.y-before.y)>.1;}
function focusDoor(){const exit=exitArea(),next=scene==='park'?park.focus(player):exit&&N.contains(exit,player)?exit:doors().filter(d=>N.contains(N.approach(d),player)).sort((a,b)=>N.distance(N.approach(a),player)-N.distance(N.approach(b),player))[0]||null;focused=next;$('enter').disabled=!focused||!!active||panelOpen||!!park.loading;$('enter').setAttribute('aria-label',focused?.exit?'Leave this place':focused?'Enter or use '+focused.id:'Approach a door or activity');$('destination').hidden=!focused;const control=$('enter').querySelector('.picture-sprite');if(control)control.src=scene==='park'&&park.mode?park.actionURL():A.iconURL('door');if(focused){if(scene==='park'&&!focused.exit)$('destination').src=park.iconFor(focused.id);else if(images[focused.picture])$('destination').src=images[focused.picture].src;else $('destination').src=A.iconURL(focused.picture);}}
function navigate(id){const ticket=++navGeneration;id=({street:'mall',fitting:'boutique',photo:'mall'})[id]||id;if(!scenes[id])return;if(id==='park'&&!park.ready){announce('Loading the sports park.');park.load().then(()=>{if(ticket===navGeneration&&!active&&!panelOpen)navigate('park');}).catch(()=>announce('Sports artwork could not load. Press the entrance picture to retry.'));return;}const from=scene;if(scene==='park')park.leaveWorld();mall.leaveScene(scene,id);scene=id;Object.assign(player,id==='village'&&from==='park'?{x:1205,y:875}:scenes[id].spawn);clear();focused=null;$('scene-back').hidden=id==='village';resize();focusDoor();persist();draw();}
function back(){if(scene==='park'&&park.mode&&!panelOpen){park.stop();clear();focusDoor();draw();return;}if(panelOpen)return mall.close();if(active)return returnHome();navigate(parents[scene]||'village');}
function urlFor(id){let url;if(legacy&&['localhost','127.0.0.1'].includes(location.hostname))url=new URL(id==='cafe'?'http://localhost:8787/':'http://127.0.0.1:8788/');else url=new URL(id==='cafe'?'../game/build/':'../adventure/',location.href);url.searchParams.set('worldOrigin',location.origin);url.searchParams.set('worldBase',new URL('../',location.href).href);url.searchParams.set('hub','1');if(qa)url.searchParams.set('qa','1');return url;}
function send(frame,command){frame?.node.contentWindow?.postMessage({type:'UNICORN_WORLD',command},frame.origin);}
function profileTo(frame){frame.node.contentWindow?.postMessage({type:'UNICORN_PROFILE',command:'snapshot',profile:service.public()},frame.origin);}
function enter(){if(!loaded||active||!focused||portrait||panelOpen||returning)return;clear();if(focused.exit)return navigate(focused.to);const id=focused.id;if(scene==='park'){if(focused.exit)return navigate('village');if(park.mode)park.action();else park.begin(id);clear();focusDoor();persist();draw();return;}if(scenes[id])return navigate(id);if(!['cafe','adventure'].includes(id)){mall.open(id);return;}
 active=id;persist();$('world').hidden=true;$('game-shell').hidden=false;$('loading').hidden=false;let f=frames.get(id);if(!f){const url=urlFor(id),node=document.createElement('iframe');node.title=id==='cafe'?'Rainbow Restaurant':'Sneaky Unicorn adventure';node.setAttribute('allow','autoplay');node.src=url.href;f={node,origin:url.origin,ready:false};frames.set(id,f);$('frames').append(node);}
 for(const[key,frame]of frames)frame.node.hidden=key!==id;if(f.ready){$('loading').hidden=true;send(f,'resume');f.node.contentWindow.focus();}$('enter').disabled=true;
}
function finishReturn(){const d=villageDoors.find(d=>d.id===active);if(!d)return;active=null;returning=false;$('return').disabled=false;for(const f of frames.values())f.node.hidden=true;$('game-shell').hidden=true;$('world').hidden=false;scene='village';Object.assign(player,d.spawn);$('scene-back').hidden=true;clear();resize();focusDoor();persist();canvas.focus({preventScroll:true});}
function returnHome(){if(!active||returning||panelOpen)return;const f=frames.get(active);if(!f.ready){f.node.remove();frames.delete(active);finishReturn();return;}returning=true;$('return').disabled=true;send(f,'suspend');setTimeout(()=>{if(returning){returning=false;$('return').disabled=false;announce('The game has not confirmed its pause. Try returning again.');}},2500);}
function announce(text){$('announcement').textContent=text;}
window.addEventListener('message',async e=>{const match=[...frames.entries()].find(([,f])=>e.source===f.node.contentWindow&&e.origin===f.origin);if(!match)return;const[id,f]=match;
 if(e.data?.type==='UNICORN_WORLD'&&e.data.command==='return'){if(active===id&&!portrait&&!document.hidden)returnHome();return;}
 if(e.data?.type==='UNICORN_WORLD_ACK'){
  if(e.data.command==='ready'){f.ready=true;profileTo(f);if(active===id){$('loading').hidden=true;send(f,portrait||panelOpen?'suspend':'resume');f.node.contentWindow.focus();}else send(f,'suspend');}
  if(e.data.command==='suspend'&&active===id){if(returning)finishReturn();if(panelPauseResolve){panelPauseResolve();panelPauseResolve=null;panelPausePromise=null;}}return;
 }
 if(e.data?.type!=='UNICORN_PROFILE')return;
 if(e.data.command==='connect'){profileTo(f);return;}
 if(e.data.command==='request'){
  const {id:requestId,action,args}=e.data;if(!['buy','equip'].includes(action)||typeof requestId!=='string'||requestId.length>240)return;
  try{const r=await service.run(action,args,requestId);f.node.contentWindow?.postMessage({type:'UNICORN_PROFILE',command:'receipt',id:requestId,ok:true,value:r.value},f.origin);}
  catch(err){if(['coins','owned','invalid','missing'].includes(err.code))f.node.contentWindow?.postMessage({type:'UNICORN_PROFILE',command:'receipt',id:requestId,ok:false,error:err.code},f.origin);else announce('Your change is waiting to save.');}return;
 }
 if(e.data.command==='earn'){const event=e.data.event;try{await service.run('earn',{game:id,event},id==='cafe'&&event?.kind==='import'?'import:cafe':event?.id);f.node.contentWindow?.postMessage({type:'UNICORN_PROFILE',command:'receipt',id:event.id},f.origin);}catch(err){announce('World earnings are waiting to save.');}}
});
canvas.addEventListener('pointerdown',e=>{if(!loaded||active||portrait||panelOpen||drag||e.button>0)return;e.preventDefault();canvas.focus();const p=point(e);if(scene==='park'&&park.down(e,p))return;drag={id:e.pointerId,x:p.x,y:p.y,viewX:p.x-(scene==='park'?park.view().x:0),viewY:p.y-(scene==='park'?park.view().y:0),dx:0,dy:0,max:0};target=null;route=[];canvas.setPointerCapture(e.pointerId);$('guide').classList.remove('show');});
canvas.addEventListener('pointermove',e=>{if(scene==='park'&&park.pointerMove(e,point(e)))return;if(drag?.id!==e.pointerId)return;const p=point(e);drag.dx=scene==='park'?p.x-park.view().x-drag.viewX:p.x-drag.x;drag.dy=scene==='park'?p.y-park.view().y-drag.viewY:p.y-drag.y;drag.max=Math.max(drag.max,Math.hypot(drag.dx,drag.dy));});
function end(e,cancel=false){if(scene==='park'&&park.up(e,point(e),cancel))return;if(drag?.id!==e.pointerId)return;const tap=drag.max<9,p=point(e);drag=null;try{canvas.releasePointerCapture(e.pointerId);}catch(_){}if(tap&&!cancel){const exit=exitArea(),d=exit&&N.hit(exit,p)?exit:doors().find(d=>N.hit(d,p));if(d)setDestination(d.exit||scene==='park'?{x:d.x,y:d.y}:N.approach(d));else if(walkable(p.x,p.y))setDestination(p);}persist();}
canvas.addEventListener('pointerup',e=>end(e));canvas.addEventListener('pointercancel',e=>end(e,true));canvas.addEventListener('lostpointercapture',()=>{drag=null;park.cancel();});canvas.addEventListener('contextmenu',e=>e.preventDefault());
$('enter').onclick=enter;for(const id of ['return','backpack','world-sound'])$(id).addEventListener('pointerdown',e=>e.preventDefault());$('return').onclick=returnHome;$('scene-back').onclick=back;$('backpack').onclick=()=>mall.open('backpack');$('world-sound').onclick=()=>mall.toggleSound();
window.addEventListener('keydown',e=>{if(e.key==='Escape'){back();return;}if(active||portrait||panelOpen)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Enter','w','a','s','d'].includes(e.key)){if(e.target.tagName==='BUTTON'&&[' ','Enter'].includes(e.key))return;e.preventDefault();if([' ','Enter'].includes(e.key)){if(!e.repeat)enter();}else{keys.add(e.key.toLowerCase());target=null;route=[];}}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
window.addEventListener('blur',clear);window.addEventListener('resize',resize);window.addEventListener('pagehide',()=>{persist();mall.saveRound();});
document.addEventListener('visibilitychange',()=>{clear();persist();last=0;mall.cancelControls();if(active)send(frames.get(active),document.hidden||panelOpen||portrait?'suspend':'resume');});
let groundPatch=null,borderPatch=null;
function ground(){if(!groundPatch){groundPatch=document.createElement('canvas');groundPatch.width=340;groundPatch.height=300;const p=groundPatch.getContext('2d');p.drawImage(images.village,1000,580,280,170,0,0,340,300);p.globalCompositeOperation='destination-in';const mask=p.createRadialGradient(170,150,122,170,150,150);mask.addColorStop(0,'#000');mask.addColorStop(1,'#0000');p.fillStyle=mask;p.fillRect(0,0,340,300);}ctx.drawImage(groundPatch,665,350);
 if(!borderPatch){borderPatch=document.createElement('canvas');borderPatch.width=360;borderPatch.height=360;const b=borderPatch.getContext('2d');b.drawImage(images.village,0,640,210,301,0,0,360,360);b.globalCompositeOperation='destination-in';const fade=b.createRadialGradient(180,180,148,180,180,180);fade.addColorStop(0,'#000');fade.addColorStop(1,'#0000');b.fillStyle=fade;b.fillRect(0,0,360,360);}ctx.drawImage(borderPatch,1355,585);
 // Open only the previously reserved expansion route; originals stay intact.
}
function draw(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#503a63';ctx.fillRect(0,0,canvas.width/dpr,canvas.height/dpr);ctx.translate(ox,oy);ctx.scale(scale,scale);if(!loaded)return;if(scene==='park'){ctx.save();ctx.beginPath();ctx.rect(0,0,768,512);ctx.clip();park.draw(ctx,time,moving,mall.previewOutfit||service.value.outfit);const cam=park.view();ctx.save();ctx.translate(-cam.x,-cam.y);const exit=exitArea();if(exit)N.exit(ctx,exit,focused?.exit);if(target)A.ellipse(ctx,target.x,target.y,15,8,null,'#fff2c4',3);ctx.restore();if(drag&&drag.max>9){ctx.save();ctx.globalAlpha=.7;A.ellipse(ctx,drag.viewX,drag.viewY,38,38,null,'#fff4d8',3);A.ellipse(ctx,drag.viewX+Math.max(-28,Math.min(28,drag.dx)),drag.viewY+Math.max(-28,Math.min(28,drag.dy)),12,12,'#fff4d8',null);ctx.restore();}ctx.restore();return;}const spec=scenes[scene];ctx.drawImage(images[spec.image||'village'],0,0,spec.w,spec.h);if(scene==='village')ground();
 if(scene==='track'){ctx.save();ctx.strokeStyle='#fff0c4';ctx.lineWidth=7;ctx.setLineDash([24,14]);ctx.beginPath();ctx.ellipse(770,755,530,150,0,0,Math.PI*2);ctx.stroke();ctx.restore();}
 for(const d of doors())N.entrance(ctx,d,focused?.id===d.id,images);const exit=exitArea();if(exit)N.exit(ctx,exit,focused?.exit);
 if(target)A.ellipse(ctx,target.x,target.y,15,8,null,'#fff2c4',3);A.ellipse(ctx,player.x,player.y,38,12,'#62436835',null);
 const riding=ride(),frame=riding?riding+(moving?Math.floor(time*10)%4:0):moving?'u_run'+Math.floor(time*10)%6:'u_idle'+Math.floor(time*2)%2;
 A.unicorn(ctx,player.x,player.y,155,mall.previewOutfit||service.value.outfit,frame,player.facing<0,riding);
 if(drag&&drag.max>9){ctx.save();ctx.globalAlpha=.7;A.ellipse(ctx,drag.x,drag.y,38,38,null,'#fff4d8',3);A.ellipse(ctx,drag.x+Math.max(-28,Math.min(28,drag.dx)),drag.y+Math.max(-28,Math.min(28,drag.dy)),12,12,'#fff4d8',null);ctx.restore();}
}
function loop(ms){requestAnimationFrame(loop);const dt=last?Math.min(.04,(ms-last)/1000):0;last=ms;if(!loaded||active||portrait||panelOpen||document.hidden)return;time+=dt;let dx=0,dy=0;if(drag?.max>9){dx=drag.dx/55;dy=drag.dy/55;}else{dx=(keys.has('arrowright')||keys.has('d')?1:0)-(keys.has('arrowleft')||keys.has('a')?1:0);dy=(keys.has('arrowdown')||keys.has('s')?1:0)-(keys.has('arrowup')||keys.has('w')?1:0);}if(!dx&&!dy&&target){const next=route[0]||target,x=next.x-player.x,y=next.y-player.y,len=Math.hypot(x,y);if(len<(route.length>1?1.5:6)){route.shift();if(!route.length)target=null;}else{dx=x/len*Math.min(1,len/12);dy=y/len*Math.min(1,len/12);}}moving=move(dx,dy,dt);if(scene==='park')park.tick(dt,moving);if(target&&!moving&&dt>0&&route.length&&Math.hypot(route[0].x-player.x,route[0].y-player.y)>6){route=planRoute(target);if(!route.length)target=null;}const exit=exitArea();if(exit&&exitLatch.step(player,exit,dt,!moving))return navigate(exit.to);focusDoor();draw();if(time-lastPersist>1){persist();lastPersist=time;}}
const mall=new UWMall({service,canvas,images,scene:()=>scene,navigate,announce,draw,async setPanel(open){panelOpen=open;if(open)park.hud.hidden=true;clear();$('enter').hidden=open;$('world').inert=open;last=0;if(open&&active&&frames.get(active).ready){if(!panelPausePromise){panelPausePromise=new Promise(resolve=>{panelPauseResolve=resolve;send(frames.get(active),'suspend');setTimeout(()=>{if(panelPauseResolve){panelPauseResolve();panelPauseResolve=null;panelPausePromise=null;}},2500);});}await panelPausePromise;}$('frames').inert=open;if(!open&&active)send(frames.get(active),portrait?'suspend':'resume');}});
service.onChange(p=>{$('coin-count').textContent=p.coins;for(const f of frames.values())profileTo(f);mall.changed();draw();});
async function boot(){for(const[id,icon]of[['scene-back','back'],['backpack','bag'],['world-sound','sound'],['coin-picture','coin']])$(id).innerHTML=A.icon(icon);$('scene-back').hidden=scene==='village';
 try{await service.open();}catch(e){$('saving').hidden=false;$('saving').innerHTML=A.icon('save');$('saving').setAttribute('aria-label','World saving unavailable. Try reopening the world.');announce('World saving is unavailable. Existing games can still be played.');}
 try{const files={village:'./assets/village-concept.png',pizza:'../game/build/assets/pizza.webp',room_door:'../game/build/assets/room_door.webp',...Object.fromEntries(['mall','boutique','wheels','arcade','photo'].map(n=>[n,'./assets/mall/'+n+'.png']))};await Promise.all([A.load('../'),N.load(),...Object.entries(files).map(([key,src])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[key]=im;resolve();};im.onerror=()=>reject(Error(src));im.src=src;}))]);if(scene==='park')await park.load();loaded=true;mall.ready();resize();focusDoor();draw();$('enter').querySelector('.picture-sprite')?.remove();$('enter').querySelector('svg')?.remove();$('enter').insertAdjacentHTML('afterbegin',A.icon('door'));$('return').innerHTML=A.icon('home');$('guide').innerHTML=A.icon('hand')+A.icon('arrow');$('rotate').innerHTML=A.icon('rotate');$('guide').classList.add('show');setTimeout(()=>$('guide').classList.remove('show'),7000);}catch(e){announce('Artwork could not load. Reload to try again.');console.error(e);}}
if(qa)window.__WORLD_TEST__={snapshot:()=>({player:{...player},scene,focused:focused?.id,active,loaded,drag:!!drag,target,portrait,panel:panelOpen,exit:exitArea(),exitState:exitLatch.snapshot(),frames:[...frames].map(([id,f])=>({id,ready:f.ready})),keys:keys.size}),walkable,planRoute,setDestination,get doors(){return doors();},place(x,y){if(!walkable(x,y))throw Error('Blocked');Object.assign(player,{x,y});clear();focusDoor();draw();},enter,returnHome,navigate,service,mall,screenPoint:(x,y)=>({x:ox+(x-(scene==='park'?park.view().x:0))*scale,y:oy+(y-(scene==='park'?park.view().y:0))*scale}),park,urls:()=>villageDoors.filter(d=>['cafe','adventure'].includes(d.id)).map(d=>urlFor(d.id).href)};
resize();requestAnimationFrame(loop);boot();
})();
