/* Run: node tests/engine_tests.js. Tests use the actual packaged engine. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const R=require('../build/src/engine.js');const result=[];
function test(name,fn){try{const detail=fn();result.push({name,pass:true,detail});console.log('PASS',name);}catch(e){result.push({name,pass:false,error:e.stack});console.error('FAIL',name,e.stack);}}
function make(e,c,chosen=c.dish,v=c.variant,deco='rainbow'){
 assert(e.takeOrder(c.id));assert(e.startRecipe(c.id,chosen));
 while(!e.s.prep.done){let p=e.s.prep,st=R.RECIPES[p.dish].steps[p.step];assert(e.act(st.action==='choice'?v:st.action==='decorate'?deco:null,{x:.4,y:.6}).ok);}
 assert(e.packMeal());
}
function service(e,dish=null,variant=null){let c=e.spawn(5);assert(c);if(dish){c.dish=dish;c.variant=variant;}assert(e.arrive(c.id));make(e,c);assert(e.serve(c.table).ok);assert(e.finishEating(c.id));assert(e.startLeaving(c.id));assert(e.remove(c.id));assert(e.pickDirty(c.table));for(let i=0;i<5;i++)assert(e.washAct().ok);return c;}
function lunch(e){assert.equal(e.s.phase,'lunch');assert(!e.spawn(5));assert(!e.endLunch());assert(e.chooseLunch('pancakes'));for(let i=0;i<5;i++)assert(e.lunchAct());assert(!e.lunchAct());assert(e.endLunch());assert(!e.endLunch());assert.equal(e.s.phase,'afternoon');}
function close(e){assert.equal(e.s.phase,'cleaning');assert(!e.s.completed);for(const t of R.CLEAN_TASKS){for(let i=0;i<t.need;i++){let r=e.cleanAct(t.id);assert(r.ok);assert.equal(r.done,i===t.need-1);}}assert(e.s.completed);assert.equal(e.s.phase,'complete');}
test('All 18 recipe/variation combinations through dish return/wash',()=>{
 let count=0;for(const dish of R.MENU)for(const v of R.RECIPES[dish].variants){const e=new R.Engine();service(e,dish,v.id);assert.equal(e.s.tables[0].status,'clean');assert.equal(e.s.served,1);count++;}return {combinations:count};
});
test('Wrong flavour stays carried, remake preserves customer',()=>{const e=new R.Engine(),c=e.spawn(1);e.arrive(c.id);make(e,c,'pizza','mushroom');assert.equal(e.serve(c.table).reason,'variant');assert(e.s.tray);assert(e.remake());make(e,c);assert(e.serve(c.table).ok);});
test('Wrong dish and wrong table cannot eat or consume tray',()=>{const e=new R.Engine(),c=e.spawn(1);e.arrive(c.id);make(e,c,'soup','peas');assert.equal(e.serve(1).reason,'table');assert.equal(e.serve(c.table).reason,'dish');assert.equal(e.s.served,0);assert(e.s.tray);});
test('Every cupcake sprinkle choice is correct, also change when ready',()=>{for(const v of R.RECIPES.cupcake.variants)for(const deco of R.RECIPES.cupcake.decorations){const e=new R.Engine(),c=e.spawn(1);c.dish='cupcake';c.variant=v.id;e.arrive(c.id);e.takeOrder(c.id);e.startRecipe(c.id,'cupcake');while(!e.s.prep.done){const st=R.RECIPES.cupcake.steps[e.s.prep.step];e.act(st.action==='choice'?v.id:st.action==='decorate'?deco.id:null);}assert(e.redecorate('hearts'));assert(e.redecorate(deco.id));assert(!e.redecorate('wrong'));e.packMeal();assert(e.serve(0).ok);assert.equal(c.deco,deco.id);}return {cases:6};});
test('Halfway stops arrivals at FIVE, not mid-cooking or with abandoned guests',()=>{const e=new R.Engine();for(let i=0;i<4;i++)service(e);const c=e.spawn(1);e.arrive(c.id);make(e,c);assert.equal(e.s.phase,'morning');assert(!e.spawn(5));e.serve(0);e.updateDay();assert.equal(e.s.phase,'morning');e.finishEating(c.id);e.startLeaving(c.id);e.remove(c.id);assert.equal(e.s.phase,'morning');e.pickDirty(0);for(let i=0;i<5;i++)e.washAct();assert.equal(e.s.phase,'lunch');});
test('Full day = five guests, playable lunch, five more, surfaces then floors',()=>{const e=new R.Engine();for(let i=0;i<5;i++)service(e);lunch(e);for(let i=0;i<5;i++)service(e);assert.equal(e.s.served,10);assert.equal(e.s.stickers.length,9);assert(!e.cleanAct('floor-0').ok);close(e);assert(!e.spawn(5));assert(!e.cleanAct('floor-0').ok);return {guests:10,recipes:9,cleaningTasks:R.CLEAN_TASKS.length};});
test('Lunch save/reload after EVERY bite/sip, no duplicate lunch',()=>{let e=new R.Engine();for(let i=0;i<5;i++)service(e);e.chooseLunch('smoothie');for(let i=0;i<5;i++){e.lunchAct();const state=e.snapshot();e=new R.Engine(state);assert.deepEqual(e.s.lunch,state.lunch);assert.equal(e.s.phase,'lunch');}assert(e.endLunch());const saved=e.snapshot();e=new R.Engine(saved);assert(e.s.lunch.done);assert.equal(e.s.phase,'afternoon');assert(!e.chooseLunch('soup'));});
test('Final cleaning persists at each individual scrub and final state',()=>{let e=new R.Engine();for(let i=0;i<5;i++)service(e);lunch(e);for(let i=0;i<5;i++)service(e);let n=0;for(const t of R.CLEAN_TASKS){for(let j=0;j<t.need;j++){assert(e.cleanAct(t.id).ok);const p=e.s.cleaning.map(q=>q.p);e=new R.Engine(e.snapshot());assert.deepEqual(e.s.cleaning.map(q=>q.p),p);n++;}}assert(e.s.completed);return {savedStrokes:n};});
test('Closing waits for eating, guest exit, dish return AND all cleaning',()=>{const e=new R.Engine();for(let i=0;i<5;i++)service(e);lunch(e);for(let i=0;i<4;i++)service(e);const c=e.spawn(1);e.arrive(c.id);make(e,c);e.serve(0);e.updateDay();assert.equal(e.s.phase,'closing');assert.equal(e.cleanTargets().length,0);e.finishEating(c.id);e.startLeaving(c.id);e.pickDirty(0);for(let i=0;i<5;i++)e.washAct();assert.equal(e.s.phase,'closing');e.remove(c.id);assert.equal(e.s.phase,'cleaning');assert(!e.s.completed);});
test('Washed dish does not reappear on save/reload while guest leaves',()=>{const e=new R.Engine(),c=e.spawn(1);e.arrive(c.id);make(e,c);e.serve(0);e.finishEating(c.id);e.startLeaving(c.id);e.pickDirty(0);for(let i=0;i<5;i++)e.washAct();const f=new R.Engine(e.snapshot());assert.equal(f.s.tables[0].status,'clean');assert.equal(f.s.customers[0].phase,'leaving');assert(!f.s.dirtyTray);});
test('No replacement until dirty dish is actually returned and washed',()=>{const e=new R.Engine();const c=e.spawn(1);e.arrive(c.id);make(e,c);e.serve(0);e.finishEating(c.id);e.startLeaving(c.id);e.remove(c.id);assert.notEqual(e.freeTable(),0);e.pickDirty(0);assert.notEqual(e.freeTable(),0);for(let i=0;i<4;i++)e.washAct();assert.notEqual(e.freeTable(),0);e.washAct();assert.equal(e.freeTable(),0);});
test('27,000 customization states validate without moving collision geometry',()=>{const C=R.CUSTOMIZATION,keys=Object.keys(C),base=JSON.stringify(R.OBSTACLES);let count=0;function walk(d,i){if(i===keys.length){assert.deepEqual(R.validDecor(d),d);count++;return;}for(const v of C[keys[i]])walk({...d,[keys[i]]:v},i+1);}walk({},0);assert.equal(count,27000);assert.equal(JSON.stringify(R.OBSTACLES),base);return {states:count,choices:Object.values(C).reduce((s,q)=>s+q.length,0)};});
test('All interaction/cleanup targets have reachable safe floor points',()=>{let count=0;for(const q of [R.KITCHEN,R.SINK,...R.TABLES.map(t=>t.meet),...R.CLEAN_TASKS]){const p=R.safePoint(q);assert(R.walkable(p.x,p.y));const nodes=R.pathfind({x:445,y:911},p);assert(nodes.length);for(const n of nodes)assert(R.walkable(n.x,n.y));count++;}return {targets:count};});
test('Safe migration of real Part 4-style partial recipe',()=>{const old=new R.Engine(),c=old.spawn(1);old.arrive(c.id);old.takeOrder(c.id);old.startRecipe(c.id,'pizza');old.act();old.act();const s=old.snapshot();s.schema=2;s.version='1.3.0-p4';delete s.phase;delete s.lunch;delete s.cleaning;delete s.pace;const e=new R.Engine(s);assert.equal(e.s.prep.p,2);assert.equal(e.s.prep.step,0);assert.equal(e.s.version,R.VERSION);assert.equal(e.s.schema,3);});
test('Completed older release stays complete, no forced extra guest',()=>{const s=R.fresh();s.schema=2;s.served=9;s.issued=9;s.completed=true;s.stickers=R.MENU.slice();const e=new R.Engine(s);assert(e.s.completed);assert.equal(e.s.phase,'complete');assert.equal(e.s.stickers.length,9);});
test('Older save past midpoint takes one safe catch-up lunch',()=>{const s=R.fresh();s.schema=2;s.served=7;s.issued=7;const e=new R.Engine(s);assert.equal(e.s.phase,'lunch');lunch(e);for(let i=0;i<3;i++)service(e);assert.equal(e.s.phase,'cleaning');});
test('Corrupt/unknown storage inputs fall back to playable fresh state',()=>{for(const raw of [null,{},[],0,'bad',{schema:999,customers:[]},{schema:3,customers:[null]},{schema:3,customers:[{id:1,table:99,dish:'pizza',variant:'tomato'}]}]){const e=new R.Engine(raw);assert.equal(e.s.served,0);assert(e.spawn(1));}});
test('Malformed carried table recovery avoids softlock',()=>{const s=R.fresh();s.tables[0]={status:'carried',dirty:null};s.issued=9;const e=new R.Engine(s);assert.equal(e.s.tables[0].status,'clean');assert.equal(e.s.issued,0);assert(e.spawn(1));});
test('Pacing cycles cozy/normal/busy, bounded speeds and capacity',()=>{const e=new R.Engine(),moods=new Set();let issued=0;for(let i=0;i<8000;i++){const c=e.paceTick(.1);moods.add(e.s.pace.mood);if(c){issued++;assert(e.guestSpeed(c)>=145&&e.guestSpeed(c)<=233);}assert(e.s.customers.length<=5);assert(e.s.issued<=5);}assert(moods.has('cozy'));assert(moods.has('normal'));assert(moods.has('busy'));return {moods:[...moods],issued,walkRange:'146–231px/s'};});
test('Pacing does not advance during lunch, cleaning or completed play',()=>{for(const phase of ['lunch','cleaning','closing','complete']){const e=new R.Engine();e.s.phase=phase;const q=JSON.stringify(e.s.pace);for(let i=0;i<100;i++)e.paceTick(.1);assert.equal(JSON.stringify(e.s.pace),q);}});
test('Replay retains decor, collection, mute and reduced-motion preferences',()=>{const e=new R.Engine();for(let i=0;i<5;i++)service(e);lunch(e);for(let i=0;i<5;i++)service(e);close(e);e.setDecor('tableType','heart');e.setDecor('tablecloth','rainbow');e.s.settings.muted=true;e.s.settings.reduced=true;const n=e.newDay();assert.equal(n.day,2);assert.equal(n.served,0);assert.equal(n.phase,'morning');assert(!n.lunch.done);assert.equal(n.decor.tableType,'heart');assert.equal(n.stickers.length,9);assert(n.settings.muted&&n.settings.reduced);assert(n.cleaning.every(t=>t.p===0));});
test('Partial pizza placements persist and no automatic meal packing',()=>{const e=new R.Engine(),c=e.spawn(1);e.arrive(c.id);e.takeOrder(c.id);e.startRecipe(c.id,'pizza');while(e.s.prep.step<4){const st=R.RECIPES.pizza.steps[e.s.prep.step];e.act(st.action==='choice'?'tomato':null);}e.act(null,{x:.12,y:.83});const f=new R.Engine(e.snapshot());assert.deepEqual(f.s.prep.placements,e.s.prep.placements);while(!f.s.prep.done)f.act(null,{x:.2,y:.3});assert(!f.s.tray);assert(f.packMeal());});
fs.writeFileSync(path.join(__dirname,'engine-results.json'),JSON.stringify({kind:'production-engine deterministic tests, not physical-device or UI testing',passed:result.filter(q=>q.pass).length,total:result.length,results:result},null,2));
if(result.some(q=>!q.pass))process.exitCode=1;
